import type {Draft,DraftAction,DraftValues} from './drafts';
/** Closed pure planner; clocks, queues, identifiers and effects belong to adapters. */
export function createAutosaveModel(){
 const editFields=['title','notes','order','flagged','parent_id','due_at'] as const;
 function savedValue(action:DraftAction,field:string):unknown{if(field==='tag_ids')return (action.tags||[]).map(tag=>tag.id).sort();if(field==='project_id')return action.project_id??null;return field==='deferDate'||field==='deferUntil'?action.defer_until??'':field==='parent_id'||field==='due_at'?action[field]??null:action[field as keyof DraftAction];}
 function equal(a:unknown,b:unknown){return Object.is(a,b)||Array.isArray(a)&&Array.isArray(b)&&JSON.stringify(a)===JSON.stringify(b);}
 function conflicts(draft:Draft,action:DraftAction,base:Partial<Record<keyof DraftValues,unknown>>):string[]{return Object.keys(draft.patch).filter(field=>field!=='timezone'&&Object.hasOwn(base,field)&&!equal(savedValue(action,field),base[field as keyof DraftValues])&&!equal(savedValue(action,field),draft.patch[field as keyof DraftValues]));}
 function validInstant(value:unknown):boolean{return value===null||value===''||typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d{1,3})?)?(?:Z|[+-]\d{2}:\d{2})$/.test(value)&&Number.isFinite(Date.parse(value));}
 function validation(draft:Draft){const errors:Record<string,string>={};const patch=draft.patch;if(!draft.title.trim())errors.title='Enter a Title.';if(draft.title.length>200)errors.title='Title must be at most 200 characters.';if(typeof patch.notes==='string'&&patch.notes.length>65536)errors.notes='Notes must be at most 65536 characters.';if(Object.hasOwn(patch,'due_at')&&!validInstant(patch.due_at))errors.due_at='Choose a complete Due date and time.';if(Object.hasOwn(patch,'deferUntil')&&!validInstant(patch.deferUntil))errors.deferUntil='Choose a complete Defer date and time.';return errors;}
 function plan(id:string,draft:Draft,mode:'date'|'until',saved?:DraftAction){
  if(!draft.title.trim())return {error:'Enter a Title.'};if(draft.title.length>200)return {error:'Title must be at most 200 characters.'};
  const captured:Partial<DraftValues>={};const payload:Record<string,unknown>={id};
  for(const field of editFields)if(Object.hasOwn(draft.patch,field)){Object.assign(captured,{[field]:draft.patch[field]});payload[field]=draft.patch[field];}
  if(Object.keys(captured).length){if(Object.hasOwn(payload,'order')&&(!Number.isInteger(payload.order)||Number(payload.order)<0))return {error:'Enter a nonnegative whole number for Order.'};if(Object.hasOwn(payload,'due_at')&&!validInstant(payload.due_at))return {error:'Choose a complete Due date and time.'};if(typeof payload.notes==='string'&&payload.notes.length>65536)return {error:'Notes must be at most 65536 characters.'};if(typeof payload.title==='string'&&!payload.title.trim())return {error:'Enter a Title.'};if(typeof payload.title==='string'&&payload.title.length>200)return {error:'Title must be at most 200 characters.'};return {kind:'edit',payload,captured};}
  if(Object.hasOwn(draft.patch,'status'))return {kind:'status',payload:{id,status:draft.status},captured:{status:draft.status}};
  if(draft.dirtyGroups.defer){const key=mode==='date'?'deferDate':'deferUntil';if(!Object.hasOwn(draft.patch,key))return {error:'Finish the Defer input.'};const value=draft[key];const captured:Partial<DraftValues>={};for(const field of ['deferDate','deferUntil','timezone'] as const)if(Object.hasOwn(draft.patch,field))Object.assign(captured,{[field]:draft.patch[field]});if(Object.hasOwn(draft.patch,'timezone'))captured.timezone=draft.timezone;if(!value)return {kind:'release',payload:{id},captured};if(mode==='date'){if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value+'T00:00:00Z'))||new Date(value+'T00:00:00Z').toISOString().slice(0,10)!==value)return {error:'Enter a complete Defer date.'};if(!draft.timezone)return {error:'A timezone is needed for this Defer date.'};return {kind:'defer',payload:{id,date:value,timezone:draft.timezone},captured};}if(!validInstant(value))return {error:'Choose a complete Defer date and time.'};return {kind:'defer',payload:{id,until:value},captured};}
  if(Object.hasOwn(draft.patch,'project_id'))return equal(draft.project_id,saved?.project_id??null)?{noop:true,captured:{project_id:draft.project_id}}:{kind:'action_project',payload:{id,project_id:draft.project_id},captured:{project_id:draft.project_id}};
  if(Object.hasOwn(draft.patch,'tag_ids')){const actual=(saved?.tags||[]).map(tag=>tag.id).sort(),desired=[...draft.tag_ids].sort();const changed=[...new Set([...actual,...desired])].filter(tag=>actual.includes(tag)!==desired.includes(tag));if(!changed.length)return {noop:true,captured:{tag_ids:desired}};const tag_id=changed[0];return {kind:'action_tag',payload:{id,tag_id,enabled:desired.includes(tag_id)},captured:changed.length===1?{tag_ids:desired}:{}};}
  return {empty:true};
 }
 function pending(queued:Draft,current:Draft):Draft{const patch:Partial<DraftValues>={};for(const field of Object.keys(queued.patch) as (keyof DraftValues)[])if(Object.hasOwn(current.patch,field))Object.assign(patch,{[field]:queued.patch[field]});const fields=Object.keys(patch);return {...queued,patch,dirty:fields.length>0,dirtyGroups:{edit:fields.some(f=>editFields.includes(f as typeof editFields[number])),status:fields.includes('status'),defer:fields.some(f=>['deferDate','deferUntil','timezone'].includes(f))}};}
 return {savedValue,conflicts,plan,pending,equal,validation};
}
