import type {NavigationSnapshot,NavigationCatalog,NavigationAction,NavigationFilter} from './navigation';
export interface OutlineEntry {key:string;kind:'project'|'tag'|'group'|'action';id:string;level:number;label:string;parentKey:string|null;catalogId:string|null;expandable:boolean;action?:NavigationAction}
/** Catalog membership is direct; containment affects indentation only inside a membership. */
export function createCatalogTreeModel(){
 function outline(snapshot:NavigationSnapshot,view:'projects'|'tags',filter:NavigationFilter,collapsed:readonly string[]=[],revealId:string|null=null){const kind=view==='projects'?'project':'tag',catalog=[...(view==='projects'?snapshot.projects||[]:snapshot.tags||[])].map(record=>{if(!Number.isSafeInteger(record.order)||record.order<0)throw Error('Catalog order is invalid.');return record;}).sort((a,b)=>(a.order-b.order)||(a.name<b.name?-1:a.name>b.name?1:0)||(a.id<b.id?-1:a.id>b.id?1:0)),eligible=snapshot.actions.filter(a=>a.id===revealId||(!Object.hasOwn(filter,'statuses')||filter.statuses!.includes(a.status))&&(!Object.hasOwn(filter,'is_deferred')||Boolean(a.is_deferred)===filter.is_deferred)),entries:OutlineEntry[]=[],visited=new Set<string>();
  function members(id:string|null){return eligible.filter(a=>kind==='project'?(a.project_id??null)===id:id===null?!(a.tags||[]).length:a.tags?.some(t=>t.id===id));}
  function actions(id:string|null,level:number,parentKey:string){const rows=members(id),seen=new Set<string>();function visit(action:NavigationAction,depth:number,parent:string){if(seen.has(action.id))return;seen.add(action.id);const key=parentKey+':action:'+action.id;entries.push({key,kind:'action',id:action.id,level:depth,label:action.title,parentKey:parent,catalogId:id,expandable:false,action});for(const child of rows.filter(a=>a.parent_id===action.id))visit(child,depth+1,key);}for(const action of rows)if(!rows.some(p=>p.id===action.parent_id))visit(action,level,parentKey);for(const action of rows)visit(action,level,parentKey);}
  function node(record:NavigationCatalog,level:number,parentKey:string|null){if(visited.has(record.id))return;visited.add(record.id);const key=kind+':'+record.id,children=catalog.filter(c=>c.parent_id===record.id);entries.push({key,kind,id:record.id,level,label:record.name||'Untitled '+kind,parentKey,catalogId:record.id,expandable:Boolean(children.length||members(record.id).length)});if(collapsed.includes(key))return;actions(record.id,level+1,key);for(const child of children)node(child,level+1,key);}
  for(const record of catalog)if(!record.parent_id||!catalog.some(parent=>parent.id===record.parent_id))node(record,0,null);for(const record of catalog){let parent=record.parent_id,hidden=false;const chain=new Set<string>();while(parent&&!chain.has(parent)){chain.add(parent);if(collapsed.includes(kind+':'+parent)){hidden=true;break;}parent=catalog.find(p=>p.id===parent)?.parent_id;}if(!hidden)node(record,0,null);}const key=kind+':none';entries.push({key,kind:'group',id:kind==='project'?'unassigned':'untagged',level:0,label:kind==='project'?'Unassigned':'Untagged',parentKey:null,catalogId:null,expandable:Boolean(members(null).length)});if(!collapsed.includes(key))actions(null,1,key);return entries;
 }
 function reveal(snapshot:NavigationSnapshot,view:string,id:string,collapsed:readonly string[]){if(view!=='projects'&&view!=='tags')return [...collapsed];const kind=view==='projects'?'project':'tag',action=snapshot.actions.find(a=>a.id===id);if(!action)return [...collapsed];const catalog=view==='projects'?snapshot.projects||[]:snapshot.tags||[],groups=view==='projects'?[action.project_id??null]:(action.tags?.length?action.tags.map(t=>t.id):[null]),open=new Set<string>();for(const group of groups){if(group===null){open.add(kind+':none');continue;}let node=catalog.find(n=>n.id===group);while(node&&!open.has(kind+':'+node.id)){open.add(kind+':'+node.id);node=catalog.find(n=>n.id===node!.parent_id);}}return collapsed.filter(key=>!open.has(key));}
 function label(catalog:readonly NavigationCatalog[],id:string,kind:'project'|'tag'){const parts:string[]=[],seen=new Set<string>();let node=catalog.find(n=>n.id===id);while(node&&!seen.has(node.id)){seen.add(node.id);parts.unshift(node.name||'Untitled '+kind);node=catalog.find(n=>n.id===node!.parent_id);}return parts.join(' / ');}
 function range(anchor:string|null,key:string,entries:readonly OutlineEntry[],shift:boolean){const visible=entries.filter(e=>e.kind==='action').map(e=>e.key);if(!visible.includes(key))return {keys:[] as string[],anchor:null};if(shift&&anchor&&visible.includes(anchor)){const a=visible.indexOf(anchor),b=visible.indexOf(key);return {keys:visible.slice(Math.min(a,b),Math.max(a,b)+1),anchor};}return {keys:[key],anchor:key};}
 return {outline,range,label,reveal};
}
