export type CatalogKind='project'|'tag';
export interface CatalogRecord {id:string;name:string;description?:string;parent_id?:string|null}
export interface CatalogDraft {kind:CatalogKind;id:string;name:string;description:string;patch:Partial<{name:string;description:string}>;base:{name:string;description:string}}
/** Separate namespaces prevent catalog IDs and Action drafts from sharing fields. */
export function createCatalogDraftModel(){
 function merge(previous:Record<string,CatalogDraft>,projects:readonly CatalogRecord[],tags:readonly CatalogRecord[]){const next:Record<string,CatalogDraft>={};for(const [key,draft] of Object.entries(previous))if(Object.keys(draft.patch).length)next[key]=draft;for(const [kind,records] of [['project',projects],['tag',tags]] as const)for(const record of records){const key=kind+':'+record.id,old=previous[key],saved={name:record.name,description:record.description||''};next[key]={kind,id:record.id,...saved,...old?.patch,patch:{...old?.patch},base:{name:old?.patch.name!==undefined?old.base.name:saved.name,description:old?.patch.description!==undefined?old.base.description:saved.description}};}return next;}
 function edit(previous:Record<string,CatalogDraft>,key:string,patch:Partial<{name:string;description:string}>){const old=previous[key];if(!old)throw Error('Catalog is unavailable');const actual={...old.patch};for(const [field,value] of Object.entries(patch) as [keyof typeof patch,string][]){if(value===old[field]&&!Object.hasOwn(actual,field))continue;actual[field]=value;}return {...previous,[key]:{...old,...patch,patch:actual}};}
 function acknowledge(previous:Record<string,CatalogDraft>,key:string,captured:CatalogDraft['patch']){const old=previous[key];if(!old)return previous;const patch={...old.patch},base={...old.base};for(const [field,value] of Object.entries(captured) as [keyof CatalogDraft['patch'],string][]){base[field]=field==='name'?value.trim():value;if(patch[field]===value)delete patch[field];}return {...previous,[key]:{...old,patch,base}};}
 function validation(draft:CatalogDraft){const errors:Record<string,string>={};if(!draft.name.trim())errors.name='Enter a name.';if(draft.name.length>200)errors.name='Name must be at most 200 characters.';if(draft.patch.description!==undefined&&draft.patch.description.length>65536)errors.description='Description must be at most 65536 characters.';return errors;}
 function conflicts(draft:CatalogDraft,record:CatalogRecord){return (Object.keys(draft.patch) as (keyof CatalogDraft['patch'])[]).filter(field=>{const saved=record[field]||'',proposed=draft.patch[field]||'';return saved!==draft.base[field]&&saved!==(field==='name'?proposed.trim():proposed);});}
 function resolve(previous:Record<string,CatalogDraft>,key:string,record:CatalogRecord,fields:string[],mine:boolean){const old=previous[key],patch={...old.patch},base={...old.base};for(const field of fields as (keyof CatalogDraft['patch'])[]){base[field]=record[field]||'';if(!mine)delete patch[field];}return {...previous,[key]:{...old,name:record.name,description:record.description||'',...patch,patch,base}};}
 return {merge,edit,acknowledge,conflicts,resolve,validation};
}
