/** Calendar values are resolved against injected timezone formatting, never the clock. */
export function createDateInputModel(){
 function localValue(instant:string|null|undefined,formatAt:(milliseconds:number)=>string):string{if(!instant||!Number.isFinite(Date.parse(instant)))return '';const at=Date.parse(instant),fraction=new Date(at).getUTCMilliseconds();return formatAt(at)+(fraction?'.'+String(fraction).padStart(3,'0'):'');}
 function resolve(value:string,formatAt:(milliseconds:number)=>string){try{if(!value)return {value:null,error:''};if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d{1,3})?)?$/.test(value))return {value:null,error:'Choose a complete date and time.'};const local=value.length===16?value+':00':value,naive=Date.parse(local+'Z'),seconds=local.slice(0,19);if(!Number.isFinite(naive)||new Date(naive).toISOString().slice(0,19)!==seconds)return {value:null,error:'Choose a valid date and time.'};const offsets=new Set<number>();for(let hours=-48;hours<=48;hours+=6){const at=Math.floor(naive/1000)*1000+hours*3600000;offsets.add(Date.parse(formatAt(at)+'Z')-at);}const matches=[...offsets].map(offset=>naive-offset).filter(at=>formatAt(at)===seconds);if(matches.length!==1)return {value:null,error:matches.length?'This time occurs twice in your timezone. Choose an unambiguous time.':'This time does not exist in your timezone. Choose another time.'};return {value:new Date(matches[0]).toISOString(),error:''};}catch{return {value:null,error:'Your timezone could not be resolved. Choose a valid timezone before saving.'};}}
 function clock(raw:string){let value=raw;if(/^(?:\d{3,6}(?:\.\d{1,3})?)$/.test(raw))value=raw.slice(0,2)+':'+raw.slice(2,4)+(raw.length>4?':'+raw.slice(4):'');else if(/^\d{2}:\d{3,4}(?:\.\d{1,3})?$/.test(raw))value=raw.slice(0,5)+':'+raw.slice(5);return /^\d{2}:\d{2}:00$/.test(value)?value.slice(0,5):value;}
 function clockMask(raw:string){if(!/^(?:\d{0,2})(?::\d{0,2})?(?::\d{0,2}(?:\.\d{0,3})?)?$/.test(raw))return '';const parts=raw.split(':');const display=[0,1,2].map(index=>index<parts.length-1?parts[index]:(parts[index]||'').padEnd(2,'-')).join(':');return display.startsWith(raw)?display.slice(raw.length):'';}
 function pair(instant:string|null|undefined,formatAt:(milliseconds:number)=>string){const local=localValue(instant,formatAt);return {date:local.slice(0,10),time:clock(local.slice(11)),value:instant||'',error:'',timeEdited:false,badDate:false,badTime:false};}
 function feedback(current:ReturnType<typeof pair>){if(!current.error)return {message:'',date:false,time:false};const date=current.badDate||!/^\d{4}-\d{2}-\d{2}$/.test(current.date),time=current.badTime||!/^\d{2}:\d{2}(?::\d{2}(?:\.\d{1,3})?)?$/.test(current.time);return {message:current.error,date:date||!time,time:time||!date};}
 function editPair(current:ReturnType<typeof pair>,part:'date'|'time',raw:string,badInput:boolean,formatAt:(milliseconds:number)=>string){const next={...current,[part]:part==='time'?clock(raw):raw,...(part==='time'?{timeEdited:true}:{}),[part==='date'?'badDate':'badTime']:badInput};if(part==='date'&&!raw&&!badInput)return {...pair(null,formatAt),value:''};if(part==='date'&&raw&&!next.time&&!next.timeEdited)next.time='09:00';if(next.badDate||next.badTime)return {...next,error:'Finish choosing the date and time.'};if(!next.date||!next.time)return {...next,error:'Choose a complete date and time.'};const resolved=resolve(next.date+'T'+next.time,formatAt);return {...next,value:resolved.value||'',error:resolved.error};}
 return {localValue,resolve,pair,editPair,clock,clockMask,feedback};
}
