export interface MovementAction {id:string;parent_id?:string|null;project_id?:string|null;order:number}
export type MovePlacement='before'|'after'|'inside'|'root';
export interface MovePayload {ids:string[];placement:MovePlacement;anchor_id?:string}
/** Closed deterministic UI intent model; backend owns authoritative rank changes. */
export function createMovementModel(){
 function ordered(actions:readonly MovementAction[]):MovementAction[]{const compare=(a:MovementAction,b:MovementAction)=>a.order-b.order||(a.id<b.id?-1:a.id>b.id?1:0);const out:MovementAction[]=[],seen=new Set<string>();function visit(a:MovementAction){if(seen.has(a.id))return;seen.add(a.id);out.push(a);for(const child of actions.filter(c=>c.parent_id===a.id).sort(compare))visit(child);}const roots=actions.filter(a=>!a.parent_id).sort((a,b)=>((a.project_id??'')<(b.project_id??'')?-1:(a.project_id??'')>(b.project_id??'')?1:0)||compare(a,b));for(const root of roots)visit(root);return out;}
 function contains(actions:readonly MovementAction[],ancestor:string,id:string):boolean{const seen=new Set<string>();let row=actions.find(a=>a.id===id);while(row?.parent_id){if(row.parent_id===ancestor)return true;if(seen.has(row.parent_id))return true;seen.add(row.parent_id);row=actions.find(a=>a.id===row!.parent_id);}return false;}
 function relevant(actions:readonly MovementAction[],payload:MovePayload):string[]{const selected=actions.filter(a=>payload.ids.includes(a.id)),anchor=actions.find(a=>a.id===payload.anchor_id),parent=payload.placement==='inside'?anchor?.id:anchor?.parent_id??null;return actions.filter(a=>payload.ids.includes(a.id)||payload.ids.some(id=>contains(actions,id,a.id)||contains(actions,a.id,id))||a.id===anchor?.id||Boolean(anchor&&contains(actions,a.id,anchor.id))||(payload.placement==='root'?!a.parent_id&&selected.some(root=>(root.project_id??null)===(a.project_id??null)):a.parent_id===parent&&(parent!==null||(a.project_id??null)===(anchor?.project_id??null)))).map(a=>a.id);}
 function sourceFingerprint(actions:readonly MovementAction[],ids:readonly string[]):string{return JSON.stringify(actions.filter(a=>ids.some(id=>a.id===id||contains(actions,id,a.id)||contains(actions,a.id,id))).map(a=>[a.id,a.parent_id??null,a.project_id??null,a.order]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))));}
 function fingerprint(actions:readonly MovementAction[],payload?:MovePayload):string{const ids=payload?relevant(actions,payload):actions.map(a=>a.id);return JSON.stringify(actions.filter(a=>ids.includes(a.id)).map(a=>[a.id,a.parent_id??null,a.project_id??null,a.order]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))));}
 function intent(actions:readonly MovementAction[],ids:readonly string[],placement:MovePlacement,anchorId?:string){const rejected=(reason:string)=>({allowed:false,reason,roots:[] as string[],payload:null as MovePayload|null});if(!['before','after','inside','root'].includes(placement))return rejected('Choose a valid placement.');if(!ids.length)return rejected('Select an action to move.');if(new Set(ids).size!==ids.length||ids.some(id=>!actions.some(a=>a.id===id)))return rejected('The selection is no longer available.');const selected=new Set(ids),roots=ordered(actions).filter(a=>selected.has(a.id)&&!ids.some(id=>id!==a.id&&contains(actions,id,a.id)));if(!roots.length)return rejected('The selection is no longer available.');if(placement!=='root'){const anchor=actions.find(a=>a.id===anchorId);if(!anchor)return rejected('Choose an available destination.');if(roots.some(a=>a.id===anchor.id||contains(actions,a.id,anchor.id)))return rejected('An action cannot move into its own subtree.');if((placement==='before'||placement==='after')&&!anchor.parent_id&&roots.some(a=>(a.project_id??null)!==(anchor.project_id??null)))return rejected('Choose a destination in the same Project, or move Into the action.');}const payload:MovePayload={ids:roots.map(a=>a.id),placement,...(placement==='root'?{}:{anchor_id:anchorId!})};return {allowed:true,reason:'',roots:payload.ids,payload};}
 function selection(current:readonly string[],anchor:string|null,id:string,visible:readonly string[],range:boolean){if(!visible.includes(id))return {ids:[...current],anchor};if(range&&anchor&&visible.includes(anchor)){const a=visible.indexOf(anchor),b=visible.indexOf(id);return {ids:visible.slice(Math.min(a,b),Math.max(a,b)+1),anchor};}return {ids:[id],anchor:id};}
 return {ordered,contains,fingerprint,intent,selection,relevant,sourceFingerprint};
}
