import type {Draft,DraftAction} from './drafts';
import type {CatalogDraft,CatalogRecord} from './catalog-drafts';
export type TransientKind='action'|'project'|'tag';
export interface TransientRecord {id:string;kind:TransientKind;context:Record<string,unknown>;edited:boolean;pending:boolean;token:number}
/** Local identities never cross the persistence port. Snapshots remain authoritative. */
export function createTransientModel(){
 function isLocal(id:unknown):id is string{return typeof id==='string'&&id.startsWith('local:');}
 function add(previous:Record<string,TransientRecord>,kind:TransientKind,id:string,context:Record<string,unknown>,token=0){return {...previous,[id]:{id,kind,context:JSON.parse(JSON.stringify(context)),edited:false,pending:false,token}};}
 function overlay(snapshot:(Record<string,unknown>&{actions:DraftAction[]})|null,records:Record<string,TransientRecord>,drafts:Readonly<Record<string,Draft>>,catalogDrafts:Record<string,CatalogDraft>){if(!snapshot)return snapshot;const next={...snapshot,actions:[...snapshot.actions] as (DraftAction&{is_deferred?:boolean})[],projects:[...((snapshot.projects||[]) as (CatalogRecord&{order?:number;revision?:number;path?:string})[])],tags:[...((snapshot.tags||[]) as (CatalogRecord&{order?:number;revision?:number;path?:string})[])]};for(const row of Object.values(records)){if(row.kind==='action'){const d=drafts[row.id];next.actions.push({id:row.id,revision:0,title:d?.title||'',notes:d?.notes||'',status:d?.status||'active',order:d?.order??Number.MAX_SAFE_INTEGER,flagged:d?.flagged??Boolean(row.context.flagged),parent_id:d?d.parent_id:row.context.parent_id as string??null,project_id:d?d.project_id:row.context.project_id as string??null,tags:((d?.tag_ids||row.context.tag_ids||[]) as string[]).map((id:string)=>({id})),due_at:d?.due_at??null,defer_until:d?.deferUntil||null,is_deferred:Boolean(d?.deferUntil)});}else{const d=catalogDrafts[row.kind+':'+row.id];next[row.kind==='project'?'projects':'tags'].push({id:row.id,revision:0,order:Number.MAX_SAFE_INTEGER,name:d?.name||'',description:d?.description||'',parent_id:row.context.parent_id as string??null,path:d?.name||''});}}const scopes=(snapshot.list_scopes||{}) as Record<string,string[]>;return {...next,list_scopes:{...Object.fromEntries(Object.entries(scopes).map(([key,ids])=>[key,[...ids]])),inbox:[...(scopes.inbox||[]),...next.actions.filter(action=>isLocal(action.id)&&!action.project_id&&(action.status==='active'||action.status==='on-hold')).map(action=>action.id)]}};}
 function references(row:TransientRecord,draft:Draft|CatalogDraft|undefined):string[]{const action=draft as Draft|undefined;const values=row.kind==='action'?[action?.parent_id,action?.project_id,...(action?.tag_ids||[])]:[row.context.parent_id];return values.filter(isLocal);}
 function eligible(row:TransientRecord,draft:Draft|CatalogDraft|undefined){const action=draft as Draft|undefined,catalog=draft as CatalogDraft|undefined;return row.kind==='action'?Boolean(action?.title?.trim())&&action!.title.length<=200:Boolean(catalog?.name?.trim())&&catalog!.name.length<=200;}
 function prune(records:Record<string,TransientRecord>,drafts:Readonly<Record<string,Draft>>,catalogDrafts:Record<string,CatalogDraft>,protectedIds:readonly string[]=[]){const required=new Set<string>();function visit(id:string){if(required.has(id))return;required.add(id);const parent=records[id];if(parent)for(const ref of references(parent,parent.kind==='action'?drafts[id]:catalogDrafts[parent.kind+':'+id]))visit(ref);}for(const id of protectedIds)visit(id);for(const [id,draft] of Object.entries(drafts))if(draft.dirty&&!records[id])for(const ref of references({id,kind:'action',context:{},edited:true,pending:false,token:0},draft))visit(ref);for(const row of Object.values(records))if(row.edited||row.pending)visit(row.id);return Object.fromEntries(Object.entries(records).filter(([id,row])=>row.edited||row.pending||required.has(id)));}
 function replace<T>(value:T,from:string,to:string):T{const identities=new Set(['id','parent_id','project_id','tag_ids','ids','classificationId','perspectiveId','target','targetId']);function visit(item:unknown,key=''):unknown{if(typeof item==='string')return identities.has(key)&&item===from?to:item;if(Array.isArray(item))return item.map(entry=>visit(entry,key));if(item&&typeof item==='object')return Object.fromEntries(Object.entries(item).map(([field,entry])=>[field,visit(entry,field)]));return item;}return visit(value) as T;}


 function replacement(records:Record<string,TransientRecord>,drafts:Readonly<Record<string,Draft>>,catalogDrafts:Record<string,CatalogDraft>,selected:string|null,context:Record<string,unknown>,unknown:boolean){const row=selected?records[selected]:undefined;if(!row)return {allowed:true,context:{...context},remove:null};if(row.pending||unknown)return {allowed:false,reason:'Check the pending save before replacing this draft.'};if(prune({...records,[row.id]:{...row,edited:false}},drafts,catalogDrafts)[row.id])return {allowed:false,reason:'Another draft depends on this item. Change its parent or classification first.'};const next={...context},action=drafts[row.id];let valid=true;function persistedParent(initial:unknown):unknown{let value=initial;const seen=new Set<string>();while(isLocal(value)){if(seen.has(value)){valid=false;return null;}seen.add(value);const parent=records[value];if(!parent){valid=false;return null;}value=parent.kind==='action'&&drafts[value]?drafts[value].parent_id:parent.context.parent_id??null;}return value??null;}if(next.parent_id===row.id)next.parent_id=persistedParent(row.kind==='action'&&action?action.parent_id:row.context.parent_id);if(!valid)return {allowed:false,reason:'The draft parent is unavailable. Choose an existing parent first.'};if(next.project_id===row.id)next.project_id=null;if(Array.isArray(next.tag_ids))next.tag_ids=next.tag_ids.filter(id=>id!==row.id);return {allowed:true,context:next,remove:row.id};}
 return {isLocal,add,overlay,references,eligible,prune,replace,replacement};
}
