import test from 'node:test';import assert from 'node:assert/strict';import {createDateInputModel} from '../../lib/ui/model/date-input.ts';
const model=createDateInputModel();function format(zone){const f=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});return at=>{const p=f.formatToParts(new Date(at)),get=key=>p.find(x=>x.type===key).value;return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}:${get('second')}`;};}
test('calendar explicit timezone round trips instants and milliseconds without rewriting saved data',()=>{for(const zone of ['Asia/Tokyo','America/New_York','Asia/Kathmandu','Australia/Lord_Howe']){const saved='2026-10-03T00:12:15.123Z',local=model.localValue(saved,format(zone));assert.equal(model.resolve(local,format(zone)).value,saved);}assert.equal(model.resolve('2026-10-03T18:00',format('Asia/Tokyo')).value,'2026-10-03T09:00:00.000Z');assert.equal(model.resolve('',format('Asia/Tokyo')).value,null);});
test('calendar rejects impossible dates and daylight-saving gaps/folds without choosing an instant',()=>{const f=format('America/New_York');for(const local of ['2026-02-30T12:00','2026-03-08T02:30','2026-11-01T01:30']){const result=model.resolve(local,f);assert.equal(result.value,null);assert.ok(result.error);}assert.match(model.resolve('2026-11-01T01:30',f).error,/twice/);assert.match(model.resolve('2026-03-08T02:30',f).error,/not exist/);});
test('one Defer pair defaults only a new date to09, preserves custom precision, and distinguishes partial time from deliberate date clear',()=>{const f=format('Asia/Tokyo'),empty=model.pair(null,f),selected=model.editPair(empty,'date','2026-10-04',false,f);assert.equal(selected.time,'09:00');assert.equal(selected.value,'2026-10-04T00:00:00.000Z');const custom=model.editPair(selected,'time','14:23:45.123',false,f),changed=model.editPair(custom,'date','2026-10-05',false,f);assert.equal(changed.value,'2026-10-05T05:23:45.123Z');const partial=model.editPair(changed,'time','',false,f);assert.ok(partial.error);assert.equal(model.editPair(partial,'date','2026-10-06',false,f).time,'');assert.equal(model.editPair(changed,'date','',true,f).error,'Finish choosing the date and time.');assert.equal(model.editPair(changed,'date','',false,f).value,'');assert.equal(model.editPair(model.editPair(changed,'date','',false,f),'date','2026-10-07',false,f).time,'09:00');assert.deepEqual(empty,model.pair(null,f));assert.equal(model.pair(custom.value,f).time,'14:23:45.123');const gap=model.editPair(model.editPair(model.pair(null,format('America/New_York')),'date','2026-03-08',false,format('America/New_York')),'time','02:30',false,format('America/New_York'));assert.match(gap.error,/not exist/);});

test('24-hour numeric clock input normalizes only complete values and keeps nonzero precision',()=>{const f=format('Asia/Tokyo');assert.equal(model.pair('2026-10-04T00:00:00.000Z',f).time,'09:00');for(const [raw,time] of [['1430','14:30'],['143015','14:30:15'],['143015.123','14:30:15.123']]){const result=model.editPair(model.pair('2026-10-04T00:00:00.000Z',f),'time',raw,false,f);assert.equal(result.time,time);assert.equal(result.error,'');}for(const raw of ['14','143','14301','25:00'])assert.ok(model.editPair(model.pair('2026-10-04T00:00:00.000Z',f),'time',raw,false,f).error);});
test('date/time feedback identifies incomplete responsible parts and retains joint DST errors',()=>{const f=format('America/New_York'),date=model.editPair(model.pair(null,f),'date','2026-03-08',false,f),partial=model.editPair(date,'time','13:',false,f);assert.deepEqual(model.feedback(partial),{message:partial.error,date:false,time:true});const gap=model.editPair(date,'time','02:30',false,f);assert.deepEqual(model.feedback(gap),{message:gap.error,date:true,time:true});assert.deepEqual(model.feedback(model.pair(null,f)),{message:'',date:false,time:false});});

test('clock mask preserves missing segments and progressively separates all six numeric digits',()=>{for(const [raw,expected] of [['1','1'],['13','13'],['131','13:1'],['1317','13:17'],['13:171','13:17:1'],['13:1715','13:17:15']])assert.equal(model.clock(raw),expected);for(const [raw,tail] of [['','--:--:--'],['1','-:--:--'],['13',':--:--'],['13:1','-:--'],['13:17',':--'],['13:17:1','-'],['13:17:45.123','']])assert.equal(model.clockMask(raw),tail);const current=model.pair(null,format('Asia/Tokyo'));assert.ok(model.editPair({...current,date:'2026-10-04'},'time','13:17:1',false,format('Asia/Tokyo')).error);});
