import test from 'node:test';
import {JSDOM} from 'jsdom';
import assert from 'node:assert/strict';
import {dateDefer} from '../../lib/domain/core.ts';
import {widgetHtml} from '../../lib/widget.ts';
import {verificationWidgetHtml} from '../../lib/verification-widget.ts';
const settle=async()=>{for(let i=0;i<80;i++)await Promise.resolve();};
async function fillCreation(f,field='editTitle',value='New action'){const node=f.dom.window.document.getElementById(field);node.value=value;node.dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));node.dispatchEvent(new f.dom.window.Event('blur'));await settle();}
function selectFirst(f){f.dom.window.document.querySelector('.action-select')?.click();}
function createFixture(html=widgetHtml,options={}){
const action={id:'d2adf59d-e631-4e65-95d2-35a6558d36c5',title:'保存済み',notes:'',revision:1,status:'active',view:'normal',parent_id:null,due_at:null,defer_until:null,defer_reasons:[],order:0,flagged:false,project_id:null};
let state={schemaVersion:2,revision:1,projects:[],tags:[],perspectives:[],actions:[action],list_scopes:{inbox:[action.id],waiting:[],flagged:[]},retrieved_at:'2026-10-01T00:00:00Z'};
let lost=false,lastLost=null;const requests=[],timers=new Map(),frames=new Map();let frameId=0,frameTime=0;
const dom=new JSDOM(html,{url:'https://fictional.invalid',runScripts:'dangerously',beforeParse(w){
 w.requestAnimationFrame=callback=>{const id=++frameId;frames.set(id,callback);return id;};w.cancelAnimationFrame=id=>frames.delete(id);
 const timeout=w.setTimeout.bind(w),clear=w.clearTimeout.bind(w);let timer=100;
 w.setTimeout=(fn,ms)=>{if(ms===20000||ms===500){const n=++timer;timers.set(n,fn);return n;}return timeout(fn,ms);};w.clearTimeout=n=>{timers.delete(n);clear(n);};
 if(options.resizeObserver)w.ResizeObserver=options.resizeObserver;
 w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 w.postMessage=m=>{if(m.id==null)return;let result;
 if(m.method==='ui/initialize')result=options.initialize||{};else if(m.method==='ui/request-display-mode'){requests.push({method:m.method,args:structuredClone(m.params)});result={mode:options.actualMode||m.params.mode};}else{const {name,arguments:a}=m.params;requests.push({name,args:structuredClone(a)});
  if(name==='list_actions')result={structuredContent:structuredClone(state)};
  else if(name==='preview_change'&&options.previewError)result={isError:true,structuredContent:{error:options.previewError}};
  else if(name==='preview_change')result={structuredContent:{expectedRevision:state.revision,kind:a.kind,payload:a.kind==='defer'&&a.payload.date?{id:a.payload.id,until:dateDefer(a.payload.date,a.payload.timezone)}:a.payload,affected:[action],warnings:options.warnings||[],evaluatedAt:state.retrieved_at}};
  else if(name==='apply_change'&&a.kind==='add'){if(lost){lastLost=m;return;}const createdId='f25a36bb-3eef-4c21-b3ee-0cc45cb596ab';let created=state.actions.find(x=>x.id===createdId);if(!created){created={...action,...a.payload,id:createdId,title:a.payload.title,notes:a.payload.notes,project_id:a.payload.project_id??null,tags:(a.payload.tag_ids||[]).map(id=>({id,name:state.tags?.find(t=>t.id===id)?.name||id}))};state.actions.push(created);if(created.project_id===null)state.list_scopes.inbox.push(created.id);state.revision++;}result={structuredContent:{...structuredClone(state),result:{operationId:a.operationId,resolved:{actions:[{id:createdId}]}}}};}
  else if(name==='apply_change'&&['project_get_or_create','tag_get_or_create','project_add','tag_add'].includes(a.kind)){if(lost){lastLost=m;return;}const kind=a.kind.startsWith('project')?'project':'tag',catalog=state[kind==='project'?'projects':'tags']||(state[kind==='project'?'projects':'tags']=[]);let record=a.kind.endsWith('_add')?null:catalog.find(n=>n.name===a.payload.name.trim()&&(n.parent_id??null)===(a.payload.parent_id??null));const created=!record;if(!record){record={id:kind==='project'?'63620a50-eaa0-4e5c-8022-a8e84940a6b2':'31879f0d-4a9c-44a6-af42-0f3f5f03b8ce',name:a.payload.name.trim(),description:'',parent_id:a.payload.parent_id??null,order:0};catalog.push(record);state.revision++;}result={structuredContent:{...structuredClone(state),result:{operationId:a.operationId,resolved:{[kind]:{id:record.id,created}}}}};}
  else if(name==='apply_change'&&['project_edit','tag_edit'].includes(a.kind)){if(lost){lastLost=m;return;}const catalog=state[a.kind==='project_edit'?'projects':'tags'],target=catalog.find(n=>n.id===a.payload.id);Object.assign(target,a.payload);if(a.payload.name!==undefined)target.name=a.payload.name.trim();state.revision++;result={structuredContent:{...structuredClone(state),result:{operationId:a.operationId}}};}
  else if(name==='apply_change'){if(lost){lastLost=m;return;}const target=state.actions.find(x=>x.id===a.payload.id)||action;if(a.kind==='action_tag'){target.tags=target.tags||[];if(a.payload.enabled&&!target.tags.some(tag=>tag.id===a.payload.tag_id))target.tags.push({id:a.payload.tag_id});if(!a.payload.enabled)target.tags=target.tags.filter(tag=>tag.id!==a.payload.tag_id);}else if(a.kind==='complete'){target.status='completed';target.view='completed';}else if(a.kind==='release'){target.defer_until=null;target.defer_reasons=[];}else if(a.kind==='defer'){target.defer_until=a.payload.until;}else if(a.kind==='status'){target.status=a.payload.status;state.list_scopes.waiting=target.status==='on-hold'?[target.id]:[];}else{Object.assign(target,a.payload);}state.list_scopes.flagged=target.flagged&&target.view==='normal'?[target.id]:[];target.revision++;state.revision++;result={structuredContent:{...structuredClone(state),result:{operationId:a.operationId}}};}
  else if(name==='capture_intent'){if(lost){lastLost=m;return;}const captured={...action,id:'f25a36bb-3eef-4c21-b3ee-0cc45cb596ab',title:a.title,notes:a.text};state.actions.push(captured);state.list_scopes.inbox.push(captured.id);state.revision++;result={structuredContent:{...structuredClone(state),result:{operationId:a.operationId}}};}
  else if(name==='add_action'){if(lost){lastLost=m;return;}result={structuredContent:{...structuredClone(state),result:{operationId:a.request_id}}};}
  else if(name==='operation_status')result={structuredContent:{status:'not_observed',result:null}};
 }
 queueMicrotask(()=>w.dispatchEvent(new w.MessageEvent('message',{source:w,data:{jsonrpc:'2.0',id:m.id,result}})));
 };
}});
return {action,state,requests,timers,dom,frameCount:()=>frames.size,flushFrames(){for(let count=0;frames.size&&count<20;count++){const callbacks=[...frames.values()];frames.clear();frameTime+=16;for(const callback of callbacks)callback(frameTime);}},setLost:value=>{lost=value;},lostRequest:()=>lastLost};
}
test('verification resource discards real successful write response and preserves exact-ID recovery',async(t)=>{
 const f=createFixture(verificationWidgetHtml);t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document;
 d.getElementById('discardNext').checked=true;d.getElementById('addAction').click();await settle();assert.equal(f.requests.filter(r=>r.args?.kind==='add').length,0);await fillCreation(f);assert.equal(f.requests.filter(r=>r.name==='apply_change'&&r.args.kind==='add').length,1);assert.equal(d.getElementById('discardNext').checked,false);assert.match(d.getElementById('status').textContent,/discarded/);
 for(const fn of [...f.timers.values()])fn();await settle();assert.equal(d.getElementById('unknown').hidden,false);assert.equal(d.querySelector('section input').disabled,false);const first=f.requests.find(r=>r.name==='apply_change'&&r.args.kind==='add');d.getElementById('retry').click();await settle();assert.deepEqual(f.requests.filter(r=>r.name==='apply_change'&&r.args.kind==='add').at(-1).args,first.args);assert.equal(d.getElementById('unknown').hidden,true);
});
test('Inbox includes deferred unassigned actions and excludes assigned or ended records',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document;
 const deferred={...f.action,id:'deferred',title:'後で整理',view:'deferred',notes:'原文の気がかり'};
 f.state.actions.push(deferred,{...f.action,id:'assigned',title:'所属済み',project_id:'project'},{...f.action,id:'completed',title:'完了済み',status:'completed',view:'completed'});
 f.state.list_scopes.inbox.push(deferred.id);d.getElementById('refresh').click();await settle();
 d.querySelector('[data-view="inbox"]').click();assert.deepEqual([...d.querySelectorAll('.action-select span')].map(x=>x.textContent),['保存済み','後で整理']);
 assert.equal(d.querySelector('input[aria-label="他者待ちの理由"]'),null);assert.equal([...d.querySelectorAll('button')].some(b=>b.textContent==='待機を保存'),false);assert.equal(d.getElementById('captures'),null);
 d.querySelector('[data-action-id="deferred"] .action-select').click();assert.equal(d.getElementById('editNotes').value,'原文の気がかり');
});
test('Add starts locally and notes-only content waits for Title then creates with exact original notes',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;assert.equal(d.getElementById('capture'),null);assert.equal(d.getElementById('captureTitle'),null);assert.equal(d.getElementById('title'),null);d.getElementById('addAction').click();await settle();assert.equal(f.requests.some(r=>r.args?.kind==='add'),false);assert.equal(d.activeElement,d.getElementById('editTitle'));assert.equal(d.getElementById('editTitle').value,'');assert.equal(d.querySelector('.action-select[aria-pressed="true"]').textContent,'Untitled');d.getElementById('editNotes').value='  いつか検討するかもしれない\n<script>exact</script>  ';d.getElementById('editNotes').dispatchEvent(new w.Event('input',{bubbles:true}));d.getElementById('editTitle').dispatchEvent(new w.Event('blur'));await settle();assert.equal(f.requests.some(r=>r.args?.kind==='add'),false);d.getElementById('editTitle').value='Required title';d.getElementById('editTitle').dispatchEvent(new w.Event('input',{bubbles:true}));d.getElementById('editTitle').dispatchEvent(new w.Event('blur'));await settle();const added=f.state.actions.find(a=>a.id==='f25a36bb-3eef-4c21-b3ee-0cc45cb596ab');assert.equal(added.notes,'  いつか検討するかもしれない\n<script>exact</script>  ');assert.equal(added.title,'Required title');assert.equal(f.requests.some(r=>r.name==='capture_intent'||r.name==='add_action'),false);
});
test('complete raw editor survives scope removal, refresh, context and IME without node replacement',async t=>{
 const f=createFixture(widgetHtml,{initialize:{hostContext:{displayMode:'inline',availableDisplayModes:['inline','fullscreen'],theme:'light'}}});t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window;
 const fields={editTitle:'raw title',editNotes:'raw notes <script>exact</script>',editDue:'2026-10-10',dueTime:'12:00',deferDate:'2026-10-11',deferUntil:'09:00'};
 for(const [id,value] of Object.entries(fields)){const input=d.getElementById(id);input.value=value;input.dispatchEvent(new w.Event('input',{bubbles:true}));}
 f.state.actions.push({...f.action,id:'parent',title:'親'});d.getElementById('refresh').click();await settle();d.querySelector('[data-status="on-hold"]').click();
 assert.equal(d.getElementById('deferDetails').tagName,'SECTION');const notes=d.getElementById('editNotes');notes.focus();notes.setSelectionRange(2,7,'backward');notes.dispatchEvent(new w.Event('compositionstart',{bubbles:true}));
 f.action.title='latest';f.action.notes='saved change';f.state.revision++;w.dispatchEvent(new w.MessageEvent('message',{source:w,data:{jsonrpc:'2.0',method:'ui/notifications/tool-result',params:{structuredContent:structuredClone(f.state)}}}));w.dispatchEvent(new w.MessageEvent('message',{source:w,data:{jsonrpc:'2.0',method:'ui/notifications/host-context-changed',params:{theme:'dark'}}}));
 assert.equal(d.getElementById('editNotes'),notes);assert.equal(d.activeElement,notes);assert.equal(notes.selectionStart,2);assert.equal(notes.selectionEnd,7);assert.equal(notes.selectionDirection,'backward');assert.equal(d.getElementById('deferDetails').querySelector('summary'),null);assert.equal(d.documentElement.style.colorScheme,'dark');
 for(const [id,value] of Object.entries(fields))assert.equal(d.getElementById(id).value,value);assert.equal(d.querySelector('[data-status="on-hold"]').getAttribute('aria-pressed'),'true');notes.dispatchEvent(new w.Event('compositionend',{bubbles:true}));
 d.querySelector('[data-view="history"]').click();assert.equal(d.getElementById('retained').hidden,false);assert.equal(d.getElementById('editor').hidden,false);assert.equal(d.getElementById('scopeTitle').textContent,'History');assert.equal(d.getElementById('scopeCount').textContent,'0');d.getElementById('retained').querySelector('button').click();assert.equal(d.activeElement,d.getElementById('editTitle'));
 f.state.actions=[];d.getElementById('refresh').click();await settle();assert.equal(d.getElementById('editNotes').value,fields.editNotes);assert.equal(d.getElementById('targetMissing').hidden,false);assert.equal(d.getElementById('deferDate').disabled,true);assert.equal(d.getElementById('retained').hidden,false);
});
test('narrow scope selector exposes every scope and selected editor receives focus; labels remain escaped',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;let scrolled=false;w.matchMedia=()=>({matches:true});d.getElementById('editor').scrollIntoView=()=>{scrolled=true;};f.action.title='<img src=x onerror=alert(1)>';d.getElementById('refresh').click();await settle();
 assert.deepEqual([...d.querySelectorAll('#navigationMenu [data-view]')].map(o=>o.dataset.view),['inbox','projects','tags','flagged','history']);assert.equal(d.querySelector('.action-select span').textContent,f.action.title);assert.equal(d.querySelector('#actions img'),null);selectFirst(f);assert.equal(d.activeElement,d.getElementById('editTitle'));assert.equal(scrolled,true);assert.equal(d.querySelector('#actions svg').getAttribute('aria-hidden'),'true');assert.equal(d.getElementById('displayToggle').hidden,true);
});
test('saved dropped parent survives unrelated title save without detach or reorder',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;
 f.action.parent_id='parent';f.action.order=9;f.state.actions.push({...f.action,id:'parent',title:'取り下げた親',parent_id:null,status:'dropped',view:'cancelled'});d.getElementById('refresh').click();await settle();selectFirst(f);assert.equal(d.getElementById('editParent'),null);assert.equal(d.getElementById('editOrder'),null);d.getElementById('editTitle').value='new title';d.getElementById('editTitle').dispatchEvent(new w.Event('input',{bubbles:true}));d.getElementById('editTitle').dispatchEvent(new w.Event('blur'));await settle();assert.deepEqual(f.requests.filter(r=>r.name==='preview_change').at(-1).args.payload,{id:f.action.id,title:'new title'});assert.equal(f.action.parent_id,'parent');assert.equal(f.action.order,9);
});
test('unchanged list rows and focusable controls keep their DOM identity through a saving-only Notes update',async t=>{const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document;selectFirst(f);const row=d.querySelector('.action-row'),controls=[...row.querySelectorAll('button')];d.getElementById('editNotes').value='exact notes only';d.getElementById('editNotes').dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));d.getElementById('editNotes').dispatchEvent(new f.dom.window.Event('blur'));await settle();assert.equal(d.querySelector('.action-row'),row);assert.deepEqual([...row.querySelectorAll('button')],controls);assert.equal(f.state.actions[0].notes,'exact notes only');});
test('control rendering avoids same-value disabled writes and preserves busy and completed states',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window,complete=d.querySelector('.complete'),records=[],observer=new w.MutationObserver(changes=>records.push(...changes));assert.equal(complete.disabled,false,'an active action starts enabled');observer.observe(d.getElementById('actions'),{subtree:true,attributes:true,attributeFilter:['disabled']});
 f.setLost(true);complete.click();await settle();assert.equal(complete.disabled,true);assert.equal(records.filter(record=>record.target.classList.contains('complete')).length,1,`a real busy transition should write disabled once; disabled=${complete.disabled}; connected=${complete.isConnected}; records=${records.map(record=>record.target.className+':'+record.attributeName+':'+record.target.disabled+':'+record.target.isConnected)}; request=${f.requests.map(request=>request.name+':'+(request.args?.kind||''))}`);
 records.length=0;w.dispatchEvent(new w.MessageEvent('message',{source:w,data:{jsonrpc:'2.0',method:'ui/notifications/tool-result',params:{structuredContent:structuredClone(f.state)}}}));await settle();assert.equal(records.length,0,'an unchanged busy render must not rewrite disabled');observer.disconnect();
 const completed=createFixture();t.after(()=>completed.dom.window.close());await settle();const cd=completed.dom.window.document;completed.action.status='completed';cd.querySelector('[data-view="history"]').click();cd.getElementById('refresh').click();await settle();const completedControl=cd.querySelector('.complete');assert.equal(completedControl.getAttribute('aria-checked'),'true');assert.equal(completedControl.disabled,true,'a completed action remains disabled after renderControls');
});
test('same-target pointer movement does not rewrite aria-live destination text but a changed target does',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;for(const [id,title] of [['destination-a','Destination A'],['destination-b','Destination B']]){f.state.actions.push({...f.action,id,title,order:f.state.actions.length});f.state.list_scopes.inbox.push(id);}d.getElementById('refresh').click();await settle();
 const rows=[...d.querySelectorAll('.action-row')],source=rows[0],first=rows[1],second=rows[2],status=d.getElementById('moveStatus');d.querySelector('.list-panel').getBoundingClientRect=()=>({left:0,right:300});d.getElementById('actions').getBoundingClientRect=()=>({left:0,right:300});rows.forEach((row,index)=>{const top=index*60;row.getBoundingClientRect=()=>({left:0,right:300,top,bottom:top+60,height:60});row.querySelector('.action-select').getBoundingClientRect=()=>({left:20,right:280,top:top+10,bottom:top+40,height:30});});d.elementFromPoint=(x,y)=>y<60?source.querySelector('.action-select'):y<120?first.querySelector('.action-select'):second.querySelector('.action-select');
 const statusMutations=[],observer=new w.MutationObserver(changes=>statusMutations.push(...changes));observer.observe(status,{childList:true});const pointer=(target,type,x,y)=>{const event=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperties(event,{pointerId:{value:9},pointerType:{value:'mouse'},button:{value:0},clientX:{value:x},clientY:{value:y}});target.dispatchEvent(event);};pointer(source,'pointerdown',20,30);pointer(w,'pointermove',120,90);f.flushFrames();await settle();const firstStatus=status.textContent;assert.match(firstStatus,/Destination A/,`target status should reflect the first action destination; status=${firstStatus}; drops=${[...d.querySelectorAll('[data-drop-class]')].map(row=>row.dataset.actionId+':'+row.dataset.dropClass)}; frames=${f.frameCount()}; rows=${rows.map(r=>r.dataset.actionId+':'+r.getBoundingClientRect().top+'-'+r.getBoundingClientRect().bottom)}; select=${d.querySelector('.batch-selected')?.dataset.actionId}; active=${d.getElementById('selectionBar').hidden}`);assert(statusMutations.length>0,'initial target should announce its status');statusMutations.length=0;
 pointer(w,'pointermove',122,95);f.flushFrames();await settle();assert.equal(status.textContent,firstStatus);assert.equal(statusMutations.length,0,'same-target movement must not replace aria-live text');
 pointer(w,'pointermove',120,150);f.flushFrames();await settle();assert.match(status.textContent,/Destination B/);assert.notEqual(status.textContent,firstStatus);assert(statusMutations.length>0,'a semantic target change should update the status');observer.disconnect();
});
test('English UI keeps exact user text and maps server errors without leaking raw copy',async(t)=>{
 const f=createFixture(widgetHtml,{previewError:{code:'revision_conflict',message:'別画面で更新されました。秘密の内部文言'}});t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;selectFirst(f);d.getElementById('editTitle').value='保存する原文';d.getElementById('editTitle').dispatchEvent(new w.Event('input',{bubbles:true}));d.getElementById('editTitle').dispatchEvent(new w.Event('blur'));await settle();
 assert.equal(d.documentElement.lang,'en');assert.equal(d.getElementById('saveProblem').hidden,false);assert(!d.getElementById('status').textContent.includes('秘密'));assert.equal(d.getElementById('editTitle').value,'保存する原文');assert.equal(d.getElementById('review'),null);assert.equal(f.requests.some(r=>r.name==='apply_change'),false);
});
test('completion affordance is unchecked until completed and closing details returns focus while retaining draft',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;assert.equal(d.querySelector('.complete').getAttribute('aria-checked'),'false');assert.equal(d.querySelector('.workspace').classList.contains('has-editor'),false);selectFirst(f);d.getElementById('editNotes').value='exact raw メモ';d.getElementById('editNotes').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.querySelector('.workspace').classList.contains('has-editor'),true);d.getElementById('backToList').click();assert.equal(d.querySelector('.workspace').classList.contains('has-editor'),false);assert.equal(d.activeElement,d.querySelector('.action-select'));d.querySelector('.action-select').click();assert.equal(d.getElementById('editNotes').value,'exact raw メモ');f.action.status='completed';d.querySelector('[data-view="history"]').click();d.getElementById('refresh').click();await settle();assert.equal(d.querySelector('.complete').getAttribute('aria-checked'),'true');
});

test('classification and saved perspective browsing preserves proposals and exact names without partial snapshot calls',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;
 f.action.project_id='p';f.action.project_path='Work';f.action.tags=[{order:0,id:'tag',name:'Focus',path:'Focus'}];f.action.is_deferred=false;f.action.status='on-hold';f.action.flagged=true;f.state.projects=[{order:0,id:'p',name:'Work',path:'Work',parent_id:null,description:'  exact\nProject context  '}];f.state.tags=[{order:0,id:'tag',name:'Focus',path:'Focus',parent_id:null}];f.state.perspectives=[{order:0,id:'all',name:'Everything <img>',description:'  saved 原文\n<script> context  ',filter:{}},{order:0,id:'none',name:'No matches',description:'',filter:{statuses:[]}}];f.state.list_scopes.inbox=[];d.getElementById('refresh').click();await settle();
 assert.deepEqual([...d.querySelectorAll('[data-view]')].map(b=>b.dataset.view),['inbox','projects','tags','flagged','history']);d.querySelector('[data-view="projects"]').click();d.querySelector('[data-catalog-id="p"] .catalog-select').click();assert.equal(d.getElementById('scopeTitle').textContent,'Projects');assert.equal(d.getElementById('catalogEditDescription').value,'  exact\nProject context  ');assert.equal(d.getElementById('classificationPicker'),null);assert(d.querySelector('.badge.on-hold svg'));assert.match(d.querySelector('.badge.on-hold').textContent,/On hold/);selectFirst(f);
 d.getElementById('editNotes').value='  raw 未保存\n';d.getElementById('editNotes').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.getElementById('actionClassification'),null);d.querySelector('[data-view="tags"]').click();assert.equal(d.querySelectorAll('.action-row').length,1);d.querySelector('[data-focus-key="perspective:none"]').click();assert.equal(d.querySelectorAll('.action-row').length,0);assert.equal(d.getElementById('targetMissing').hidden,true);assert.equal(d.getElementById('editNotes').value,'  raw 未保存\n');assert.equal(d.getElementById('retained').hidden,false);assert.equal(d.getElementById('scopeSummary').hidden,true);
 d.querySelector('[data-focus-key="perspective:all"]').click();assert.equal(d.getElementById('scopeTitle').textContent,'Everything <img>');assert.equal(d.getElementById('scopeDescription').textContent,'  saved 原文\n<script> context  ');assert.equal(d.querySelector('#scopeTitle img'),null);assert.equal(f.requests.some(r=>r.name==='query_perspective'||r.name==='query_actions'),false);
});
test('unknown save permits navigation and Back while retaining the exact recovery request',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;selectFirst(f);d.getElementById('editNotes').value='retained proposal';d.getElementById('editNotes').dispatchEvent(new w.Event('input',{bubbles:true}));f.setLost(true);d.getElementById('editNotes').dispatchEvent(new w.Event('blur'));await settle();for(const fn of [...f.timers.values()])fn();await settle();const request=f.requests.filter(r=>r.name==='apply_change'&&r.args.kind==='edit').at(-1);assert.equal(d.getElementById('backToList').disabled,false);assert.equal(d.getElementById('closeEditor').disabled,false);d.querySelector('[data-view="history"]').click();assert.equal(d.getElementById('scopeTitle').textContent,'History');assert.equal(d.getElementById('editNotes').value,'retained proposal');d.getElementById('backToList').click();assert.equal(d.getElementById('editor').hidden,true);assert.equal(d.getElementById('retained').hidden,false);d.getElementById('retained').querySelector('button').click();assert.equal(d.getElementById('editNotes').value,'retained proposal');f.setLost(false);d.getElementById('retry').click();await settle();assert.deepEqual(f.requests.filter(r=>r.name==='apply_change'&&r.args.kind==='edit').at(-1).args,request.args);assert.equal(d.getElementById('editNotes').value,'retained proposal');
});
test('deleted selected catalog keeps its inspector unavailable without broadening Add context',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.state.projects=[{order:0,id:'p',name:'Work',description:'saved',parent_id:null}];f.action.project_id='p';f.action.is_deferred=false;d.getElementById('refresh').click();await settle();d.querySelector('[data-view="projects"]').click();d.querySelector('[data-catalog-id="p"] .catalog-select').click();const input=d.getElementById('catalogEditDescription');input.value='unsaved exact';input.dispatchEvent(new w.Event('input',{bubbles:true}));f.state.projects=[];f.state.revision++;w.dispatchEvent(new w.MessageEvent('message',{source:w,data:{jsonrpc:'2.0',method:'ui/notifications/tool-result',params:{structuredContent:structuredClone(f.state)}}}));assert.equal(d.getElementById('catalogEditor').hidden,false);assert.equal(d.getElementById('catalogMissing').hidden,false);assert.equal(input.value,'unsaved exact');assert.equal(input.disabled,true);assert.equal(d.getElementById('addAction').disabled,false);
});
test('returning to tree views retains action drafts and Defer settings without a classification dropdown',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.action.project_id='p';f.action.is_deferred=false;f.state.projects=[{order:0,id:'p',name:'Work',parent_id:null}];f.state.perspectives=[{order:0,id:'saved',name:'Exact view',filter:{statuses:[]}}];d.getElementById('refresh').click();await settle();d.querySelector('[data-view="projects"]').click();d.querySelector('[data-catalog-id="p"] .catalog-select').click();d.querySelector('[data-display-choice="deferred"]').click();selectFirst(f);d.getElementById('editNotes').value='retained raw';d.getElementById('editNotes').dispatchEvent(new w.Event('input',{bubbles:true}));d.querySelector('[data-view="inbox"]').click();d.querySelector('[data-view="projects"]').click();assert.equal(d.getElementById('classificationPicker'),null);assert.equal(d.querySelector('[data-display-choice="deferred"]').getAttribute('aria-checked'),'true');assert.equal(d.getElementById('editNotes').value,'retained raw');d.querySelector('[data-focus-key="perspective:saved"]').click();assert.equal(d.getElementById('scopeTitle').textContent,'Exact view');assert.equal(d.getElementById('editNotes').value,'retained raw');
});
test('minimal editor has no review or save controls; debounce/blur saves exact Notes and direct row controls persist',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window;assert.equal(d.querySelector('dialog'),null);assert.equal(d.getElementById('saveEdit'),null);assert.equal(d.getElementById('creationHint'),null);const notes=d.getElementById('editNotes');notes.value='  exact 日本語 <script>text</script>  ';notes.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(f.requests.some(r=>r.name==='apply_change'),false);notes.dispatchEvent(new w.Event('blur'));await settle();assert.equal(f.action.notes,notes.value);assert.equal(d.getElementById('status').textContent,'');assert.equal(d.getElementById('refresh').dataset.state,'saved');d.querySelector('.flag').click();await settle();assert.equal(f.action.flagged,true);d.querySelector('.complete').click();await settle();assert.equal(f.action.status,'completed');assert.equal(d.querySelector('dialog'),null);
});
test('autosave retains invalid raw input without retry and IME only sends final text through original target',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window;const due=d.getElementById('editDue');due.value='2026-11-01T01:30:00';Object.defineProperty(due.validity,'badInput',{value:true,configurable:true});due.dispatchEvent(new w.Event('input',{bubbles:true}));due.dispatchEvent(new w.Event('blur'));await settle();assert.equal(f.requests.some(r=>r.name==='apply_change'),false);assert.match(d.getElementById('dueError').textContent,/Finish choosing/);assert.equal(d.getElementById('saveProblem').hidden,true);Object.defineProperty(due.validity,'badInput',{value:false,configurable:true});due.value='2026-10-10T12:00:00';due.dispatchEvent(new w.Event('input',{bubbles:true}));due.dispatchEvent(new w.Event('blur'));await settle();const notes=d.getElementById('editNotes');notes.dispatchEvent(new w.Event('compositionstart'));notes.value='途中';notes.dispatchEvent(new w.Event('input',{bubbles:true}));notes.dispatchEvent(new w.Event('blur'));d.querySelector('[data-view="history"]').click();await settle();assert.equal(f.action.notes,'');notes.value='日本語完成';notes.dispatchEvent(new w.Event('compositionend'));for(const fn of [...f.timers.values()])fn();await settle();assert.equal(f.action.notes,'日本語完成');assert.equal(d.getElementById('editNotes'),notes);
});
test('external touched-field conflict pauses only target and uses explicit inline reconciliation',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window;const title=d.getElementById('editTitle');title.value='my title';title.dispatchEvent(new w.Event('input',{bubbles:true}));f.action.title='caller title';f.action.revision++;f.state.revision++;d.getElementById('refresh').click();await settle();title.dispatchEvent(new w.Event('blur'));await settle();assert.equal(f.requests.some(r=>r.name==='apply_change'),false);assert.equal(title.value,'my title');assert.equal(d.getElementById('useMine').hidden,false);d.getElementById('useMine').click();await settle();assert.equal(f.action.title,'my title');assert.equal(d.getElementById('saveProblem').hidden,true);
});
test('IME action switch defers shared inspector rebinding until original final value is captured',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.state.actions.push({...f.action,id:'second',title:'Second title',notes:'Second notes'});f.state.list_scopes.inbox.push('second');d.getElementById('refresh').click();await settle();selectFirst(f);const input=d.getElementById('editTitle');input.focus();input.dispatchEvent(new w.Event('compositionstart'));input.value='途中';input.dispatchEvent(new w.Event('input'));const second=d.querySelector('[data-action-id="second"] .action-select');second.focus();second.click();d.getElementById('refresh').click();await settle();assert.equal(input.value,'途中');input.value='元の完成';input.dispatchEvent(new w.Event('compositionend'));await settle();assert.equal(f.action.title,'元の完成');assert.equal(f.state.actions.find(a=>a.id==='second').title,'Second title');assert.equal(input.value,'Second title');assert.equal(d.querySelector('.action-select[aria-pressed="true"]').closest('.action-row').dataset.actionId,'second');
});
test('Move chooser Escape and Cancel restore the initiating grip after rows rerender',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document;
 for(const close of ['Escape','Cancel']){const grip=d.querySelector('.drag-handle');grip.focus();grip.dispatchEvent(new f.dom.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(d.getElementById('moveChooser').hidden,false);assert.equal(d.activeElement,d.getElementById('movePlacement'));if(close==='Escape')d.dispatchEvent(new f.dom.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));else d.getElementById('cancelMove').click();assert.equal(d.getElementById('moveChooser').hidden,true);assert.equal(d.activeElement.dataset.focusKey,'grip:'+f.action.id);}
});
test('real pointer activation selects only a contiguous Shift range and Ctrl replaces it without checkboxes',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;for(const [id,title] of [['two','Two'],['three','Three'],['four','Four']]){f.state.actions.push({...f.action,id,title,order:f.state.actions.length});f.state.list_scopes.inbox.push(id);}d.getElementById('refresh').click();await settle();const click=(id,shift=false,ctrl=false)=>{const title=d.querySelector('[data-action-id="'+id+'"] .action-select');title.dispatchEvent(new w.MouseEvent('pointerdown',{bubbles:true,button:0,clientX:20,clientY:20}));w.dispatchEvent(new w.MouseEvent('pointerup',{bubbles:true,button:0,clientX:20,clientY:20}));title.dispatchEvent(new w.MouseEvent('click',{bubbles:true,shiftKey:shift,ctrlKey:ctrl}));};click(f.action.id);click('three',true);assert.equal(d.querySelectorAll('.batch-selected').length,3);click('two',true);assert.equal(d.querySelectorAll('.batch-selected').length,2);click('four',false,true);assert.equal(d.querySelectorAll('.batch-selected').length,1);assert.equal(d.querySelector('.batch-selected').dataset.actionId,'four');assert.equal(d.querySelector('.row-selection'),null);assert.equal(d.getElementById('editDue').type,'date');assert.equal(d.getElementById('deferDate').type,'date');});
test('duplicate Tag occurrences select only the clicked interval while sharing one Action editor and exact catalog inspector',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.state.tags=[{order:0,id:'first',name:'Focus',description:' exact first '},{order:0,id:'second',name:'Email',description:' second '}];f.action.tags=[{order:0,id:'first',name:'Focus'},{order:0,id:'second',name:'Email'}];f.action.is_deferred=false;d.getElementById('refresh').click();await settle();d.querySelector('[data-view="tags"]').click();const first='tag:first:action:'+f.action.id,second='tag:second:action:'+f.action.id;d.querySelector('[data-occurrence-key="'+first+'"] .action-select').click();assert.equal(d.querySelectorAll('.action-select[aria-pressed="true"]').length,1);assert.equal(d.querySelectorAll('.batch-selected').length,1);d.querySelector('[data-occurrence-key="'+second+'"] .action-select').dispatchEvent(new w.MouseEvent('click',{bubbles:true,shiftKey:true}));assert.equal(d.querySelectorAll('.batch-selected').length,2);assert.match(d.getElementById('selectionCount').textContent,/2 rows.*1 actions/);const title=d.getElementById('editTitle');title.value='Same record';title.dispatchEvent(new w.Event('input',{bubbles:true}));assert.deepEqual([...d.querySelectorAll('.action-select span')].map(n=>n.textContent),['Same record','Same record']);d.querySelector('[data-catalog-id="second"] .catalog-select').click();assert.equal(d.getElementById('editor').hidden,true);assert.equal(d.getElementById('catalogEditor').hidden,false);assert.equal(d.getElementById('catalogEditName').value,'Email');assert.equal(d.querySelectorAll('.action-select[aria-pressed="true"]').length,0);assert.equal(d.querySelectorAll('.batch-selected').length,0);assert.equal(d.getElementById('classificationPicker'),null);
});
test('catalog IME keeps its original target through refresh and deferred Action selection',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.state.projects=[{order:0,id:'p',name:'Work',description:'saved'}];f.action.project_id='p';f.action.is_deferred=false;d.getElementById('refresh').click();await settle();d.querySelector('[data-view="projects"]').click();d.querySelector('[data-catalog-id="p"] .catalog-select').click();const description=d.getElementById('catalogEditDescription');description.focus();description.dispatchEvent(new w.Event('compositionstart'));description.value='途中';d.querySelector('.action-select').click();d.getElementById('refresh').click();await settle();assert.equal(description.value,'途中');assert.equal(f.requests.some(r=>r.name==='apply_change'&&r.args.kind==='project_edit'),false);description.value=' 完成 日本語 <script>exact</script> ';description.dispatchEvent(new w.Event('compositionend'));await settle();assert.equal(f.state.projects[0].description,' 完成 日本語 <script>exact</script> ');assert.equal(f.action.notes,'');assert.equal(d.getElementById('editor').hidden,false);assert.equal(d.getElementById('catalogEditDescription'),description);
});
test('header split Add consolidates creation and searchable pickers preserve UUID association and chip removal',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.state.projects=[{order:0,id:'p',name:'Work',path:'Work / Website'}];f.state.tags=[{order:0,id:'focus',name:'Focus'},{order:0,id:'email',name:'Email'}];d.getElementById('refresh').click();await settle();assert(d.querySelector('header #addAction'));assert(d.querySelector('header #addMenuToggle'));assert(d.querySelector('header #displayMenuToggle'));assert(d.querySelector('header #displayMenu'));for(const id of ['newCatalog','newProject','newTag','catalogChild','editProject'])assert.equal(d.getElementById(id),null);d.getElementById('addMenuToggle').click();d.getElementById('addMenuTag').click();await settle();assert.equal(d.getElementById('scopeTitle').textContent,'Tags');assert.equal(d.getElementById('catalogComposer').hidden,true);assert.equal(d.getElementById('catalogEditor').hidden,false);d.querySelector('[data-view="inbox"]').click();selectFirst(f);const search=d.getElementById('projectSearch');search.focus();search.value='wbs';search.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.querySelectorAll('#projectOptions [role="option"]').length,1);d.querySelector('#projectOptions [role="option"]').click();await settle();assert.equal(f.action.project_id,'p');d.getElementById('tagPickerToggle').click();const tag=d.getElementById('tagSearch');tag.value='eml';tag.dispatchEvent(new w.Event('input',{bubbles:true}));d.querySelector('#tagOptions [role="option"]').click();await settle();assert.deepEqual(f.action.tags.map(tag=>tag.id),['email']);assert.equal(d.querySelectorAll('#editTags input').length,0);d.querySelector('#editTags button').click();await settle();assert.deepEqual(f.action.tags,[]);tag.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.getElementById('tagPicker').hidden,true);assert.equal(d.activeElement,d.getElementById('tagPickerToggle'));
});
test('pointer cancellation, capture loss, Escape and unmount cancel the single queued drag frame',async t=>{for(const reason of ['pointercancel','lostpointercapture','Escape','pagehide']){const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window,row=d.querySelector('.action-row');const captured=new Set();row.setPointerCapture=id=>captured.add(id);row.hasPointerCapture=id=>captured.has(id);row.releasePointerCapture=id=>captured.delete(id);const pointer=(target,type,x,y)=>{const event=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperties(event,{pointerId:{value:7},pointerType:{value:'mouse'},button:{value:0},clientX:{value:x},clientY:{value:y}});target.dispatchEvent(event);};pointer(row,'pointerdown',20,120);pointer(w,'pointermove',40,130);assert.equal(f.frameCount(),1,reason);if(reason==='Escape')w.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));else if(reason==='pagehide')w.dispatchEvent(new w.Event('pagehide'));else if(reason==='lostpointercapture'){assert(captured.has(7),'pointer gesture should own its captured pointer before the browser reports loss');captured.delete(7);pointer(w,reason,40,130);}else pointer(w,reason,40,130);assert.equal(f.frameCount(),0,reason);f.flushFrames();await settle();assert.equal(f.requests.some(request=>request.name==='apply_change'&&request.args.kind==='action_move'),false,reason);}});
test('edge drops finish once and ineffective auto-scroll leaves no queued frame',async t=>{
 for(const native of [false,true])for(const edge of ['top','bottom'])for(const limit of [0,100]){
  const label=JSON.stringify({native,edge,limit}),f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window,targetId='66666666-6666-4666-8666-666666666666';
  f.state.actions.push({...f.action,id:targetId,title:'Destination',order:1});f.state.list_scopes.inbox.push(targetId);d.getElementById('refresh').click();await settle();
  const source=d.querySelector('.action-row[data-action-id="'+f.action.id+'"]'),target=d.querySelector('.action-row[data-action-id="'+targetId+'"]'),y=edge==='top'?20:748;
  let scroll=limit,scrollCalls=0;Object.defineProperty(w,'scrollY',{get:()=>scroll});w.scrollBy=(_x,delta)=>{scrollCalls++;scroll=Math.max(0,Math.min(100,scroll+delta));};
  d.getElementById('actions').getBoundingClientRect=()=>({left:0,right:300});d.querySelector('.list-panel').getBoundingClientRect=()=>({left:0,right:300});source.getBoundingClientRect=()=>({left:0,right:300,top:y-100,bottom:y-40,height:60});target.getBoundingClientRect=()=>({left:0,right:300,top:y-20,bottom:y+20,height:40});
  const dispatch=(node,type,coordinate)=>{const event=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperties(event,{pointerId:{value:7},pointerType:{value:'mouse'},button:{value:0},clientX:{value:20},clientY:{value:coordinate},dataTransfer:{value:{setData(){},effectAllowed:'',dropEffect:''}}});node.dispatchEvent(event);};
  if(native){dispatch(source,'dragstart',120);dispatch(target,'dragover',y);}else{dispatch(source,'pointerdown',120);dispatch(w,'pointermove',y);}
  assert.equal(f.frameCount(),1,label);f.flushFrames();assert.equal(f.frameCount(),0,label);assert(scrollCalls<=10,label+' bounded scrolling');
  if(native){dispatch(target,'drop',y);dispatch(source,'dragend',y);}else dispatch(w,'pointerup',y);
  assert.equal(f.frameCount(),1,label);f.flushFrames();await settle();assert.equal(f.frameCount(),0,label);
  const moves=f.requests.filter(request=>request.name==='apply_change'&&request.args.kind==='action_move');assert.equal(moves.length,1,label);assert.equal(moves[0].args.payload.anchor_id,targetId,label);assert.equal(moves[0].args.payload.placement,'inside',label);
 }
});
test('native mouse drag survives pointercancel and pointer capture loss, then emits one shared movement operation',async(t)=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;const targetId='66666666-6666-4666-8666-666666666666';f.state.actions.push({...f.action,id:targetId,title:'Destination',order:1});f.state.list_scopes.inbox.push(targetId);d.getElementById('refresh').click();await settle();const source=d.querySelector('[data-action-id="'+f.action.id+'"]'),target=d.querySelector('[data-action-id="'+targetId+'"]');assert.equal(source.draggable,true);const captured=new Set();source.setPointerCapture=id=>captured.add(id);source.hasPointerCapture=id=>captured.has(id);source.releasePointerCapture=id=>captured.delete(id);d.querySelector('.list-panel').getBoundingClientRect=()=>({left:0,right:300});d.getElementById('actions').getBoundingClientRect=()=>({left:0,right:300});target.getBoundingClientRect=()=>({left:0,top:100,bottom:160,height:60});d.elementFromPoint=()=>target.querySelector('.action-select');const event=type=>{const e=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperties(e,{pointerId:{value:8},pointerType:{value:'mouse'},button:{value:0},clientX:{value:20},clientY:{value:120},dataTransfer:{value:{setData(){},effectAllowed:'',dropEffect:''}}});return e;};assert.equal(d.getElementById('selectionBar').hidden,true);source.dispatchEvent(event('pointerdown'));assert(captured.has(8),'native transition should begin with a captured pointer gesture');source.dispatchEvent(event('dragstart'));assert.equal(d.getElementById('selectionBar').hidden,true);w.dispatchEvent(event('pointercancel'));assert(captured.has(8),'native pointercancel must not release the active pointer gesture');captured.delete(8);w.dispatchEvent(event('lostpointercapture'));for(let i=0;i<5;i++)target.dispatchEvent(event('dragover'));assert.equal(f.frameCount(),1);target.dispatchEvent(event('drop'));assert.equal(f.frameCount(),1);source.dispatchEvent(event('dragend'));f.flushFrames();await settle();const moves=f.requests.filter(r=>r.name==='apply_change'&&r.args.kind==='action_move');assert.equal(moves.length,1);assert.equal(moves[0].args.payload.placement,'inside');assert.equal(moves[0].args.payload.anchor_id,targetId);
});
test('tree catalog movement is keyboard reachable without a separate root drop region or Action selection',async(t)=>{const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.state.projects=[{id:'p',name:'Work',order:0,parent_id:null},{id:'q',name:'Website',order:0,parent_id:'p'}];d.getElementById('refresh').click();await settle();d.querySelector('[data-view="projects"]').click();assert.equal(d.getElementById('rootDrop'),null);const source=d.querySelector('[data-catalog-id="q"] .catalog-select');assert.equal(source.closest('.catalog-row').draggable,true);source.focus();source.dispatchEvent(new w.KeyboardEvent('keydown',{key:' ',bubbles:true}));assert.equal(d.getElementById('moveChooser').hidden,false);assert.equal(d.getElementById('moveDestination').options.length,2);assert.equal(d.getElementById('selectionBar').hidden,true);d.getElementById('movePlacement').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.getElementById('moveChooser').hidden,true);assert.equal(d.activeElement.dataset.focusKey,'project:q');});
test('native root outdent uses geometric list gutter even when DOM hit is padding and rejects nav/editor or outside bands',async(t)=>{for(const region of ['gutter','gutter-center','nav','editor','below','outside']){const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window,parent='66666666-6666-4666-8666-666666666666';f.state.actions.unshift({...f.action,id:parent,title:'Parent',order:0});f.action.parent_id=parent;f.action.order=1;f.state.list_scopes.inbox.unshift(parent);d.getElementById('refresh').click();await settle();const rows=[...d.querySelectorAll('.action-row')],source=rows.at(-1),panel=d.querySelector('.list-panel');panel.getBoundingClientRect=()=>({left:56,right:500});d.getElementById('actions').getBoundingClientRect=()=>({left:100,right:500});rows.forEach((r,i)=>r.getBoundingClientRect=()=>({left:100,top:100+i*50,bottom:150+i*50,height:50}));d.elementFromPoint=()=>region==='nav'?d.getElementById('navigationMenu'):region==='editor'?d.querySelector('.editor-panel'):panel;const x=region==='outside'?55:70,y=region==='below'?209:region==='gutter-center'?175:208;const event=type=>{const e=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperties(e,{clientX:{value:type==='dragstart'?180:x},clientY:{value:type==='dragstart'?175:y},dataTransfer:{value:{setData(){},effectAllowed:'',dropEffect:''}}});return e;};source.dispatchEvent(event('dragstart'));d.dispatchEvent(event('dragover'));d.dispatchEvent(event('drop'));source.dispatchEvent(event('dragend'));f.flushFrames();await settle();const moves=f.requests.filter(r=>r.name==='apply_change'&&r.args.kind==='action_move');assert.equal(moves.length,region.startsWith('gutter')?1:0,region);if(moves.length)assert.deepEqual(moves[0].args.payload,{ids:[f.action.id],placement:'root'});}});
test('floating function and display menus expose exact selected states, restore focus and exit without a duplicate sidebar',async(t)=>{const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.state.perspectives=[{order:0,id:'saved',name:'Focus <raw> 日本語',description:'exact raw',filter:{statuses:[]}}];d.getElementById('refresh').click();await settle();assert.equal(d.querySelector('nav'),null);assert.equal(d.getElementById('scopePicker'),null);assert.equal(d.getElementById('refresh').getAttribute('aria-label'),'Refresh');assert.equal(d.getElementById('refresh').getAttribute('aria-label'),'Refresh');const toggle=d.getElementById('navigationToggle');toggle.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.equal(d.activeElement.dataset.view,'inbox');d.activeElement.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.equal(d.activeElement.dataset.view,'projects');d.activeElement.click();assert.equal(d.getElementById('scopeTitle').textContent,'Projects');assert.equal(d.activeElement,toggle);assert.equal(d.getElementById('navigationMenu').hidden,true);const display=d.getElementById('displayMenuToggle');display.click();assert.equal(d.activeElement.dataset.displayChoice,'active');d.querySelector('[data-display-choice="deferred"]').click();assert.equal(d.querySelector('[data-display-choice="deferred"]').getAttribute('aria-checked'),'true');assert.equal(d.getElementById('displayMenu').hidden,false);d.getElementById('displayMenu').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.activeElement,display);toggle.click();d.querySelector('[data-focus-key="perspective:saved"]').click();assert.equal(d.getElementById('scopeTitle').textContent,'Focus <raw> 日本語');assert.equal(d.querySelector('#scopeTitle raw'),null);toggle.click();d.activeElement.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Tab',bubbles:true}));assert.equal(d.getElementById('navigationMenu').hidden,true);toggle.click();d.querySelector('.list-panel').dispatchEvent(new w.Event('pointerdown',{bubbles:true}));assert.equal(d.getElementById('navigationMenu').hidden,true);toggle.click();d.activeElement.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.activeElement,toggle);f.state.perspectives=[];d.getElementById('refresh').click();await settle();assert.equal(d.getElementById('scopeCount').textContent,'0');toggle.click();assert.equal(d.activeElement.dataset.view,'inbox');assert.equal(d.querySelector('#perspectiveButtons [aria-checked="true"]').disabled,true);});
test('header blank creation defers original IME and later explicit navigation cancels it',async(t)=>{for(const later of [false,true]){const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window,node=d.getElementById('editNotes');node.dispatchEvent(new w.Event('compositionstart'));node.value='途中';d.getElementById('addMenuToggle').click();d.getElementById('addMenuProject').click();assert.equal(f.requests.some(r=>r.args?.kind==='project_add'),false);if(later)d.querySelector('[data-view="tags"]').click();node.value=' exact 完成 日本語 ';node.dispatchEvent(new w.Event('compositionend'));for(const [id,fn] of [...f.timers]){f.timers.delete(id);fn();}await settle();assert.equal(f.action.notes,' exact 完成 日本語 ');assert.equal(f.requests.some(r=>r.args?.kind==='project_add'),false);assert.equal(d.getElementById('scopeTitle').textContent,later?'Tags':'Projects');if(!later){assert.equal(d.activeElement,d.getElementById('catalogEditName'));assert.equal(d.getElementById('catalogEditName').value,'');}}});
test('unknown header blank catalog retries exact request without pulling newer navigation back',async(t)=>{for(const kind of ['project','tag']){const f=createFixture(verificationWidgetHtml);t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document;d.getElementById('discardNext').checked=true;d.getElementById('addMenuToggle').click();d.getElementById(kind==='project'?'addMenuProject':'addMenuTag').click();await settle();await fillCreation(f,'catalogEditName','Created '+kind);for(const fn of [...f.timers.values()])fn();await settle();assert.equal(d.getElementById('unknown').hidden,false);const original=f.requests.find(r=>r.args?.kind===kind+'_add').args;assert.equal(original.payload.name,'Created '+kind);d.querySelector('[data-view="history"]').click();d.getElementById('retry').click();await settle();assert.deepEqual(f.requests.filter(r=>r.args?.kind===kind+'_add').map(r=>r.args),[original,original]);assert.equal(d.getElementById('scopeTitle').textContent,'History');assert.equal(d.getElementById('catalogComposer').hidden,true);assert.equal(d.getElementById('unknown').hidden,true);}});
test('display checkboxes toggle multiple choices in place without writes, instructions or combination labels',async(t)=>{const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;d.querySelector('[data-view="projects"]').click();const before=f.requests.filter(r=>r.name==='apply_change').length;d.getElementById('displayMenuToggle').click();const active=d.querySelector('[data-display-choice="active"]');assert.equal(active.getAttribute('role'),'menuitemcheckbox');assert.equal(active.getAttribute('aria-checked'),'true');active.dispatchEvent(new w.KeyboardEvent('keydown',{key:' ',bubbles:true}));assert.equal(active.getAttribute('aria-checked'),'false');assert.equal(d.getElementById('displayMenu').hidden,false);assert.equal(d.activeElement,active);const done=d.querySelector('[data-display-choice="completed"]');done.focus();done.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(done.getAttribute('aria-checked'),'true');assert.equal(d.getElementById('displayMenu').hidden,false);assert.equal(d.activeElement,done);assert.equal(f.requests.filter(r=>r.name==='apply_change').length,before);assert.equal(d.getElementById('creationHint'),null);assert.equal(d.getElementById('addAction').hasAttribute('aria-describedby'),false);assert.equal(d.getElementById('scopeSummary').hidden,true);assert.doesNotMatch(d.getElementById('displayMenu').textContent,/Not deferred|Any Defer|Completed \+ Dropped/);});
test('Action detail controls stay visible, Flag is independent icon-only and unified Defer preserves partial raw intent',async(t)=>{const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window;assert.equal(d.querySelector('#editor details'),null);for(const id of ['classificationDetails','organizeDetails','deferDetails'])assert.equal(d.getElementById(id).tagName,'SECTION');assert.equal(d.getElementById('actionClassification'),null);assert.equal(d.getElementById('dateTimezone'),null);assert.equal(d.getElementById('saveState'),null);assert.equal(d.getElementById('catalogSaveState'),null);const flag=d.getElementById('editFlag');assert.equal(flag.previousElementSibling.id,'statusIcons');assert.equal(d.querySelectorAll('#statusIcons button').length,4);assert.equal(d.querySelector('#statusIcons #editFlag'),null);assert.equal(flag.parentElement.className,'action-state-controls');assert.equal(flag.tagName,'BUTTON');assert.equal(flag.textContent,'');flag.click();await settle();assert.equal(flag.getAttribute('aria-pressed'),'true');assert.equal(f.requests.filter(r=>r.name==='apply_change'&&r.args?.kind==='edit').length,1);const date=d.getElementById('deferDate'),time=d.getElementById('deferUntil');assert.equal(time.type,'text');assert.equal(time.parentElement.querySelector('.clock-tail').textContent,'--:--:--');time.value='1';time.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(time.parentElement.querySelector('.clock-tail').textContent,'-:--:--');d.getElementById('refresh').click();await settle();assert.equal(time.value,'1');date.value='';date.dispatchEvent(new w.Event('input',{bubbles:true}));date.value='2026-10-04';date.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(time.value,'09:00');time.value='12:34:56.123';time.dispatchEvent(new w.Event('input',{bubbles:true}));date.value='2026-10-05';date.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(time.value,'12:34:56.123');time.value='';time.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.getElementById('refresh').dataset.state,'error');d.getElementById('refresh').click();await settle();assert.equal(time.value,'');assert.equal(d.getElementById('refresh').dataset.state,'error');date.value='';date.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.getElementById('refresh').dataset.state,'pending');date.dispatchEvent(new w.Event('blur'));await settle();assert.equal(d.getElementById('refresh').dataset.state,'saved');});
test('all-view Add reveals ordinary active actions without altering display choices and never reuses an off-view selection',async(t)=>{for(const view of ['inbox','projects','tags','flagged','history','perspective']){const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document;selectFirst(f);if(view==='perspective'){f.state.perspectives=[{order:0,id:'none',name:'None',filter:{statuses:[]}}];d.getElementById('refresh').click();await settle();d.querySelector('[data-focus-key="perspective:none"]').click();}else d.querySelector('[data-view="'+view+'"]').click();assert.equal(d.getElementById('addAction').disabled,false);d.getElementById('addAction').click();await settle();assert.equal(f.requests.some(r=>r.args?.kind==='add'),false);assert.equal(d.getElementById('editTitle').value,'');await fillCreation(f);const create=f.requests.find(r=>r.args?.kind==='add');assert.equal(create.args.payload.parent_id,null);assert.equal(create.args.payload.project_id,null);assert.equal(d.getElementById('editTitle').value,'New action');assert.equal(d.getElementById('editor').hidden,false);assert(d.querySelector('[data-action-id="f25a36bb-3eef-4c21-b3ee-0cc45cb596ab"]'));d.querySelector('[data-view="history"]').click();assert.equal(d.getElementById('retained').hidden,false);}});
test('Due and Defer use date plus explicit24h clocks and retain partial numeric input across refresh',async(t)=>{const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window;for(const [dateId,timeId] of [['editDue','dueTime'],['deferDate','deferUntil']]){const date=d.getElementById(dateId),time=d.getElementById(timeId);assert.equal(date.type,'date');assert.equal(time.type,'text');assert.equal(time.getAttribute('inputmode'),'numeric');date.value='2026-10-08';date.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(time.value,'09:00');time.value='2315';time.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(time.value,'23:15');time.value='23';time.dispatchEvent(new w.Event('input',{bubbles:true}));d.getElementById('refresh').click();await settle();assert.equal(time.value,'23');assert.equal(d.getElementById('refresh').dataset.state,'error');}});

test('Action Add waits for original IME final text before serial creation',async(t)=>{const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window,node=d.getElementById('editNotes');node.dispatchEvent(new w.Event('compositionstart'));node.value='途中';d.getElementById('addAction').click();assert.equal(f.requests.some(r=>r.args?.kind==='add'),false);node.value=' exact 完成 ';node.dispatchEvent(new w.Event('compositionend'));await settle();assert.equal(f.requests.some(r=>r.args?.kind==='add'),false);await fillCreation(f);const writes=f.requests.filter(r=>r.name==='apply_change');assert.equal(writes[0].args.kind,'edit');assert.equal(writes[0].args.payload.notes,' exact 完成 ');assert.equal(writes[1].args.kind,'add');assert.equal(writes[1].args.payload.parent_id,f.action.id);});
test('field validation stays beside its responsible input and Refresh owns one global status at header right',async(t)=>{const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window,refresh=d.getElementById('refresh');assert.equal(d.getElementById('saveIndicator'),null);assert.equal(refresh.parentElement.lastElementChild,refresh);assert.equal(refresh.getAttribute('aria-label'),'Refresh');assert.equal(refresh.getAttribute('aria-describedby'),'refreshStatus');assert.equal(d.getElementById('refreshStatus').parentElement,refresh);assert.equal(refresh.querySelectorAll('svg').length,1);const date=d.getElementById('editDue'),time=d.getElementById('dueTime');assert.equal(time.placeholder,'HH:mm');assert.equal(time.value,'');date.value='2026-10-09';date.dispatchEvent(new w.Event('input',{bubbles:true}));time.value='13:';time.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(time.value,'13:');assert.equal(time.getAttribute('aria-invalid'),'true');assert.equal(time.getAttribute('aria-describedby'),'dueError');assert.equal(date.getAttribute('aria-invalid'),'false');assert.equal(d.getElementById('dueError').hidden,false);assert.equal(d.getElementById('dueError').closest('#organizeDetails').id,'organizeDetails');time.dispatchEvent(new w.Event('blur'));await settle();assert.equal(d.getElementById('saveProblem').hidden,true);assert.equal(refresh.dataset.state,'error');refresh.click();await settle();assert.equal(time.value,'13:');assert.equal(time.getAttribute('aria-invalid'),'true');time.value='1317';time.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(time.value,'13:17');assert.equal(time.getAttribute('aria-invalid'),'false');assert.equal(time.hasAttribute('aria-describedby'),false);assert.equal(d.getElementById('dueError').hidden,true);time.dispatchEvent(new w.Event('blur'));await settle();assert.equal(refresh.dataset.state,'saved');const title=d.getElementById('editTitle');title.value='x'.repeat(201);title.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(title.getAttribute('aria-invalid'),'true');assert.equal(title.getAttribute('aria-describedby'),'titleError');assert.equal(d.getElementById('titleError').parentElement,title.parentElement);title.dispatchEvent(new w.Event('blur'));await settle();assert.equal(d.getElementById('saveProblem').hidden,true);title.value='Corrected';title.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.getElementById('titleError').hidden,true);assert.equal(title.getAttribute('aria-invalid'),'false');});
test('repeated Add replaces local objects instead of creating unnamed parent chains',async t=>{for(const kind of ['action','project','tag']){const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;const add=()=>{if(kind==='action')d.getElementById('addAction').click();else d.getElementById('addMenu'+(kind==='project'?'Project':'Tag')).click();};add();const field=d.getElementById(kind==='action'?'editTitle':'catalogEditName');field.value='Discard selected draft';field.dispatchEvent(new w.Event('input',{bubbles:true}));add();await settle();const rows=d.querySelectorAll(kind==='action'?'.action-row[data-action-id^="local:"]':'.catalog-row[data-catalog-id^="local:"]');assert.equal(rows.length,1);assert.equal(rows[0].getAttribute('aria-level'),'1');assert.equal(field.value,'');assert.equal(f.requests.filter(r=>r.name==='apply_change').length,0);d.getElementById(kind==='action'?'closeEditor':'catalogClose').click();await settle();assert.equal(d.querySelectorAll('[data-action-id^="local:"],[data-catalog-id^="local:"]').length,0);}});
test('Tag keyboard chooser exposes relative before and after with one typed move request',async t=>{const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.state.tags=[{id:'one',name:'One',order:0,parent_id:null},{id:'two',name:'Two',order:1,parent_id:null}];d.getElementById('refresh').click();await settle();d.querySelector('[data-view="tags"]').click();const source=d.querySelector('[data-catalog-id="two"] .catalog-select');source.dispatchEvent(new w.KeyboardEvent('keydown',{key:' ',bubbles:true}));assert.equal(d.querySelector('#movePlacement option[value="before"]').hidden,false);assert.equal(d.querySelector('#movePlacement option[value="after"]').hidden,false);d.getElementById('movePlacement').value='before';d.getElementById('movePlacement').dispatchEvent(new w.Event('change'));d.getElementById('moveDestination').value='one';d.getElementById('moveDestination').dispatchEvent(new w.Event('change'));d.getElementById('applyMove').click();await settle();const moves=f.requests.filter(r=>r.args?.kind==='tag_move'&&r.name==='apply_change');assert.equal(moves.length,1);assert.deepEqual(moves[0].args.payload,{id:'two',placement:'before',anchor_id:'one'});});
test('closing an untouched Project or Tag inspector removes only its local row without writes',async t=>{for(const kind of ['project','tag']){const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document;d.getElementById('addMenu'+(kind==='project'?'Project':'Tag')).click();await settle();assert.equal(d.querySelectorAll('.catalog-row[data-catalog-id^="local:"]').length,1);d.getElementById('catalogClose').click();await settle();assert.equal(d.querySelectorAll('.catalog-row[data-catalog-id^="local:"]').length,0);assert.equal(f.requests.filter(r=>r.name==='apply_change').length,0);}});

test('selection and refreshed row content retain focused child controls and never scroll focus recovery',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window,row=d.querySelector('.action-row'),grip=row.querySelector('.drag-handle'),select=row.querySelector('.action-select'),complete=row.querySelector('.complete');
 grip.focus();select.dispatchEvent(new w.MouseEvent('click',{bubbles:true,shiftKey:true}));
 assert.equal(row.querySelector('.drag-handle'),grip);assert.equal(row.querySelector('.action-select'),select);assert.equal(row.querySelector('.complete'),complete);assert.equal(d.activeElement,grip);
 f.action.title='Changed externally';f.state.revision++;d.getElementById('refresh').click();await settle();
 assert.equal(row.querySelector('.drag-handle'),grip);assert.equal(row.querySelector('.action-select'),select);assert.equal(d.activeElement,grip);assert.equal(select.textContent,'Changed externally');assert.match(complete.getAttribute('aria-label'),/Changed externally/);
});
test('Escape after an unselected drag exposes retained selection without replacing focused grip',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window,grip=d.querySelector('.drag-handle');grip.focus();
 const pointer=(node,type,x)=>{const event=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperties(event,{pointerId:{value:7},pointerType:{value:'mouse'},button:{value:0},clientX:{value:x},clientY:{value:120}});node.dispatchEvent(event);};
 pointer(grip.closest('.action-row'),'pointerdown',20);pointer(w,'pointermove',40);assert.equal(d.getElementById('selectionBar').hidden,true);w.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
 assert.equal(d.getElementById('selectionBar').hidden,false);assert.equal(d.getElementById('selectionCount').textContent,'1 selected');assert.equal(d.querySelectorAll('.batch-selected').length,1);assert.equal(d.querySelector('.drag-handle'),grip);assert.equal(d.activeElement,grip);assert.equal(f.requests.some(r=>r.args?.kind==='action_move'),false);
});

test('unfinished IME raw draft and newer final text retain external correction conflict across refresh',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window,notes=d.getElementById('editNotes');notes.focus();notes.dispatchEvent(new w.Event('compositionstart'));notes.value='途中';notes.dispatchEvent(new w.Event('input',{bubbles:true}));notes.setSelectionRange(1,2);
 f.action.notes='external correction';f.state.revision++;d.getElementById('refresh').click();await settle();assert.equal(d.getElementById('editNotes'),notes);assert.equal(notes.value,'途中');assert.equal(notes.selectionStart,1);assert.equal(notes.selectionEnd,2);assert.equal(d.activeElement,notes);assert.equal(f.requests.some(r=>r.name==='apply_change'),false);
 notes.value='新しい完成';notes.dispatchEvent(new w.Event('compositionend'));for(const fn of [...f.timers.values()])fn();await settle();assert.equal(notes.value,'新しい完成');assert.equal(f.action.notes,'external correction');assert.equal(f.requests.some(r=>r.name==='apply_change'),false);assert.equal(d.getElementById('useMine').hidden,false);d.getElementById('useMine').click();await settle();assert.equal(f.action.notes,'新しい完成');
});

test('reordering a retained row restores its exact focused control without requesting scroll',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.state.actions.push({...f.action,id:'second',title:'Second',order:1});f.state.list_scopes.inbox.push('second');d.getElementById('refresh').click();await settle();
 const grip=d.querySelector('.drag-handle'),calls=[],focus=w.HTMLElement.prototype.focus;w.HTMLElement.prototype.focus=function(options){calls.push(options);return focus.call(this,options);};grip.focus({preventScroll:true});calls.length=0;
 f.action.order=2;f.state.actions.reverse();f.state.list_scopes.inbox.reverse();f.state.revision++;d.getElementById('refresh').click();await settle();assert.equal(d.querySelectorAll('.drag-handle')[1],grip);assert.equal(d.activeElement,grip);assert(calls.every(options=>options?.preventScroll===true));
});

test('canceled duplicate Tag gesture and same-view display changes preserve occurrence keys and visible selection controls',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;f.state.tags=[{id:'one',name:'One',order:0},{id:'two',name:'Two',order:1}];f.action.tags=f.state.tags;f.action.is_deferred=false;d.getElementById('refresh').click();await settle();d.querySelector('[data-view="tags"]').click();const rows=[...d.querySelectorAll('.action-row')],keys=rows.map(row=>row.dataset.occurrenceKey);rows[0].querySelector('.action-select').click();rows[1].querySelector('.action-select').dispatchEvent(new w.MouseEvent('click',{bubbles:true,shiftKey:true}));
 const pointer=(node,type,x)=>{const e=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperties(e,{pointerId:{value:3},pointerType:{value:'mouse'},button:{value:0},clientX:{value:x},clientY:{value:130}});node.dispatchEvent(e);};pointer(rows[0],'pointerdown',10);pointer(w,'pointermove',30);w.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
 const selected=()=>[...d.querySelectorAll('.batch-selected')].map(row=>row.dataset.occurrenceKey);assert.deepEqual(selected(),keys);assert.equal(d.getElementById('selectionCount').textContent,'2 rows · 1 actions');assert.equal(d.getElementById('selectionBar').hidden,false);
 d.querySelector('[data-display-choice="completed"]').click();assert.deepEqual(selected(),keys);assert.equal(d.getElementById('selectionBar').hidden,false);assert.equal(f.requests.some(r=>r.args?.kind==='action_move'),false);
});


test('Refresh state icons distinguish pending, writing and saved without animation and preserve recovery semantics',async t=>{
 const f=createFixture();t.after(()=>f.dom.window.close());await settle();selectFirst(f);const d=f.dom.window.document,w=f.dom.window,refresh=d.getElementById('refresh'),live=d.getElementById('refreshStatus'),row=d.querySelector('.action-row'),notes=d.getElementById('editNotes');
 const shape=()=>refresh.querySelector('svg').innerHTML;const saved=shape();assert.match(saved,/m5 12 4 4 10-10/);f.setLost(true);
 notes.value='Retain this proposal';notes.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(refresh.dataset.state,'pending');const pending=shape();assert.notEqual(pending,saved);
 notes.dispatchEvent(new w.Event('blur'));await settle();assert.equal(refresh.dataset.state,'saving');const saving=shape();assert.notEqual(saving,saved);assert.notEqual(saving,pending);assert.equal(live.textContent,'Saving changes');assert.equal(d.getElementById('saveFeedback').textContent,'Saving changes');assert.equal(d.getElementById('saveFeedback').hidden,false);assert.equal(refresh.getAttribute('aria-busy'),'true');assert.equal(d.querySelector('.action-row'),row);assert.equal(d.getElementById('editNotes'),notes);assert.equal(notes.disabled,false);
 const sent=f.requests.find(request=>request.name==='apply_change');assert(sent);for(const callback of [...f.timers.values()])callback();await settle();assert.equal(refresh.dataset.state,'unknown');assert.equal(d.getElementById('saveFeedback').textContent,'Save result unknown');assert.equal(d.getElementById('saveFeedback').hidden,false);assert.notEqual(shape(),saving);assert.equal(d.getElementById('unknown').hidden,false);
 f.setLost(false);d.getElementById('retry').click();await settle();assert.deepEqual(f.requests.filter(request=>request.name==='apply_change').at(-1).args,sent.args);assert.equal(refresh.dataset.state,'saved');assert.equal(shape(),saved);assert.equal(d.getElementById('saveFeedback').hidden,true);assert.equal(d.getElementById('refresh'),refresh);assert.equal(d.getElementById('refreshStatus'),live);assert.equal(refresh.getAttribute('aria-label'),'Refresh');assert.equal(refresh.getAttribute('aria-describedby'),'refreshStatus');assert.equal(refresh.querySelectorAll('svg').length,1);
 const title=d.getElementById('editTitle');title.value='x'.repeat(201);title.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(refresh.dataset.state,'error');assert.equal(d.getElementById('saveFeedback').textContent,'Changes need attention');assert.equal(d.getElementById('saveFeedback').hidden,false);assert.equal(d.getElementById('saveFeedback').getAttribute('aria-hidden'),'true');
 const reads=f.requests.filter(request=>request.name==='list_actions').length;refresh.click();await settle();assert.equal(f.requests.filter(request=>request.name==='list_actions').length,reads+1);
});


test('header resize invalidates active drag geometry while unchanged pointer motion retains the cache',async t=>{
 let resized;const observed=[];class ResizeObserver{constructor(callback){resized=callback;}observe(node){observed.push(node);}disconnect(){}}
 const f=createFixture(widgetHtml,{resizeObserver:ResizeObserver});t.after(()=>f.dom.window.close());await settle();const d=f.dom.window.document,w=f.dom.window;
 for(const [index,title] of ['Destination A','Destination B'].entries()){const id='destination-'+index;f.state.actions.push({...f.action,id,title,order:index+1});f.state.list_scopes.inbox.push(id);}d.getElementById('refresh').click();await settle();assert(observed.includes(d.querySelector('header')));
 let offset=0,reads=0;const rows=[...d.querySelectorAll('.action-row')];for(const [index,row] of rows.entries()){row.getBoundingClientRect=()=>{reads++;return {left:0,right:300,top:offset+index*60,bottom:offset+(index+1)*60,height:60};};row.querySelector('.action-select').getBoundingClientRect=()=>({left:20,right:280,top:offset+index*60+10,bottom:offset+index*60+40,height:30});}
 d.getElementById('actions').getBoundingClientRect=()=>({left:0,right:300});d.querySelector('.list-panel').getBoundingClientRect=()=>({left:0,right:300});d.elementFromPoint=(x,y)=>rows[Math.min(rows.length-1,Math.max(0,Math.floor((y-offset)/60)))].querySelector('.action-select');
 const pointer=(target,type,x,y)=>{const event=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperties(event,{pointerId:{value:9},pointerType:{value:'mouse'},button:{value:0},clientX:{value:x},clientY:{value:y}});target.dispatchEvent(event);};
 pointer(rows[0],'pointerdown',20,30);pointer(w,'pointermove',120,150);f.flushFrames();await settle();assert.match(d.getElementById('moveStatus').textContent,/Destination B/);const measured=reads;pointer(w,'pointermove',121,150);f.flushFrames();await settle();assert.equal(reads,measured);
 offset=60;resized([{target:d.querySelector('header')}]);assert.equal(f.frameCount(),1);f.flushFrames();await settle();assert(reads>measured);assert.match(d.getElementById('moveStatus').textContent,/Destination A/);assert.deepEqual([...d.querySelectorAll('.action-row')],rows);w.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
});
