import test from 'node:test';import assert from 'node:assert/strict';
import {createMovementModel} from '../../lib/ui/model/movement.ts';import {actionMoveEdits,change,orderedActions} from '../../lib/domain/core.ts';
const model=createMovementModel(),now='2026-10-03T00:00:00Z',id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const row=(n,patch={})=>({id:id(n),parent_id:null,project_id:null,order:n,title:'Action '+n,notes:'raw 日本語',status:'active',due_at:null,defer_until:null,flagged:false,revision:1,created_at:now,updated_at:now,...patch});
const snapshot={revision:1,actions:[row(1,{project_id:id(91)}),row(2,{parent_id:id(1),project_id:id(92)}),row(3,{project_id:id(91),status:'on-hold'}),row(4,{project_id:id(91),status:'completed',order:100}),row(5,{project_id:id(92)}),row(6,{parent_id:id(3),order:900,defer_until:'2027-01-01T00:00:00Z'})],projects:[{id:id(91),name:'Work',order:0,parent_id:null,description:''},{id:id(92),name:'Personal',order:0,parent_id:null,description:''}],tags:[],action_tags:[],perspectives:[],catalog_identity_ledger:[]};
test('UI canonical bundle roots and every supported intent match authoritative movement validity and full hidden ordering',()=>{const before=structuredClone(snapshot);for(const selected of [[1],[2,1],[3,1,2],[2,5]])for(const placement of ['before','after','inside','root'])for(const anchor of placement==='root'?[undefined]:[1,2,3,4,5,6]){const intent=model.intent(snapshot.actions,selected.map(id),placement,anchor===undefined?undefined:id(anchor));const payload={ids:selected.map(id),placement,...(anchor===undefined?{}:{anchor_id:id(anchor)})};let valid=true;try{actionMoveEdits(snapshot,payload);}catch{valid=false;}assert.equal(intent.allowed,valid,JSON.stringify(payload));if(intent.allowed){const after=change(snapshot,{kind:'action_move',payload:intent.payload},now);assert.equal(new Set(after.actions.map(a=>a.id)).size,snapshot.actions.length);for(const action of after.actions)for(const field of ['title','notes','status','due_at','defer_until','flagged','project_id'])assert.deepEqual(action[field],snapshot.actions.find(a=>a.id===action.id)[field]);}}assert.deepEqual(snapshot,before);assert.deepEqual(model.ordered(snapshot.actions).map(a=>a.id),orderedActions(snapshot).map(a=>a.id));const roots=model.intent(snapshot.actions,[id(3),id(2),id(1)],'inside',id(5)).roots;assert.deepEqual(roots,[id(1),id(3)]);});
test('shift range is inclusive and visible-only, single selection replaces prior ranges, invalid batches never prune missing identities',()=>{const visible=['a','b','d','e'];assert.deepEqual(model.selection(['a'],'a','d',visible,true),{ids:['a','b','d'],anchor:'a'});assert.deepEqual(model.selection(['a','d'],'a','d',visible,false),{ids:['d'],anchor:'d'});assert.deepEqual(model.selection(['a','b','d','e'],'a','b',visible,true).ids,['a','b']);assert.equal(model.intent(snapshot.actions,[id(1),id(99)],'root').allowed,false);assert.equal(model.intent(snapshot.actions,[id(1),id(1)],'root').allowed,false);});
test('structural movement baseline includes hidden destination/subtree and ancestors but excludes unrelated groups and text',()=>{const payload=model.intent(snapshot.actions,[id(2)],'inside',id(3)).payload,base=model.fingerprint(snapshot.actions,payload);const title=structuredClone(snapshot.actions);title[0].title='other';assert.equal(model.fingerprint(title,payload),base);const unrelated=structuredClone(snapshot.actions);unrelated.find(a=>a.id===id(5)).order=200;assert.equal(model.fingerprint(unrelated,payload),base);const hidden=structuredClone(snapshot.actions);hidden.find(a=>a.id===id(6)).order=901;assert.notEqual(model.fingerprint(hidden,payload),base);const added=[...snapshot.actions,row(7,{parent_id:id(3)})];assert.notEqual(model.fingerprint(added,payload),base);});

function referenceContains(actions,ancestor,id){const seen=new Set();let current=actions.find(action=>action.id===id);while(current?.parent_id){if(current.parent_id===ancestor)return true;if(seen.has(current.parent_id))return true;seen.add(current.parent_id);current=actions.find(action=>action.id===current.parent_id);}return false;}
function referenceOrder(actions){const compare=(a,b)=>a.order-b.order||(a.id<b.id?-1:a.id>b.id?1:0),ordered=[],seen=new Set();function visit(action){if(seen.has(action.id))return;seen.add(action.id);ordered.push(action);for(const child of actions.filter(candidate=>candidate.parent_id===action.id).sort(compare))visit(child);}const roots=actions.filter(action=>!action.parent_id).sort((a,b)=>((a.project_id??'')<(b.project_id??'')?-1:(a.project_id??'')>(b.project_id??'')?1:0)||compare(a,b));for(const root of roots)visit(root);return ordered;}
function referenceRelevant(actions,payload){const selected=actions.filter(action=>payload.ids.includes(action.id)),anchor=actions.find(action=>action.id===payload.anchor_id),parent=payload.placement==='inside'?anchor?.id:anchor?.parent_id??null;return actions.filter(action=>payload.ids.includes(action.id)||payload.ids.some(id=>referenceContains(actions,id,action.id)||referenceContains(actions,action.id,id))||action.id===anchor?.id||Boolean(anchor&&referenceContains(actions,action.id,anchor.id))||(payload.placement==='root'?!action.parent_id&&selected.some(root=>(root.project_id??null)===(action.project_id??null)):action.parent_id===parent&&(parent!==null||(action.project_id??null)===(anchor?.project_id??null)))).map(action=>action.id);}
function referenceFingerprint(actions,payload){const ids=payload?referenceRelevant(actions,payload):actions.map(action=>action.id);return JSON.stringify(actions.filter(action=>ids.includes(action.id)).map(action=>[action.id,action.parent_id??null,action.project_id??null,action.order]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))));}
function referenceIntent(actions,ids,placement,anchorId){const rejected=reason=>({allowed:false,reason,roots:[],payload:null});if(!['before','after','inside','root'].includes(placement))return rejected('Choose a valid placement.');if(!ids.length)return rejected('Select an action to move.');if(new Set(ids).size!==ids.length||ids.some(id=>!actions.some(action=>action.id===id)))return rejected('The selection is no longer available.');const selected=new Set(ids),roots=referenceOrder(actions).filter(action=>selected.has(action.id)&&!ids.some(id=>id!==action.id&&referenceContains(actions,id,action.id)));if(!roots.length)return rejected('The selection is no longer available.');if(placement!=='root'){const anchor=actions.find(action=>action.id===anchorId);if(!anchor)return rejected('Choose an available destination.');if(roots.some(action=>action.id===anchor.id||referenceContains(actions,action.id,anchor.id)))return rejected('An action cannot move into its own subtree.');if((placement==='before'||placement==='after')&&!anchor.parent_id&&roots.some(action=>(action.project_id??null)!==(anchor.project_id??null)))return rejected('Choose a destination in the same Project, or move Into the action.');}const payload={ids:roots.map(action=>action.id),placement,...(placement==='root'?{}:{anchor_id:anchorId})};return {allowed:true,reason:'',roots:payload.ids,payload};}
test('seeded forest indexes match independent scan references for bundled selections, hidden siblings, ties and invalid targets',()=>{
 const seed=0x9e3779b9;let state=seed;const random=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/0x100000000;};
 for(let forest=0;forest<12;forest++){
  const actions=[];for(let i=0;i<28;i++){const parent=i&&random()<.63?actions[Math.floor(random()*i)].id:null;actions.push({id:`f${forest}-a${i}`,parent_id:parent,project_id:parent?random()<.5?'p0':'p1':random()<.5?'p0':'p1',order:Math.floor(random()*8)});}
  const before=structuredClone(actions),prepared=model.index(actions);assert.deepEqual(model.ordered(actions,prepared).map(action=>action.id),referenceOrder(actions).map(action=>action.id),`seed ${seed}, forest ${forest}, order`);
  for(const action of actions)for(const ancestor of actions)assert.equal(model.contains(actions,ancestor.id,action.id,prepared),referenceContains(actions,ancestor.id,action.id),`seed ${seed}, forest ${forest}, ancestry ${ancestor.id}/${action.id}`);
  for(let sample=0;sample<30;sample++){
   const ids=[...new Set(Array.from({length:1+Math.floor(random()*5)},()=>actions[Math.floor(random()*actions.length)].id))],placement=['before','after','inside','root'][Math.floor(random()*4)],anchor=random()<.1?'missing':actions[Math.floor(random()*actions.length)].id,payload={ids,placement,...(placement==='root'?{}:{anchor_id:anchor})};
   assert.deepEqual(model.intent(actions,ids,placement,anchor,prepared),referenceIntent(actions,ids,placement,anchor),`seed ${seed}, forest ${forest}, intent ${JSON.stringify(payload)}`);
   assert.deepEqual(model.relevant(actions,payload,prepared),referenceRelevant(actions,payload),`seed ${seed}, forest ${forest}, relevant ${JSON.stringify(payload)}`);
   assert.equal(model.fingerprint(actions,payload,prepared),referenceFingerprint(actions,payload),`seed ${seed}, forest ${forest}, target fingerprint ${JSON.stringify(payload)}`);
   assert.equal(model.sourceFingerprint(actions,ids,prepared),JSON.stringify(actions.filter(action=>ids.some(id=>action.id===id||referenceContains(actions,id,action.id)||referenceContains(actions,action.id,id))).map(action=>[action.id,action.parent_id??null,action.project_id??null,action.order]).sort((a,b)=>String(a[0]).localeCompare(String(b[0])))),`seed ${seed}, forest ${forest}, source fingerprint`);
  }
  assert.deepEqual(actions,before,`seed ${seed}, forest ${forest}, input nonmutation`);
 }
});
