import test from 'node:test';import assert from 'node:assert/strict';import {createTreeDropModel} from '../../lib/ui/model/tree-drop.ts';
const model=createTreeDropModel(),snapshot={actions:[{id:'a',parent_id:null},{id:'b',parent_id:'a'},{id:'c',parent_id:'b'}],projects:[{id:'p',parent_id:null},{id:'q',parent_id:'p'}],tags:[{id:'t',parent_id:null},{id:'u',parent_id:'t'}]},row={kind:'action',id:'c',key:'c',top:100,bottom:150,left:20,catalogId:'q',last:true,title:{left:60,right:180,top:108,bottom:130}};
test('final child bottom-left outdents to root without a separate target; center preserves containment',()=>{assert.deepEqual(model.resolve('action',row,25,149,120,snapshot),{kind:'action',placement:'root',parent_id:null,key:'c',depth:0});assert.equal(model.resolve('action',row,100,119,120,snapshot).placement,'inside');assert.equal(model.resolve('action',{...row,last:false},102,149,120,snapshot).anchor,'b');});
test('mixed Action edges expose catalog ancestry while catalog center rejects Action targets',()=>{assert.equal(model.resolve('project',row,25,149,120,snapshot).placement,'root');assert.equal(model.resolve('project',row,100,119,120,snapshot),null);assert.equal(model.resolve('tag',{...row,catalogId:'u'},25,149,120,snapshot).parent_id,null);assert.equal(model.resolve('action',{...row,kind:'project',id:'q'},100,119,120,snapshot).kind,'classification');});
test('relative horizontal motion reaches semantic deep levels despite capped rendering, without mutation',()=>{const before=structuredClone(snapshot);assert.equal(model.resolve('action',{...row,last:false},120,149,120,snapshot).depth,2);assert.equal(model.resolve('action',{...row,last:false},102,149,120,snapshot).depth,1);assert.equal(model.resolve('action',{...row,last:false},84,149,120,snapshot).depth,0);assert.deepEqual(snapshot,before);});
test('catalog root destination peers and selected parent dependencies detect structural drift without reacting to text',()=>{const nodes=[{id:'p',parent_id:null,order:0},{id:'q',parent_id:'p',order:0},{id:'r',parent_id:null,order:1}],root=model.fingerprint(nodes,'q',undefined,true);assert.notEqual(model.fingerprint([...nodes,{id:'s',parent_id:null,order:2}],'q',undefined,true),root);const inside=model.fingerprint(nodes,'q','r');assert.notEqual(model.fingerprint([...nodes,{id:'s',parent_id:'r',order:0}],'q','r'),inside);assert.equal(model.fingerprint(nodes.map(n=>({...n,name:'Changed title'})),'q',undefined,true),root);});
test('geometric hit includes existing left gutter and the bounded final insertion band, excluding unrelated regions',()=>{const rows=[{...row,left:100,top:100,bottom:150,last:false},{...row,key:'last',left:100,top:150,bottom:200,last:true}],bounds={left:56,right:500};for(const x of [99,88,70])for(const y of [198,202,208])assert.equal(model.hit(rows,bounds,x,y)?.key,'last');assert.equal(model.hit(rows,bounds,55,198),null);assert.equal(model.hit(rows,bounds,501,198),null);assert.equal(model.hit(rows,bounds,70,209),null);assert.equal(model.hit(rows,bounds,70,99),null);assert.equal(model.hit(rows,{left:0,right:390},-1,198),null);});
test('the final row left gutter is a root insertion destination at any vertical point, while title center remains Inside',()=>{const final={...row,left:100,top:100,bottom:150,last:true};for(const kind of ['action','project','tag'])for(const y of [101,125,149]){const target=model.resolve(kind,final,88,y,180,snapshot);assert.equal(target.placement,'root',kind+':'+y);assert.equal(target.depth,0);}assert.equal(model.resolve('action',{...final,title:{left:120,right:250,top:110,bottom:140}},180,125,180,snapshot).placement,'inside');const middle={...final,last:false};assert.equal(model.resolve('action',middle,88,101,180,snapshot).placement,'after');assert.equal(model.resolve('action',{...middle,id:'a'},88,101,180,snapshot).placement,'before');});

function referenceChain(nodes,id){const result=[],seen=new Set();let current=nodes.find(node=>node.id===id);while(current&&!seen.has(current.id)){seen.add(current.id);result.unshift(current);current=nodes.find(node=>node.id===current.parent_id);}return result;}
function referenceTreeFingerprint(nodes,id,anchor,root){const source=nodes.find(node=>node.id===id),target=nodes.find(node=>node.id===anchor);return JSON.stringify(nodes.filter(node=>node.id===id||node.id===anchor||referenceChain(nodes,node.id).some(parent=>parent.id===id)||referenceChain(nodes,id).some(parent=>parent.id===node.id)||referenceChain(nodes,anchor||'').some(parent=>parent.id===node.id)||node.parent_id===source?.parent_id||node.parent_id===target?.parent_id||node.parent_id===target?.id||root&&!node.parent_id).map(node=>[node.id,node.parent_id??null,node.order??null]).sort((a,b)=>String(a[0])<String(b[0])?-1:1));}
test('seeded containment indexes match the scan reference and binary geometry hits preserve non-overlapping row semantics',()=>{
 const seed=0x51ed270b;let state=seed;const random=()=>{state=(Math.imul(state,1103515245)+12345)>>>0;return state/0x100000000;};
 for(let forest=0;forest<10;forest++){
  const nodes=[];for(let i=0;i<24;i++)nodes.push({id:`t${forest}-${i}`,parent_id:i&&random()<.7?nodes[Math.floor(random()*i)].id:null,order:Math.floor(random()*6)});const before=structuredClone(nodes),prepared=model.index(nodes);
  for(const node of nodes){assert.deepEqual(model.chain(nodes,node.id,prepared),referenceChain(nodes,node.id),`seed ${seed}, forest ${forest}, chain ${node.id}`);for(const anchor of [undefined,...nodes.slice(0,4).map(value=>value.id)])for(const root of [false,true])assert.equal(model.fingerprint(nodes,node.id,anchor,root,prepared),referenceTreeFingerprint(nodes,node.id,anchor,root),`seed ${seed}, forest ${forest}, fingerprint ${node.id}/${anchor}/${root}`);}
  const geometry=Array.from({length:24},(_,index)=>({kind:'action',id:String(index),key:String(index),left:40,top:100+index*20,bottom:118+index*20,last:index===23}));for(let y=85;y<610;y++)assert.equal(model.hit(geometry,{left:0,right:500},40,y)?.key??null,geometry.find(candidate=>y>=candidate.top&&y<=candidate.bottom+(candidate.last?8:0))?.key??null,`seed ${seed}, geometry y=${y}`);assert.deepEqual(nodes,before);
 }
});
