export function mountDom(document,window,transport,ids,model,createToolClient,createUiController,createDisplayBridge,diagnostics){
 const count=(name,callback)=>{diagnostics?.increment(name);return callback();};
 const el=id=>document.getElementById(id);const zone=()=>window.Intl.DateTimeFormat().resolvedOptions().timeZone;
 function zonedLocal(at){const parts=new window.Intl.DateTimeFormat('en-CA',{timeZone:zone(),year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new window.Date(at));const part=key=>parts.find(p=>p.type===key).value;return part('year')+'-'+part('month')+'-'+part('day')+'T'+part('hour')+':'+part('minute')+':'+part('second');}
 let resizeObserver=null,disposed=false;const requestFrame=(callback)=>window.requestAnimationFrame?window.requestAnimationFrame(callback):window.setTimeout(()=>callback(window.performance?.now?.()||Date.now()),0),cancelFrame=handle=>window.cancelAnimationFrame?window.cancelAnimationFrame(handle):window.clearTimeout(handle);let editorId=null,compositionInput=null;let rowNodes=new Map(),rowSignatures=new Map(),emptyRow=null;let gesture=null,dragFrame=null,lastDragFrame=0,finishAfterFrame=false,geometryDirty=true,geometryCache=[],geometryByKey=new Map(),geometryBounds={left:0,right:0},highlightedRow=null,moveOrigin=null,suppressRowClick=false,outlineEntries=[],outlineByKey=new Map(),movementIndex=null,actionIndex=null,projectIndex=null,tagIndex=null,indexedData=null,indexedDrafts=null,indexedTransients=null;const editor=el('editor');
 function updateIndexes(){if(indexedData===state.data&&indexedDrafts===state.drafts&&indexedTransients===state.transients)return;movementIndex=model.movement.index(displayData.actions,movementIndex||undefined);actionIndex=model.treeDrop.index(displayData.actions);projectIndex=model.treeDrop.index(displayData.projects||[]);tagIndex=model.treeDrop.index(displayData.tags||[]);indexedData=state.data;indexedDrafts=state.drafts;indexedTransients=state.transients;controller.dispatch({type:'gesture.context',context:{actions:displayData.actions,projects:displayData.projects||[],tags:displayData.tags||[],index:movementIndex,projectIndex,tagIndex}});}
 function invalidateGeometry(){geometryDirty=true;if(state.interaction.gesture?.active)requestDragFrame();}
 function setDropRow(row,className){if(highlightedRow===row&&highlightedRow?.dataset.dropClass===className)return;if(highlightedRow){highlightedRow.classList.remove(...(highlightedRow.dataset.dropClass||'').split(' ').filter(Boolean));delete highlightedRow.dataset.dropClass;}highlightedRow=row;if(row){row.classList.add(className);row.dataset.dropClass=className;}}
 const setDisabled=(node,value)=>{const next=Boolean(value);if(node.disabled!==next)node.disabled=next;};const setMoveStatus=value=>{const node=el('moveStatus'),text=String(value);if(node.textContent!==text)node.textContent=text;};
 function rowSignature(entry,tree,visibleActionIds,occurrenceSet){if(entry.kind!=='action')return JSON.stringify([entry.key,entry.kind,entry.id,entry.level,entry.label,entry.expandable,state.interaction.view.collapsed.includes(entry.key),state.catalogDrafts[entry.key]?.name,state.inspector?.kind===entry.kind&&state.inspector?.id===entry.id]);const action=entry.action,draft=state.drafts[action.id],parentVisible=visibleActionIds.has(action.parent_id),hiddenParentTitle=parentVisible?'':actionIndex.byId.get(action.parent_id)?.title;return JSON.stringify([entry.key,entry.level,tree,action.id,action.title,action.status,action.parent_id,action.flagged,entry.parentKey,parentVisible,hiddenParentTitle,action.defer_reasons,action.due_at,action.project_path,action.tags,draft?.title,occurrenceSet.has(entry.key),state.interaction.selection.active===entry.key&&state.inspector?.kind==='action']);}
 function bindPointerDown(row,handler){if(row._pointerDown)row.removeEventListener('pointerdown',row._pointerDown);row._pointerDown=handler||null;if(handler)row.addEventListener('pointerdown',handler);}
 function patchNode(current,next){
  if(current.nodeType!==next.nodeType||current.nodeName!==next.nodeName){current.replaceWith(next);return next;}
  if(current.nodeType===3){if(current.nodeValue!==next.nodeValue)current.nodeValue=next.nodeValue;return current;}
  for(const attribute of [...current.attributes])if(!next.hasAttribute(attribute.name))current.removeAttribute(attribute.name);
  for(const attribute of [...next.attributes])if(current.getAttribute(attribute.name)!==attribute.value)current.setAttribute(attribute.name,attribute.value);
  for(const name of ['onclick','onkeydown','onpointerdown','ondragstart'])current[name]=next[name];
  if(current._pointerDown||next._pointerDown)bindPointerDown(current,next._pointerDown);
  const children=[...next.childNodes];for(let index=0;index<children.length;index++){const child=current.childNodes[index];if(child)patchNode(child,children[index]);else current.append(children[index]);}
  while(current.childNodes.length>children.length)current.lastChild.remove();return current;
 }
 function patchRow(current,next){return patchNode(current,next);}
 function reconcileRows(container,desired){const started=diagnostics?window.performance.now():null;const retained=new Set(desired);let changed=false;for(const current of [...container.children])if(!retained.has(current)){current.remove();changed=true;}for(let index=0;index<desired.length;index++){const current=container.children[index]||null;if(current!==desired[index]){container.insertBefore(desired[index],current);changed=true;}}if(started!==null)diagnostics.record('dom.patch.rows',window.performance.now()-started);return changed;}

 const message=text=>{el('status').textContent=model.saveStatus.message(text)||state.operationError?.message||'';renderSaveIndicator();};
 const call=createToolClient(transport,Promise.resolve().then(()=>ready),model.errorMessage);
 let displayData=null;const controller=createUiController({call,ids,model,interactionMetric:name=>diagnostics?.increment(name),timing:diagnostics?{now:()=>window.performance.now(),record:(phase,duration)=>diagnostics.record(phase,duration)}:undefined,timers:{schedule:(fn,ms)=>window.setTimeout(fn,ms),cancel:handle=>window.clearTimeout(handle)},view:{remapCreated:(from,to)=>{if(editorId===from)editorId=to;controller.dispatch({type:'interaction.remap',from,to});},message,render:()=>render(),closeReview:()=>{},review:()=>{},focusCreated:id=>{setView('creationReveal',{id,view:state.interaction.view.navigation.view});setView('collapsed',model.catalogTree.reveal(displayData,state.interaction.view.navigation.view,id,state.interaction.view.collapsed));render();selectEditor(id);}}});const state=controller.state;
 function setView(field,value){controller.dispatch({type:'view.set',field,value});}
 function showMove(open){setView('moveChooserOpen',open);el('moveChooser').hidden=!open;}
 function setMovePlacement(value){setView('movePlacement',value);el('movePlacement').value=value;}
 function setMoveDestination(value){setView('moveDestination',value);el('moveDestination').value=value;}
 function showCatalog(open){setView('catalogComposerOpen',open);el('catalogComposer').hidden=!open;}
 function setCatalogName(value){setView('catalogName',value);el('catalogName').value=value;}
 const bridge=createDisplayBridge(transport,model,renderDisplay);const unsubscribeSnapshot=transport.subscribe(controller.accept);
 const fields={title:el('editTitle'),notes:el('editNotes'),flagged:el('editFlag'),due_at:el('editDue'),dueTime:el('dueTime'),deferDate:el('deferDate'),deferUntil:el('deferUntil')};
 for(const [field,input] of Object.entries(fields)){
  input.addEventListener(field==='flagged'||input.type==='checkbox'||input.tagName==='SELECT'?'change':'input',()=>updateField(field));
  input.addEventListener('blur',event=>{if(state.transients[editorId]&&event.relatedTarget?.closest('.add-split'))return;if(!state.interaction.composition)controller.flush(editorId);});
  input.addEventListener('compositionstart',()=>{compositionInput=input;controller.dispatch({type:'composition.begin',key:editorId,field});controller.composing(editorId,true);renderSaveIndicator();});
  input.addEventListener('compositionend',()=>{const original=state.interaction.composition;if(!original)return;controller.dispatch({type:'composition.end'});compositionInput=null;updateField(field,original.key);controller.composing(original.key,false);resumeComposition(original.deferred);});
 }
 function updateField(field,target=editorId){if(!target)return;if(['due_at','dueTime','deferDate','deferUntil'].includes(field)){updateDefer(field,target);return;}const input=fields[field];const value=field==='flagged'?input.checked:field==='order'?(input.value===''?NaN:Number(input.value)):['parent_id','due_at'].includes(field)?input.value||null:input.value;const patch={[field]:value};if((field==='due_at'||field==='deferUntil'||field==='deferDate')&&input.validity.badInput){controller.dispatch({type:'date.error',id:target,field,message:'Finish choosing the date and time.'});controller.editDraft(target,{[field]:'Incomplete date/time'});controller.dispatch({type:'field.invalid',id:target,field:field==='due_at'?'due_at':'deferUntil',message:'Finish choosing the date and time.'});renderEditorFeedback();return;}if(field==='due_at'||field==='deferUntil'){const resolved=model.dateInput.resolve(value,zonedLocal);if(resolved.error){controller.dispatch({type:'date.error',id:target,field,message:resolved.error});controller.editDraft(target,{[field]:value});controller.dispatch({type:'field.invalid',id:target,field:field==='due_at'?'due_at':'deferUntil',message:resolved.error});renderEditorFeedback();return;}controller.dispatch({type:'date.error',id:target,field,message:null});patch[field]=field==='deferUntil'?resolved.value||'':resolved.value;}if(field==='deferDate')patch.timezone=zone();controller.editDraft(target,patch);if(!state.interaction.composition&&(input.type==='checkbox'||input.tagName==='SELECT'))controller.flush(target);renderEditorFeedback();}
 function renderClock(input){const tail=input.parentElement.querySelector('.clock-tail');if(tail){tail.textContent=model.dateInput.clockMask(input.value);tail.style.setProperty('--clock-length',String(input.value.length));}}
 function updateDefer(field,target){const draft=state.drafts[target];if(!draft||state.interaction.composition)return;const due=field==='due_at'||field==='dueTime',key=due?'due_at':'deferUntil',pairs=due?state.interaction.view.duePairs:state.interaction.view.deferPairs,part=field==='deferDate'||field==='due_at'?'date':'time',input=fields[field],raw=input.value,current=pairs[target]||model.dateInput.pair(draft[key],zonedLocal),next=model.dateInput.editPair(current,part,raw,input.validity.badInput,zonedLocal);controller.dispatch({type:'date.pair',id:target,kind:due?'due':'defer',pair:next});if(part==='time'&&next.time!==raw){const start=input.selectionStart,end=input.selectionEnd,position=at=>{const count=raw.slice(0,at).replace(/:/g,'').length;let seen=0;for(let i=0;i<next.time.length;i++){if(next.time[i]!==':')seen++;if(seen===count)return i+1;}return next.time.length;};input.value=next.time;input.setSelectionRange(start===0?0:position(start),end===0?0:position(end));}if(part==='time')renderClock(input);if(next.error){controller.dispatch({type:'date.error',id:target,field:key,message:next.error});controller.editDraft(target,{[key]:'Incomplete date/time'});controller.dispatch({type:'field.invalid',id:target,field:key,message:next.error});}else{controller.dispatch({type:'date.error',id:target,field:key,message:null});controller.editDraft(target,{[key]:due?next.value||null:next.value});}renderEditorFeedback();}
 function renderSaveIndicator(){const feedback=model.saveStatus.project(state,{composing:Boolean(state.interaction.composition),pending:state.interaction.view.catalogComposerOpen&&Boolean(state.interaction.view.catalogName),errors:Object.values(state.interaction.view.dateErrors).some(errors=>Object.values(errors).some(Boolean))||Object.values(state.drafts).some(draft=>Object.keys(model.autosave.validation(draft)).length)||Object.values(state.catalogDrafts).some(draft=>Object.keys(model.catalogDrafts.validation(draft)).length)});const node=el('refresh');let visible=el('saveFeedback');if(!visible){visible=document.createElement('span');visible.id='saveFeedback';visible.setAttribute('aria-hidden','true');Object.assign(visible.style,{fontSize:'11px',lineHeight:'1.25',maxWidth:'12ch',textAlign:'right'});node.before(visible);}visible.hidden=!feedback.visibleLabel;if(visible.textContent!==feedback.visibleLabel)visible.textContent=feedback.visibleLabel;visible.style.color=feedback.attention?'var(--warning)':'var(--muted)';node.dataset.saving=String(state.saving);node.setAttribute('aria-busy',String(state.saving));if(node.dataset.state!==feedback.kind){node.dataset.state=feedback.kind;const icon=document.createElement('span');icon.innerHTML=model.iconSvg(feedback.icon);node.querySelector('svg').replaceWith(icon.firstElementChild);el('refreshStatus').textContent=feedback.label;node.title='Refresh · '+feedback.label;}}
 function selectEditor(id){controller.dispatch({type:'view.selection',catalog:null});closePickers(false);flushCatalogInspector();if(state.interaction.composition){controller.dispatch({type:'composition.defer',intent:{kind:'select-action',id}});return;}if(editorId!==id&&!state.interaction.composition)controller.flush(editorId);if(!outlineEntries.some(e=>e.key===state.interaction.selection.active&&e.id===id))controller.dispatch({type:'occurrence.activate',key:outlineEntries.find(e=>e.kind==='action'&&e.id===id)?.key||id});controller.dispatch({type:'selection.action',id});fields.title.focus({preventScroll:true});if(window.matchMedia?.('(max-width:850px)').matches)editor.scrollIntoView?.({block:'start',behavior:'auto'});}
 function button(text,icon,fn){const b=document.createElement('button');b.type='button';b.innerHTML=model.iconSvg(icon);const label=document.createElement('span');label.textContent=text;b.append(label);b.onclick=fn;return b;}
 function format(time){if(!time)return '';try{return new window.Date(time).toLocaleString('en-US')+' '+zone();}catch{return String(time);}}
 function restoreFocus(key){if(!key)return;const candidates=[...document.querySelectorAll('[data-focus-key]')];candidates.find(node=>node.dataset.focusKey===key)?.focus({preventScroll:true});}
 function render(){
  diagnostics?.increment('list.render');
  displayData=model.transient.overlay(state.data,state.transients,state.drafts,state.catalogDrafts);
  const focused=document.activeElement;const focusKey=focused?.dataset?.focusKey;
  renderSaveIndicator();if(!displayData)return;updateIndexes();
  const catalogEffects=controller.acknowledgeCatalogView(displayData[state.catalogCreated?.type==='project'?'projects':'tags']||[],el('catalogName').value);if(catalogEffects.hideComposer)showCatalog(false);if(catalogEffects.focusCatalog)closePickers(false);const presentation=model.navigation.present(displayData,state.interaction.view.navigation);const tree=state.interaction.view.navigation.view==='projects'||state.interaction.view.navigation.view==='tags';outlineEntries=tree?model.catalogTree.outline(displayData,state.interaction.view.navigation.view,model.navigation.displayFilter(state.interaction.view.navigation),state.interaction.view.collapsed,state.interaction.view.creationReveal?.view===state.interaction.view.navigation.view?state.interaction.view.creationReveal.id:null):presentation.actions.map(action=>({key:action.id,kind:'action',id:action.id,action,level:Math.min(3,model.movement.depth(action.id,movementIndex)),catalogId:null}));if(!tree&&state.interaction.view.creationReveal?.view===state.interaction.view.navigation.view&&!outlineEntries.some(e=>e.id===state.interaction.view.creationReveal.id)){const action=displayData.actions.find(a=>a.id===state.interaction.view.creationReveal.id);if(action)outlineEntries.push({key:action.id,kind:'action',id:action.id,action,level:Math.min(3,model.movement.depth(action.id,movementIndex)),catalogId:null});}outlineByKey=new Map(outlineEntries.map(entry=>[entry.key,entry]));const actions=outlineEntries.filter(entry=>entry.kind==='action').map(entry=>entry.action),visibleActionIds=new Set(actions.map(action=>action.id)),occurrenceSet=new Set(state.interaction.selection.keys);const selected=model.editorSelection(state.selectedId,state.drafts,displayData.actions.map(a=>a.id),actions.map(a=>a.id));
  document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('selected',b.dataset.view===state.interaction.view.navigation.view);b.setAttribute('aria-checked',String(b.dataset.view===state.interaction.view.navigation.view));b.tabIndex=b.dataset.view===state.interaction.view.navigation.view?0:-1;});
  renderNavigation(presentation);el('scopeTitle').textContent=tree?(state.interaction.view.navigation.view==='projects'?'Projects':'Tags'):presentation.heading;el('scopeCount').textContent=String(new Set(actions.map(a=>a.id)).size);const actionList=el('actions'),stableGesture=Boolean(gesture),desiredRows=[],nextRows=new Map(),nextSignatures=new Map();actionList.setAttribute('role',tree?'tree':'list');let rowContentChanged=false;
  if(!stableGesture)for(const entry of outlineEntries){const signature=rowSignature(entry,tree,visibleActionIds,occurrenceSet),existing=rowNodes.get(entry.key);if(existing&&rowSignatures.get(entry.key)===signature){desiredRows.push(existing);nextRows.set(entry.key,existing);nextSignatures.set(entry.key,signature);continue;}if(entry.kind!=='action'){const next=renderCatalogRow(entry),row=existing?patchRow(existing,next):next;desiredRows.push(row);nextRows.set(entry.key,row);nextSignatures.set(entry.key,signature);rowContentChanged=true;continue;}const action=entry.action;const row=document.createElement('div');row.className='action-row';row.dataset.actionId=action.id;row.dataset.occurrenceKey=entry.key;row.draggable=true;row.ondragstart=event=>beginNativeDrag(event,action.id,entry.key);row.setAttribute('role','treeitem');row.setAttribute('aria-level',String(entry.level+1));row.setAttribute('aria-selected',String(occurrenceSet.has(entry.key)));row.classList.toggle('selected',state.interaction.selection.active===entry.key&&state.inspector?.kind==='action');row.classList.toggle('batch-selected',occurrenceSet.has(entry.key));row.style.setProperty('--depth',String(entry.level));
   const complete=button(action.status==='completed'?'Completed':'Mark complete',action.status==='completed'?'checked':'circle',()=>controller.direct('complete',{id:action.id}));complete.className='complete icon-button';complete.setAttribute('role','checkbox');complete.setAttribute('aria-checked',String(action.status==='completed'));complete.setAttribute('aria-label',`${action.status==='completed'?'Completed':'Mark complete'}: ${model.displayTitle(action.title)}`);complete.dataset.mutation='true';complete.disabled=action.status==='completed'||model.mutationBlocked(state.busy,state.unknown);complete.dataset.focusKey='complete:'+entry.key;
   const select=button(model.displayTitle(state.drafts[action.id]?.title??action.title),'chevron',()=>controller.selectAction(action.id));select.className='action-select';select.classList.toggle('untitled',action.title==='');select.onclick=event=>{if(suppressRowClick){suppressRowClick=false;return;}toggleSelection(action.id,event.shiftKey,entry.key);if(!event.shiftKey){controller.dispatch({type:'occurrence.activate',key:entry.key});if(tree)controller.dispatch({type:'view.navigation',patch:{classificationId:entry.catalogId||(state.interaction.view.navigation.view==='projects'?'unassigned':'untagged')}});selectEditor(action.id);}};select.onkeydown=event=>{if(!event.shiftKey&&['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();focusOutline(entry.key,event.key==='ArrowDown'?1:-1);}if(event.shiftKey&&['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();const visible=outlineEntries.filter(e=>e.kind==='action'),index=visible.findIndex(e=>e.key===entry.key),next=visible[index+(event.key==='ArrowDown'?1:-1)];if(next){toggleSelection(next.id,true,next.key);document.querySelector('[data-occurrence-key="'+next.key+'"] .action-select')?.focus();}}};select.setAttribute('aria-pressed',String(state.interaction.selection.active===entry.key&&state.inspector?.kind==='action'));select.dataset.focusKey='select:'+entry.key;
   const labels=document.createElement('div');labels.className='badges';if(action.parent_id&&(tree?!entry.parentKey?.endsWith(':action:'+action.parent_id):!visibleActionIds.has(action.parent_id))){const parent=actionIndex.byId.get(action.parent_id);if(parent)badge(labels,'In '+model.displayTitle(parent.title));}if(action.status==='on-hold')badge(labels,'On hold','waiting');if(action.status==='dropped')badge(labels,'Dropped');if(action.status==='completed')badge(labels,'Completed');if(action.defer_reasons?.length)badge(labels,'Later');if(action.due_at)badge(labels,'Due '+format(action.due_at));if(action.project_path)badge(labels,action.project_path);if(action.tags?.length)badge(labels,action.tags.map(tag=>tag.path||tag.name).join(', '));
   const content=document.createElement('div');content.className='row-content';content.append(select,labels);
   const flag=button(action.flagged?'Remove flag':'Flag action','flagged',()=>{controller.editDraft(action.id,{flagged:!(state.drafts[action.id]?.flagged??action.flagged)});controller.flush(action.id);});flag.className='flag icon-button';flag.setAttribute('aria-label',`${action.flagged?'Remove flag':'Flag action'}: ${model.displayTitle(action.title)}`);flag.setAttribute('aria-pressed',String(action.flagged));flag.dataset.mutation='true';flag.dataset.focusKey='flag:'+entry.key;const grip=button('Move action','grip',()=>{});grip.className='drag-handle icon-button';grip.setAttribute('aria-label','Move: '+model.displayTitle(action.title));grip.dataset.actionId=action.id;grip.dataset.focusKey='grip:'+entry.key;grip.onpointerdown=event=>beginPointer(event,action.id,entry.key);grip.onkeydown=event=>{if(event.key===' '||event.key==='Enter'){event.preventDefault();if(!state.interaction.selection.keys.includes(entry.key)){controller.dispatch({type:'occurrence.replace',keys:[entry.key],ids:[action.id]});}openMove(grip);}};bindPointerDown(row,event=>{if(event.pointerType==='touch'&&!event.target.closest('.drag-handle'))return;if(event.target.closest('.complete,.flag,.drag-handle'))return;beginPointer(event,action.id,entry.key);});row.onclick=event=>{if(event.target.closest('button'))return;if(suppressRowClick){suppressRowClick=false;return;}toggleSelection(action.id,event.shiftKey,entry.key);if(!event.shiftKey){controller.dispatch({type:'occurrence.activate',key:entry.key});if(tree)controller.dispatch({type:'view.navigation',patch:{classificationId:entry.catalogId||(state.interaction.view.navigation.view==='projects'?'unassigned':'untagged')}});selectEditor(action.id);}};row.append(grip,complete,content,flag);const next=existing?patchRow(existing,row):row;desiredRows.push(next);nextRows.set(entry.key,next);nextSignatures.set(entry.key,signature);rowContentChanged=true;
  }
  if(!stableGesture){if(!actions.length){const label=presentation.unavailable?'Selection unavailable':'No matching actions';if(!emptyRow){emptyRow=document.createElement('div');emptyRow.className='empty';rowContentChanged=true;}if(emptyRow.textContent!==label){emptyRow.textContent=label;rowContentChanged=true;}desiredRows.push(emptyRow);}else emptyRow=null;const structureChanged=reconcileRows(actionList,desiredRows);if(rowContentChanged||structureChanged)invalidateGeometry();rowNodes=nextRows;rowSignatures=nextSignatures;}
  const retainedIds=[...selected.retainedIds];for(const id of [state.retainedActionId,...state.movedActionIds])if(id&&!visibleActionIds.has(id)&&!retainedIds.includes(id))retainedIds.push(id);if(state.createdActionId&&!visibleActionIds.has(state.createdActionId)&&!retainedIds.includes(state.createdActionId))retainedIds.push(state.createdActionId);el('retained').replaceChildren();el('retained').hidden=!retainedIds.length;
  for(const id of retainedIds){const saved=displayData.actions.find(a=>a.id===id),draft=state.drafts[id];const b=button((draft?.dirty?'Unsaved: ':'Open: ')+model.displayTitle(draft?.title??saved?.title),'edit',()=>controller.selectAction(id));b.onclick=()=>selectEditor(id);b.dataset.focusKey='retained:'+id;if(!draft)b.disabled=true;el('retained').append(b);}
  renderEditor(selected);renderCatalogEditor();renderControls();renderSelection(actions);el('fetched').hidden=true;
  if(catalogEffects.focusCatalog)el('catalogEditName').focus({preventScroll:true});
  if(focused&&(!focused.isConnected||document.activeElement===document.body&&focused!==document.body))restoreFocus(focusKey);
 }
 function badge(parent,text,icon){const span=document.createElement('span');span.className='badge'+(icon?' on-hold':'');if(icon)span.innerHTML=model.iconSvg(icon);span.append(document.createTextNode(text));parent.append(span);}
 function setValue(input,value){const next=value==null?'':String(value);if(input.value===next||state.interaction.composition&&input===compositionInput)return;const focused=input===document.activeElement,start=input.selectionStart,end=input.selectionEnd,direction=input.selectionDirection;input.value=next;if(focused&&typeof start==='number')try{input.setSelectionRange(Math.min(start,next.length),Math.min(end,next.length),direction);}catch{}}
 function renderEditor(selection){
  const id=state.selectedId,draft=id?state.drafts[id]:null;editor.hidden=!draft;document.querySelector('.workspace').classList.toggle('has-editor',Boolean(draft));el('editorPlaceholder').hidden=Boolean(draft);if(!draft)return;
  editorId=id;for(const field of Object.keys(state.interaction.view.dateErrors[id]||{}))if(!Object.hasOwn(draft.patch,field))controller.dispatch({type:'date.error',id,field,message:null});const action=displayData.actions.find(a=>a.id===id);el('editorHeading').textContent='Action details';el('targetMissing').hidden=Boolean(action);el('targetMissing').textContent='This action is no longer available. Your unsaved changes are retained. Refresh before saving.';
  for(const [field,input] of Object.entries(fields)){if(field==='flagged'){input.checked=draft.flagged;input.setAttribute('aria-pressed',String(draft.flagged));}else if(['due_at','dueTime','deferDate','deferUntil'].includes(field)){const due=field==='due_at'||field==='dueTime',key=due?'due_at':'deferUntil',pairs=due?state.interaction.view.duePairs:state.interaction.view.deferPairs;let pair=pairs[id];if(!pair||!Object.hasOwn(draft.patch,key)){pair=model.dateInput.pair(draft[key],zonedLocal);controller.dispatch({type:'date.pair',id,kind:due?'due':'defer',pair});}const part=field==='due_at'||field==='deferDate'?'date':'time';if(!(part==='date'?pair.badDate:pair.badTime))setValue(input,pair[part]);if(part==='time')renderClock(input);}else setValue(input,draft[field]);}
  for(const choice of document.querySelectorAll('[data-status]'))choice.setAttribute('aria-pressed',String(choice.dataset.status===draft.status));renderClassification(id,draft);
  el('savedCompare').textContent=state.conflicts[id]?.length&&action?state.conflicts[id].map(field=>{const value=model.autosave.savedValue(action,field);const label={tag_ids:'Tags',project_id:'Project',title:'Title',notes:'Notes',status:'Status',due_at:'Due',deferDate:'Defer',deferUntil:'Defer',flagged:'Flag',order:'Order',parent_id:'Parent action'}[field]||field;const display=field==='project_id'?(displayData.projects||[]).find(p=>p.id===value)?.path||(displayData.projects||[]).find(p=>p.id===value)?.name||'Unassigned':field==='tag_ids'?(value||[]).map(id=>(displayData.tags||[]).find(tag=>tag.id===id)?.path||(displayData.tags||[]).find(tag=>tag.id===id)?.name||'Unavailable tag').join(', '):value;return 'Saved '+label+': '+(display==null||display===''?'Empty':String(display));}).join('\n'):'';el('editorLifecycle').textContent=action?.status==='on-hold'?'On hold':action?.status==='completed'?'Completed':action?.status==='dropped'?'Dropped':'Active';
  el('dateSummary').textContent=[...(action?.defer_reasons||[]).filter(r=>r.ancestor).map(r=>(r.ancestor?'Parent '+model.displayTitle(r.title):'This action')+' · Deferred until: '+format(r.until))].filter(Boolean).join(' / ');
  el('releaseControls').replaceChildren();for(const r of action?.defer_reasons||[])el('releaseControls').append(button(r.ancestor?'Parent '+model.displayTitle(r.title)+' · Clear Defer':'Clear Defer','deferred',()=>controller.direct('release',{id:r.id})));
  editor.dataset.targetAvailable=String(selection.targetAvailable);renderEditorFeedback();
 }
 function fieldError(id,controls,text,invalid=controls){const node=el(id);node.textContent=text||'';node.hidden=!text;for(const control of controls){const input=el(control),bad=Boolean(text)&&invalid.includes(control);input.setAttribute('aria-invalid',String(bad));const descriptions=(input.getAttribute('aria-describedby')||'').split(' ').filter(value=>value&&value!==id);if(bad)descriptions.push(id);if(descriptions.length)input.setAttribute('aria-describedby',descriptions.join(' '));else input.removeAttribute('aria-describedby');}}
 function renderEditorFeedback(){el('discardTemporaryAction').hidden=!state.transients[editorId];const id=editorId,draft=state.drafts[id],conflict=state.conflicts[id]?.length,errors=draft?model.autosave.validation(draft):{};renderSaveIndicator();fieldError('titleError',['editTitle'],errors.title);fieldError('notesError',['editNotes'],errors.notes);for(const [key,errorId,controls,pairs] of [['due_at','dueError',['editDue','dueTime'],state.interaction.view.duePairs],['deferUntil','deferError',['deferDate','deferUntil'],state.interaction.view.deferPairs]]){const pair=pairs[id],feedback=pair?model.dateInput.feedback(pair):null,text=state.interaction.view.dateErrors[id]?.[key]||errors[key]||'';const invalid=feedback?.message?controls.filter((_,index)=>index===0?feedback.date:feedback.time):controls;fieldError(errorId,controls,text,invalid);}const fieldMessages=[...Object.values(errors),...Object.values(state.interaction.view.dateErrors[id]||{})],error=state.saveErrors[id],inline=Boolean(error)&&fieldMessages.includes(error);el('saveProblem').hidden=!conflict&&(!error||inline);el('saveProblemText').textContent=conflict?'This action changed elsewhere. Choose which edits to keep.':inline?'':error||'';el('useMine').hidden=!conflict;el('useSaved').hidden=!conflict;}

 function creationObject(){const target=state.inspector;if(!target)return null;if(target.kind==='action'){const entry=outlineEntries.find(e=>e.kind==='action'&&e.id===target.id&&e.key===state.interaction.selection.active);return entry?{kind:'action',id:entry.id,catalogId:entry.catalogId}:null;}return state.interaction.view.activeCatalogSelection===target.kind+':'+target.id&&outlineEntries.some(e=>e.kind===target.kind&&e.id===target.id)&&state.interaction.view.navigation.classificationId===target.id?target:null;}
 function renderControls(){const blocked=model.mutationBlocked(state.busy,state.unknown)||state.recoveryRequired;document.querySelectorAll('[data-mutation]').forEach(node=>setDisabled(node,blocked||(node.classList.contains('complete')&&node.getAttribute('aria-checked')==='true')));document.querySelectorAll('#editor input,#editor textarea,#editor select,#statusIcons button').forEach(node=>node.disabled=editor.dataset.targetAvailable==='false');for(const id of ['addMenuProject','addMenuTag','pickerNewProject','pickerNewTag','createCatalog'])el(id).disabled=blocked;for(const id of ['check','retry','refresh'])el(id).disabled=state.busy;el('undo').disabled=blocked||!state.lastOperation;el('undo').hidden=!state.lastOperation;el('unknown').hidden=!state.unknown;el('editFlag').disabled=editor.dataset.targetAvailable==='false';const creation=displayData?model.navigation.creationContext({...displayData,actions:displayData.actions.map(action=>({...action,project_id:state.drafts[action.id]?state.drafts[action.id].project_id:action.project_id}))},state.interaction.view.navigation,creationObject()):null;setDisabled(el('addAction'),blocked||!creation?.allowed);el('addMenuAction').disabled=el('addAction').disabled;renderEditorFeedback();}
 function renderNavigation(presentation){
  el('currentViewIcon').innerHTML=model.iconSvg(state.interaction.view.navigation.view==='perspective'?'perspective':state.interaction.view.navigation.view);const perspectives=displayData.perspectives||[];
  const buttons=el('perspectiveButtons');buttons.replaceChildren();el('perspectiveNav').hidden=!perspectives.length&&state.interaction.view.navigation.view!=='perspective';for(const perspective of perspectives){const b=button(perspective.name,'perspective',()=>{});b.dataset.focusKey='perspective:'+perspective.id;b.classList.toggle('selected',state.interaction.view.navigation.view==='perspective'&&state.interaction.view.navigation.perspectiveId===perspective.id);b.setAttribute('role','menuitemradio');b.setAttribute('aria-checked',String(state.interaction.view.navigation.view==='perspective'&&state.interaction.view.navigation.perspectiveId===perspective.id));b.tabIndex=state.interaction.view.navigation.view==='perspective'&&state.interaction.view.navigation.perspectiveId===perspective.id?0:-1;const marker=document.createElement('span');marker.className='menu-check';marker.innerHTML=model.iconSvg('tick');b.append(marker);b.onclick=()=>navigate({view:'perspective',perspectiveId:perspective.id});buttons.append(b);}
  if(state.interaction.view.navigation.view==='perspective'&&!perspectives.some(p=>p.id===state.interaction.view.navigation.perspectiveId)){const unavailable=button('Unavailable perspective','perspective',()=>{});unavailable.disabled=true;unavailable.setAttribute('role','menuitemradio');unavailable.setAttribute('aria-checked','true');buttons.append(unavailable);}
  const classification=state.interaction.view.navigation.view==='projects'||state.interaction.view.navigation.view==='tags';const choices=model.navigation.displayOptions(state.interaction.view.navigation);document.querySelectorAll('[data-display-choice]').forEach(b=>{const choice=b.dataset.displayChoice;b.hidden=!choices.includes(choice);b.setAttribute('aria-checked',String(choice==='deferred'?state.interaction.view.navigation.includeDeferred:state.interaction.view.navigation.statuses.includes(choice)));});el('displayMenuToggle').hidden=!choices.length;el('scopeSummary').textContent='';el('scopeSummary').hidden=true;el('scopeDescription').hidden=classification||!presentation.description;el('scopeDescription').textContent=classification?'':presentation.description;
 }
 function navigate(patch,keepDisplayOpen=false){controller.dispatch({type:'view.selection',catalog:null});const menuOrigin=state.interaction.view.headerMenu;controller.dispatch({type:'composition.defer',intent:null});setView('creationReveal',null);if(!keepDisplayOpen)closeHeaderMenus(false);closePickers(false);flushInspector();if(patch.view)controller.dispatch({type:'occurrence.clear'});showMove(false);cancelPointer('');if(!state.interaction.composition)controller.flush(editorId);controller.dispatch({type:'view.navigation',patch});controller.selectView(state.interaction.view.navigation.view);if(menuOrigin&&!keepDisplayOpen)el(menuOrigin==='navigation'?'navigationToggle':'displayMenuToggle').focus({preventScroll:true});}
 function focusOutline(key,offset){const next=outlineEntries[outlineEntries.findIndex(e=>e.key===key)+offset];if(next)restoreFocus(next.kind==='action'?'select:'+next.key:next.key);}
 function flushCatalogInspector(){const target=state.inspector;if(target&&target.kind!=='action')controller.flushCatalog(target.kind+':'+target.id);}
 function flushInspector(){flushCatalogInspector();if(!state.interaction.composition)controller.flush(editorId);}
 function selectCatalog(kind,id){controller.dispatch({type:'view.selection',catalog:kind+':'+id});closePickers(false);if(state.interaction.composition){controller.dispatch({type:'composition.defer',intent:{kind:'select-catalog',catalogKind:kind,id}});return;}flushInspector();controller.dispatch({type:'occurrence.clear'});controller.dispatch({type:'view.navigation',patch:{classificationId:id}});controller.selectCatalog(kind,id);el('catalogEditName').focus({preventScroll:true});}
 function renderCatalogRow(entry){const row=document.createElement('div');row.className='catalog-row';row.dataset.catalogKind=entry.kind;row.dataset.catalogId=entry.id;row.dataset.outlineKey=entry.key;row.setAttribute('aria-selected',String(state.inspector?.kind===entry.kind&&state.inspector?.id===entry.id));row.style.setProperty('--depth',String(entry.level));row.setAttribute('role','treeitem');row.setAttribute('aria-level',String(entry.level+1));row.classList.toggle('selected',state.inspector?.kind===entry.kind&&state.inspector?.id===entry.id);const toggle=button(state.interaction.view.collapsed.includes(entry.key)?'Expand':'Collapse','chevron',()=>{controller.dispatch({type:'view.collapse',key:entry.key});controller.dispatch({type:'occurrence.clear'});render();});toggle.className='tree-toggle';toggle.setAttribute('aria-label',(state.interaction.view.collapsed.includes(entry.key)?'Expand ':'Collapse ')+entry.label);toggle.setAttribute('aria-expanded',String(!state.interaction.view.collapsed.includes(entry.key)));toggle.hidden=!entry.expandable;toggle.dataset.focusKey='expand:'+entry.key;const select=button((state.catalogDrafts[entry.key]?.name||entry.label),entry.kind==='project'?'projects':entry.kind==='tag'?'tags':'normal',()=>{if(entry.kind==='group'){flushInspector();controller.dispatch({type:'view.navigation',patch:{classificationId:entry.id}});controller.selectAction(null);}else selectCatalog(entry.kind,entry.id);});select.className='catalog-select';select.dataset.focusKey=entry.key;select.onkeydown=event=>{if(entry.kind!=='group'&&event.key===' '){event.preventDefault();setView('catalogMoveSource',{kind:entry.kind,id:entry.id});setMovePlacement('inside');openMove(select);return;}if(['ArrowUp','ArrowDown'].includes(event.key)&&!event.shiftKey){event.preventDefault();focusOutline(entry.key,event.key==='ArrowDown'?1:-1);}if(['ArrowLeft','ArrowRight'].includes(event.key)&&entry.expandable){event.preventDefault();const open=event.key==='ArrowRight';controller.dispatch({type:'view.collapse',key:entry.key,open});controller.dispatch({type:'occurrence.clear'});render();}};if(entry.kind!=='group'){row.draggable=true;bindPointerDown(row,event=>{if(event.target.closest('.tree-toggle')||event.button!==0&&event.pointerType!=='touch')return;beginPointer(event,entry.id,entry.key,entry.kind);});row.ondragstart=event=>beginNativeDrag(event,entry.id,entry.key);}row.append(toggle,select);return row;}
 function renderCatalogEditor(){el('discardTemporaryCatalog').hidden=!state.transients[state.inspector?.id];const target=state.inspector,active=target&&target.kind!=='action',panel=el('catalogEditor');panel.hidden=!active;if(!active)return;editor.hidden=true;document.querySelector('.workspace').classList.add('has-editor');el('editorPlaceholder').hidden=true;const key=target.kind+':'+target.id,draft=state.catalogDrafts[key],nodes=displayData[target.kind==='project'?'projects':'tags']||[],record=nodes.find(n=>n.id===target.id);el('catalogHeading').textContent=target.kind==='project'?'Project':'Tag';el('catalogMissing').hidden=Boolean(record);el('catalogMissing').textContent='This '+target.kind+' is no longer available. Your edits are retained.';el('catalogEditName').disabled=!record;el('catalogEditDescription').disabled=!record;if(draft){setValue(el('catalogEditName'),draft.name);setValue(el('catalogEditDescription'),draft.description);}el('catalogParent').textContent=record?.parent_id?'Parent: '+(nodes.find(n=>n.id===record.parent_id)?.path||nodes.find(n=>n.id===record.parent_id)?.name||'Unavailable'):'Top level';const conflicts=state.catalogConflicts[key]||[],error=state.catalogErrors[key],errors=draft?model.catalogDrafts.validation(draft):{};fieldError('catalogNameError',['catalogEditName'],errors.name);fieldError('catalogDescriptionError',['catalogEditDescription'],errors.description);const inline=Boolean(error)&&Object.values(errors).includes(error);el('catalogProblem').hidden=!conflicts.length&&(!error||inline);el('catalogProblemText').textContent=conflicts.length?'This '+target.kind+' changed elsewhere. Choose which edits to keep.':error||'';el('catalogSavedCompare').textContent=conflicts.map(field=>'Saved '+field+': '+(record?.[field]||'Empty')).join('\n');el('catalogUseMine').hidden=!conflicts.length;el('catalogUseSaved').hidden=!conflicts.length;el('catalogRetry').hidden=!error||Boolean(conflicts.length)||Boolean(state.unknown);el('catalogRetry').disabled=state.busy||state.recoveryRequired;}

 function toggleSelection(id,range,key=id){controller.dispatch({type:'occurrence.range',key,range,entries:outlineEntries});render();}
 function renderSelection(actions){el('chooseMove').hidden=!state.moveIssue;if(state.moveIssue)setMoveStatus(state.moveIssue.reason);if(state.classificationIssue)setMoveStatus(state.classificationIssue.reason);if(!state.interaction.gesture?.active)el('selectionBar').hidden=!state.interaction.selection.ids.length;el('selectionCount').textContent=state.interaction.selection.keys.length!==state.interaction.selection.ids.length?state.interaction.selection.keys.length+' rows · '+state.interaction.selection.ids.length+' actions':state.interaction.selection.ids.length+' selected';if(state.interaction.view.moveChooserOpen)renderMoveChooser(actions);}

 function openMove(origin){moveOrigin=origin?.dataset?.focusKey||document.activeElement?.dataset?.focusKey||null;showMove(true);render();el('movePlacement').focus();}
 function closeMove(){setView('catalogMoveSource',null);showMove(false);const origin=moveOrigin&&Array.from(document.querySelectorAll('[data-focus-key]')).find(node=>node.dataset.focusKey===moveOrigin);(origin||el('openMove')).focus({preventScroll:true});}
 function renderMoveChooser(actions){if(state.interaction.view.catalogMoveSource){const source=state.interaction.view.catalogMoveSource,nodes=displayData[source.kind==='project'?'projects':'tags']||[],destination=el('moveDestination'),previous=state.interaction.view.moveDestination;destination.replaceChildren();for(const node of nodes)destination.add(new window.Option(node.path||node.name,node.id));if([...destination.options].some(o=>o.value===previous))destination.value=previous;setView('moveDestination',destination.value);for(const option of el('movePlacement').options)option.hidden=false;const placement=state.interaction.view.movePlacement;el('moveDestinationLabel').hidden=placement==='root';const invalid=placement!=='root'&&model.treeDrop.chain(nodes,destination.value).some(n=>n.id===source.id);el('applyMove').disabled=invalid||state.busy||Boolean(state.unknown)||state.recoveryRequired;setMoveStatus(invalid?'Choose a destination outside this subtree.':'');return;}for(const option of el('movePlacement').options)option.hidden=false;const destination=el('moveDestination'),previous=state.interaction.view.moveDestination;destination.replaceChildren();for(const action of actions.filter((a,index)=>actions.findIndex(b=>b.id===a.id)===index))destination.add(new window.Option(model.displayTitle(state.drafts[action.id]?.title??action.title),action.id));if([...destination.options].some(option=>option.value===previous))destination.value=previous;setView('moveDestination',destination.value);const placement=state.interaction.view.movePlacement;el('moveDestinationLabel').hidden=placement==='root';const intent=count('movement.intent',()=>model.movement.intent(displayData.actions,state.interaction.selection.ids,placement,destination.value,movementIndex));el('applyMove').disabled=!intent.allowed||state.busy||Boolean(state.unknown)||state.recoveryRequired;setMoveStatus(intent.reason);}
 function commitMove(ids,placement,anchor){const intent=count('movement.intent',()=>model.movement.intent(displayData.actions,ids,placement,anchor,movementIndex));if(!intent.allowed){setMoveStatus(intent.reason);return;}if(controller.dispatch({type:'gesture.action-move',payload:intent.payload})){showMove(false);setMoveStatus('Moving '+intent.roots.length+' action'+(intent.roots.length===1?'':'s')+'.');}}
 function renderClassification(id,draft){if(state.interaction.view.pickerTarget&&state.interaction.view.pickerTarget!==id)closePickers(false);const project=(displayData.projects||[]).find(item=>item.id===draft.project_id);if(document.activeElement!==el('projectSearch')&&state.interaction.view.pickerOpen!=='project')setValue(el('projectSearch'),draft.project_id?(project?model.catalogTree.label(displayData.projects||[],project.id,'project'):'Unavailable Project'):'');el('projectSearch').placeholder='Unassigned';el('editTags').replaceChildren();for(const tagId of draft.tag_ids){const tag=(displayData.tags||[]).find(item=>item.id===tagId),label=tag?model.catalogTree.label(displayData.tags||[],tag.id,'tag'):'Unavailable Tag';const chip=button(label,'close',()=>{const current=state.drafts[id];if(current){controller.editDraft(id,{tag_ids:current.tag_ids.filter(value=>value!==tagId)});controller.flush(id);}});chip.dataset.focusKey='tag:'+id+':'+tagId;chip.setAttribute('aria-label','Remove Tag: '+label);el('editTags').append(chip);}if(state.interaction.view.pickerOpen==='project'||state.interaction.view.pickerOpen==='tag')renderPickerOptions();}

 function closeHeaderMenus(focus=true){const previous=state.interaction.view.headerMenu;setView('headerMenu',null);for(const kind of ['navigation','display']){el(kind+'Menu').hidden=true;el(kind==='navigation'?'navigationToggle':'displayMenuToggle').setAttribute('aria-expanded','false');}if(focus&&previous)el(previous==='navigation'?'navigationToggle':'displayMenuToggle').focus();}
 function openHeaderMenu(kind){if(state.interaction.view.headerMenu===kind){closeHeaderMenus();return;}closePickers(false);closeHeaderMenus(false);setView('headerMenu',kind);const menu=el(kind+'Menu');menu.hidden=false;el(kind==='navigation'?'navigationToggle':'displayMenuToggle').setAttribute('aria-expanded','true');const items=[...menu.querySelectorAll('[role="menuitemradio"],[role="menuitemcheckbox"]')].filter(node=>!node.disabled&&!node.closest('[hidden]'));const current=items.find(node=>node.getAttribute('aria-checked')==='true')||items[0];items.forEach(item=>item.tabIndex=item===current?0:-1);current?.focus();}
 function headerMenuKey(event){if(event.isComposing)return;const menu=event.currentTarget,items=[...menu.querySelectorAll('[role="menuitemradio"],[role="menuitemcheckbox"]')].filter(node=>!node.disabled&&!node.closest('[hidden]'));const index=items.indexOf(document.activeElement);if([' ','Enter'].includes(event.key)&&document.activeElement?.getAttribute('role')==='menuitemcheckbox'){event.preventDefault();document.activeElement.click();return;}if(event.key==='Escape'){event.preventDefault();closeHeaderMenus();return;}if(event.key==='Tab'){const trigger=state.interaction.view.headerMenu==='navigation'?'navigationToggle':'displayMenuToggle';closeHeaderMenus(false);el(trigger).focus({preventScroll:true});return;}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?items.length-1:(index+(event.key==='ArrowDown'?1:-1)+items.length)%items.length;items.forEach((item,i)=>item.tabIndex=i===next?0:-1);items[next]?.focus();}}
 function createFromHeader(intent){if(intent.kind==='action'){controller.createEmpty(intent.payload);return;}const targetView=intent.kind==='project'?'projects':'tags';if(state.interaction.view.navigation.view!==targetView&&!state.transients[state.inspector?.id])navigate({view:targetView,classificationId:'all'});else{controller.dispatch({type:'view.selection',catalog:null});closeHeaderMenus(false);closePickers(false);if(!state.transients[state.inspector?.id])flushInspector();controller.dispatch({type:'view.navigation',patch:{view:targetView,classificationId:'all'}});setView('activeCatalogSelection',null);}const token=controller.dispatch({type:'catalog.next-token'});controller.dispatch({type:'catalog.submission',token,submission:{type:intent.kind,target:null,parentId:intent.parent,name:'',contextToken:null,navigation:JSON.stringify(state.interaction.view.navigation),direct:true,selectionVersion:state.interaction.view.selectionVersion}});controller.createEmptyCatalog(intent.kind,intent.parent,token);}
 el('navigationToggle').onclick=()=>openHeaderMenu('navigation');el('navigationToggle').onkeydown=event=>{if(event.key==='ArrowDown'){event.preventDefault();openHeaderMenu('navigation');}};el('displayMenuToggle').onclick=()=>openHeaderMenu('display');el('displayMenuToggle').onkeydown=event=>{if(event.key==='ArrowDown'){event.preventDefault();openHeaderMenu('display');}};el('navigationMenu').onkeydown=headerMenuKey;el('displayMenu').onkeydown=headerMenuKey;document.addEventListener('pointerdown',event=>{if(state.interaction.view.headerMenu&&!event.target.closest('.header-navigation,.header-display'))closeHeaderMenus(false);});
 function closePickers(focus=true){const previous=state.interaction.view.pickerOpen;controller.dispatch({type:'picker.close'});for(const id of ['addMenu','projectPicker','tagPicker'])el(id).hidden=true;el('addMenuToggle').setAttribute('aria-expanded','false');el('projectSearch').setAttribute('aria-expanded','false');el('tagPickerToggle').setAttribute('aria-expanded','false');el('tagSearch').setAttribute('aria-expanded','false');if(focus&&previous)el(previous==='add'?'addMenuToggle':previous==='tag'?'tagPickerToggle':'projectSearch').focus();}
 function openPicker(kind){closeHeaderMenus(false);closePickers(false);controller.dispatch({type:'picker.open',kind,target:editorId});el(kind==='add'?'addMenu':kind==='project'?'projectPicker':'tagPicker').hidden=false;el(kind==='add'?'addMenuToggle':kind==='project'?'projectSearch':'tagPickerToggle').setAttribute('aria-expanded','true');if(kind==='project'){renderPickerOptions();}else if(kind==='tag'){el('tagSearch').value='';el('tagSearch').setAttribute('aria-expanded','true');renderPickerOptions();el('tagSearch').focus();}else el('addMenuAction').focus();}
 function pickerItems(){if(state.interaction.view.pickerOpen==='project')return model.picker.search([{id:'',name:'Unassigned'},...(displayData.projects||[])],state.interaction.view.projectQuery);if(state.interaction.view.pickerOpen==='tag')return model.picker.search(displayData.tags||[],state.interaction.view.tagQuery);return [];}
 function renderPickerOptions(){const kind=state.interaction.view.pickerOpen;if(kind!=='project'&&kind!=='tag')return;const list=el(kind==='project'?'projectOptions':'tagOptions'),input=el(kind==='project'?'projectSearch':'tagSearch'),draft=state.drafts[state.interaction.view.pickerTarget];list.replaceChildren();const items=pickerItems();if(state.interaction.view.pickerIndex>=items.length)setView('pickerIndex',items.length-1);items.forEach((item,index)=>{const selected=kind==='project'?(draft?.project_id||'')===item.id:Boolean(draft?.tag_ids.includes(item.id));const option=button(item.id?model.catalogTree.label(displayData[kind==='project'?'projects':'tags']||[],item.id,kind,kind==='project'?projectIndex.byId:tagIndex.byId):item.name,selected?'checked':kind==='project'?'projects':'tags',()=>selectPickerItem(item.id));option.id='picker-'+kind+'-'+(item.id||'unassigned');option.setAttribute('role','option');option.setAttribute('aria-selected',String(selected));option.classList.toggle('picker-active',index===state.interaction.view.pickerIndex);option.dataset.focusKey='picker:'+kind+':'+item.id;option.onmousedown=event=>event.preventDefault();list.append(option);});if(!items.length){const empty=document.createElement('p');empty.textContent='No matches';list.append(empty);}if(state.interaction.view.pickerIndex>=0&&items[state.interaction.view.pickerIndex])input.setAttribute('aria-activedescendant','picker-'+kind+'-'+(items[state.interaction.view.pickerIndex].id||'unassigned'));else input.removeAttribute('aria-activedescendant');}
 function selectPickerItem(id){const kind=state.interaction.view.pickerOpen,target=state.interaction.view.pickerTarget,draft=state.drafts[target];if(!draft)return;if(kind==='project'){controller.editDraft(target,{project_id:id||null});controller.flush(target);closePickers();render();}else if(kind==='tag'){controller.editDraft(target,{tag_ids:(draft.tag_ids.includes(id)?draft.tag_ids.filter(value=>value!==id):[...draft.tag_ids,id]).sort()});controller.flush(target);renderPickerOptions();}}
 function pickerKey(event){if(event.isComposing)return;if(event.key==='Escape'){event.preventDefault();closePickers();return;}let items=pickerItems();if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();if(!state.interaction.view.pickerOpen){openPicker(event.currentTarget.id==='projectSearch'?'project':'tag');items=pickerItems();}controller.dispatch({type:'picker.step',count:items.length,direction:event.key==='ArrowDown'?1:-1});renderPickerOptions();}else if(event.key==='Enter'&&state.interaction.view.pickerIndex>=0&&items[state.interaction.view.pickerIndex]){event.preventDefault();selectPickerItem(items[state.interaction.view.pickerIndex].id);}}

 function clearDrop(){setDropRow(null,'');}
 function measureGeometry(){
  const list=el('actions'),bounds=document.querySelector('.list-panel')?.getBoundingClientRect()||list.getBoundingClientRect(),rows=[];geometryByKey.clear();
  for(const element of list.children){const key=element.dataset.occurrenceKey||element.dataset.outlineKey,entry=key&&outlineByKey.get(key);if(!entry)continue;const rect=element.getBoundingClientRect(),title=element.querySelector('.action-select,.catalog-select')?.getBoundingClientRect();rows.push({kind:entry.kind==='group'?'group':entry.kind,id:entry.id,key,left:rect.left,top:rect.top,bottom:rect.bottom,catalogId:entry.catalogId,last:false,title:title?{left:title.left,right:title.right,top:title.top,bottom:title.bottom}:null,element});}
  if(rows.length)rows[rows.length-1].last=true;geometryCache=rows;geometryBounds={left:bounds.left,right:bounds.right};geometryByKey=new Map(rows.map(row=>[row.key,{element:row.element,...row}]));geometryDirty=false;
 }
 function hitDestination(x,y){
  const pointed=document.elementFromPoint?.(x,y);if(pointed?.closest('#editor,#catalogEditor,.editor-panel,#moveChooser,#catalogComposer,.picker-shell,.popover,#navigationMenu,#displayMenu,[role="dialog"]'))return null;if(geometryDirty)measureGeometry();
  const row=model.treeDrop.hit(geometryCache,geometryBounds,x,y);if(!row)return null;const source=state.interaction.gesture?.kind||'action',snapshot={actions:displayData.actions||[],projects:displayData.projects||[],tags:displayData.tags||[]},index=source==='action'?actionIndex:source==='project'?projectIndex:tagIndex;
  return model.treeDrop.resolve(source,row,x,y,gesture?.startX??x,snapshot,index);
 }
 function cancelPointer(reason){const current=gesture;if(dragFrame!==null){cancelFrame(dragFrame);dragFrame=null;}finishAfterFrame=false;lastDragFrame=0;gesture=null;controller.dispatch({type:'gesture.cancel'});if(current?.pointerId!=null&&current.captureTarget?.hasPointerCapture?.(current.pointerId))try{current.captureTarget.releasePointerCapture(current.pointerId);}catch{}clearDrop();setMoveStatus(reason);}
 function beginPointer(event,id,key=id,kind='action'){
  suppressRowClick=false;if(event.button!==0&&event.pointerType!=='touch')return;if(state.unknown||state.recoveryRequired){setMoveStatus('Check the pending save before moving actions.');return;}
  const keys=kind==='action'&&state.interaction.selection.keys.includes(key)?[...state.interaction.selection.keys]:[key],sources=[...new Set(keys.map(selectedKey=>outlineByKey.get(selectedKey)?.id).filter(Boolean))],captureTarget=event.currentTarget;
  gesture={x:event.clientX,y:event.clientY,startX:event.clientX,startY:event.clientY,pointerId:event.pointerId,captureTarget,native:false};controller.dispatch({type:'gesture.begin',kind,keys,ids:kind==='action'?sources:[id]});
  if(event.pointerId!=null&&captureTarget?.setPointerCapture)try{captureTarget.setPointerCapture(event.pointerId);}catch{}
 }
 function activateGesture(){controller.dispatch({type:'gesture.activate'});const current=state.interaction.gesture;if(current?.kind==='action')controller.dispatch({type:'occurrence.replace',keys:current.keys,ids:current.ids});suppressRowClick=true;renderSelection([]);}
 function beginNativeDrag(event,id,key){if(event.target.closest('.complete,.flag')||state.unknown||state.recoveryRequired){event.preventDefault();return;}if(!gesture)beginPointer({button:0,pointerType:'mouse',clientX:event.clientX,clientY:event.clientY,pointerId:null,currentTarget:null},id,key,outlineByKey.get(key)?.kind||'action');if(!gesture){event.preventDefault();return;}gesture.native=true;activateGesture();event.dataTransfer?.setData('application/x-action-selection','move');if(event.dataTransfer)event.dataTransfer.effectAllowed='move';requestDragFrame();}
 function finishGesture(){
  const current=state.interaction.gesture;if(!current)return;
  const accepted=controller.dispatch({type:'gesture.commit'}),reason=current.issue||(!current.target?'Move canceled.':!accepted?'Choose an available destination.':'');
  cancelPointer(reason);if(accepted){showMove(false);setMoveStatus('Moving '+current.ids.length+' action'+(current.ids.length===1?'':'s')+'.');}window.setTimeout(()=>{suppressRowClick=false;},0);render();
 }
 function showDestination(){
  if(!state.interaction.gesture?.active)return;
  if(state.interaction.gesture.issue){cancelPointer(state.interaction.gesture.issue);render();return;}
  const rawTarget=hitDestination(gesture.x,gesture.y),target=rawTarget?.kind==='classification'?{...rawTarget,kind:rawTarget.catalogKind}:rawTarget;controller.dispatch({type:'gesture.target',target});
  const current=state.interaction.gesture;
  if(current.issue){cancelPointer(current.issue);render();return;}
  if(!current.target){setDropRow(null,'');setMoveStatus('Choose a destination.');return;}
  if(current.kind!=='action'){setDropRow(geometryByKey.get(target.key)?.element,'drop-'+(target.placement==='root'?'after':target.placement));setMoveStatus((target.placement==='root'?'Top level':target.placement==='inside'?'Into':'Insert')+' · level '+target.depth);return;}
  if(target.kind==='project'||target.kind==='tag'){setDropRow(geometryByKey.get(target.key)?.element,'drop-target');const catalog=(displayData[target.kind==='project'?'projects':'tags']||[]).find(item=>item.id===target.id);setMoveStatus((target.kind==='project'?'Set Project: ':'Add Tag: ')+(catalog?.path||catalog?.name||'Unassigned'));return;}
  if(!current.intent?.allowed){setDropRow(null,'');setMoveStatus(current.intent?.reason||'Choose an available destination.');return;}
  setDropRow(geometryByKey.get(target.key)?.element,'drop-'+(target.placement==='root'?'after':target.placement));const name=target.anchor?model.displayTitle(movementIndex.byId.get(target.anchor)?.title):'Top level';setMoveStatus(current.intent.roots.length+' action'+(current.intent.roots.length===1?'':'s')+' · '+({before:'Before',after:'After',inside:'Into',root:'At'}[target.placement])+' '+name);
 }
 function requestDragFrame(){if(dragFrame===null)dragFrame=requestFrame(flushDragFrame);}
 function flushDragFrame(timestamp){
  dragFrame=null;if(!state.interaction.gesture?.active)return;
  const elapsed=lastDragFrame?Math.min(32,timestamp-lastDragFrame):16;lastDragFrame=timestamp;
  const viewport=window.innerHeight||document.documentElement.clientHeight,direction=gesture.y<64?-1:gesture.y>viewport-64?1:0;
  let scrolled=false;
  if(direction&&!finishAfterFrame){const before=window.scrollY;window.scrollBy?.(0,direction*Math.min(18,Math.max(1,elapsed*.75)));scrolled=window.scrollY!==before;if(scrolled)invalidateGeometry();}
  showDestination();
  if(finishAfterFrame){finishAfterFrame=false;finishGesture();return;}
  if(state.interaction.gesture?.active&&scrolled)requestDragFrame();
 }
 document.addEventListener('dragover',event=>{if(!gesture?.native)return;event.preventDefault();gesture.x=event.clientX;gesture.y=event.clientY;if(event.dataTransfer)event.dataTransfer.dropEffect='move';requestDragFrame();});document.addEventListener('drop',event=>{if(!gesture?.native)return;event.preventDefault();gesture.x=event.clientX;gesture.y=event.clientY;finishAfterFrame=true;requestDragFrame();});document.addEventListener('dragend',()=>{if(gesture?.native&&!finishAfterFrame){cancelPointer('');render();}window.setTimeout(()=>{suppressRowClick=false;},0);});
 window.addEventListener('pointermove',event=>{if(!gesture||event.pointerId!==gesture.pointerId)return;gesture.x=event.clientX;gesture.y=event.clientY;if(!state.interaction.gesture.active&&Math.hypot(gesture.x-gesture.startX,gesture.y-gesture.startY)>=6)activateGesture();if(state.interaction.gesture.active){event.preventDefault();requestDragFrame();}},{passive:false});
 window.addEventListener('pointerup',event=>{if(!gesture||gesture.native||event.pointerId!==gesture.pointerId)return;if(state.interaction.gesture.active){gesture.x=event.clientX;gesture.y=event.clientY;finishAfterFrame=true;requestDragFrame();}else cancelPointer('');});
 window.addEventListener('pointercancel',()=>{if(!gesture?.native){cancelPointer('Move canceled.');render();}});window.addEventListener('lostpointercapture',event=>{if(gesture&&!gesture.native&&event.pointerId===gesture.pointerId&&!finishAfterFrame){cancelPointer('Move canceled.');render();}});window.addEventListener('keydown',event=>{if(event.key==='Escape'){if(state.interaction.view.headerMenu){event.preventDefault();closeHeaderMenus();}if(state.interaction.view.pickerOpen){event.preventDefault();closePickers();}if(gesture){event.preventDefault();cancelPointer('Move canceled.');render();}if(state.interaction.view.moveChooserOpen){event.preventDefault();closeMove();}}});
 function renderDisplay(display){const {context,pending,error}=display;if(context.theme)document.documentElement.style.colorScheme=context.theme;const web=context.platform==='web'&&context.availableDisplayModes?.length===1&&context.availableDisplayModes[0]==='fullscreen';el('displayLabel').textContent=web?'Web preview':context.displayMode==='fullscreen'?'Full screen':context.displayMode==='inline'?'In conversation':'Display';const target=context.displayMode==='fullscreen'?'inline':'fullscreen';el('displayToggle').hidden=!context.availableDisplayModes?.includes(target);el('displayToggle').disabled=Boolean(pending);el('displayToggle').dataset.mode=target;el('displayToggle').innerHTML=model.iconSvg(target==='fullscreen'?'expand':'collapse')+'<span>'+(target==='fullscreen'?'Full screen':'Back to conversation')+'</span>';el('displayStatus').textContent=pending?'Switching display…':error||'';if(displayData)render();}

 function resumeComposition(intent){if(!intent)return;if(intent.kind==='create')createFromHeader({kind:intent.entity,parent:intent.parent,payload:intent.payload});else if(intent.kind==='select-catalog')selectCatalog(intent.catalogKind,intent.id);else if(intent.id===null)closeEditor();else selectEditor(intent.id);}
 for(const [field,node] of [['name',el('catalogEditName')],['description',el('catalogEditDescription')]]){
  node.addEventListener('input',()=>{const target=state.inspector;if(target&&target.kind!=='action')controller.editCatalog(state.interaction.composition?.key||target.kind+':'+target.id,{[field]:node.value});});
  node.addEventListener('blur',event=>{if(state.transients[state.inspector?.id]&&event.relatedTarget?.closest('.add-split'))return;if(!state.interaction.composition)flushCatalogInspector();});
  node.addEventListener('compositionstart',()=>{const target=state.inspector;if(target&&target.kind!=='action'){const key=target.kind+':'+target.id;compositionInput=node;controller.dispatch({type:'composition.begin',key,field});controller.composeCatalog(key,true);renderSaveIndicator();}});
  node.addEventListener('compositionend',()=>{const original=state.interaction.composition;if(!original)return;controller.dispatch({type:'composition.end'});compositionInput=null;controller.editCatalog(original.key,{[field]:node.value});controller.composeCatalog(original.key,false,original.deferred?.kind!=='create'||!state.transients[original.key.slice(original.key.indexOf(':')+1)]);resumeComposition(original.deferred);});
 }
 el('catalogClose').onclick=el('catalogBack').onclick=()=>{if(state.interaction.composition){controller.dispatch({type:'composition.defer',intent:{kind:'select-action',id:null}});return;}flushCatalogInspector();controller.selectAction(null);};el('catalogRetry').onclick=()=>{const target=state.inspector;if(target)controller.retryCatalog(target.kind+':'+target.id);};el('catalogUseMine').onclick=()=>{const target=state.inspector;if(target)controller.resolveCatalog(target.kind+':'+target.id,true);};el('catalogUseSaved').onclick=()=>{const target=state.inspector;if(target)controller.resolveCatalog(target.kind+':'+target.id,false);};
 function openCatalog(type,target,parentId=null,inline=false){const host=target?el(type==='project'?'projectPicker':'tagPicker'):el('addMenu');if(inline)el('actions').before(el('catalogComposer'));else{host.hidden=false;host.append(el('catalogComposer'));}setView('catalogContext',{type,target,parentId,token:controller.dispatch({type:'catalog.next-token'})});el('catalogNameLabel').textContent=(type==='project'?'Project name':'Tag name')+(parentId?' · '+((displayData[type==='project'?'projects':'tags']||[]).find(n=>n.id===parentId)?.path||(displayData[type==='project'?'projects':'tags']||[]).find(n=>n.id===parentId)?.name||'Unavailable parent'):'');showCatalog(true);setCatalogName('');el('catalogComposer').scrollIntoView?.({block:'nearest'});el('catalogName').focus();renderSaveIndicator();}
 el('addMenuToggle').onclick=()=>state.interaction.view.pickerOpen==='add'?closePickers():openPicker('add');el('addMenuAction').onclick=()=>{closePickers(false);el('addAction').click();};for(const kind of ['project','tag'])el(kind==='project'?'addMenuProject':'addMenuTag').onclick=()=>{const target=creationObject(),same=state.interaction.view.navigation.view===(kind==='project'?'projects':'tags'),parent=same?(target?.kind===kind?target.id:target?.kind==='action'?target.catalogId:null):null;const intent={kind,parent:parent||null};if(state.interaction.composition){controller.dispatch({type:'composition.defer',intent:{kind:'create',entity:intent.kind,parent:intent.parent}});closePickers(false);}else createFromHeader(intent);};el('projectSearch').onfocus=()=>{if(state.interaction.view.pickerOpen!=='project'){openPicker('project');el('projectSearch').select();}};el('projectSearch').oninput=()=>{controller.dispatch({type:'picker.query',kind:'project',query:el('projectSearch').value});renderPickerOptions();};el('projectSearch').onkeydown=pickerKey;el('tagPickerToggle').onclick=()=>state.interaction.view.pickerOpen==='tag'?closePickers():openPicker('tag');el('tagSearch').oninput=()=>{controller.dispatch({type:'picker.query',kind:'tag',query:el('tagSearch').value});renderPickerOptions();};el('tagSearch').onkeydown=pickerKey;el('pickerNewProject').onclick=()=>{openCatalog('project',state.interaction.view.pickerTarget);setCatalogName(state.interaction.view.projectQuery);};el('pickerNewTag').onclick=()=>{openCatalog('tag',state.interaction.view.pickerTarget);setCatalogName(state.interaction.view.tagQuery);};document.addEventListener('pointerdown',event=>{if(state.interaction.view.pickerOpen&&!event.target.closest('.picker-shell,.add-split,#catalogComposer'))closePickers(false);});
 el('catalogName').addEventListener('input',()=>{setView('catalogName',el('catalogName').value);renderSaveIndicator();});el('cancelCatalog').onclick=()=>{showCatalog(false);if(state.interaction.view.catalogContext)controller.cancelCatalogCreation(state.interaction.view.catalogContext.type,state.interaction.view.catalogContext.parentId);renderSaveIndicator();};el('createCatalog').onclick=()=>{if(state.interaction.view.catalogContext){const token=controller.dispatch({type:'catalog.next-token'}),name=el('catalogName').value;controller.dispatch({type:'catalog.submission',token,submission:{...state.interaction.view.catalogContext,name,contextToken:state.interaction.view.catalogContext.token,navigation:JSON.stringify(state.interaction.view.navigation)}});if(!controller.createCatalog(state.interaction.view.catalogContext.type,name,state.interaction.view.catalogContext.target,token,state.interaction.view.catalogContext.parentId))controller.dispatch({type:'catalog.submission',token,submission:null});}};el('catalogName').onkeydown=event=>{if(event.key==='Enter'&&!event.isComposing){event.preventDefault();el('createCatalog').click();}};
 el('actions').after(el('moveStatus'));el('chooseMove').onclick=()=>{if(state.moveIssue){controller.dispatch({type:'occurrence.replace',ids:state.moveIssue.payload.ids,keys:outlineEntries.filter(entry=>entry.kind==='action'&&state.moveIssue.payload.ids.includes(entry.id)).map(entry=>entry.key)});setMovePlacement(state.moveIssue.payload.placement);openMove();if(state.moveIssue.payload.anchor_id)setMoveDestination(state.moveIssue.payload.anchor_id);}};el('openMove').onclick=()=>{setView('catalogMoveSource',null);openMove();};el('clearSelection').onclick=()=>{controller.dispatch({type:'occurrence.clear'});showMove(false);render();};el('movePlacement').onchange=()=>{setView('movePlacement',el('movePlacement').value);render();};el('moveDestination').onchange=()=>{setView('moveDestination',el('moveDestination').value);renderMoveChooser(model.navigation.present(displayData,state.interaction.view.navigation).actions);};el('applyMove').onclick=()=>{if(state.interaction.view.catalogMoveSource){const source=state.interaction.view.catalogMoveSource,placement=el('movePlacement').value,anchor=el('moveDestination').value;if(controller.moveCatalog(source.kind,{id:source.id,placement,...(placement==='root'?{}:{anchor_id:anchor})}))closeMove();}else commitMove(state.interaction.selection.ids,el('movePlacement').value,el('moveDestination').value);};el('cancelMove').onclick=closeMove;document.querySelectorAll('[data-status]').forEach(choice=>choice.onclick=()=>{controller.editDraft(editorId,{status:choice.dataset.status});controller.flush(editorId);});
 el('editFlag').onclick=()=>{if(editorId){controller.editDraft(editorId,{flagged:!state.drafts[editorId].flagged});controller.flush(editorId);}};el('useMine').onclick=()=>controller.resolveConflict(editorId,true);el('useSaved').onclick=()=>controller.resolveConflict(editorId,false);
 el('discardTemporaryAction').onclick=()=>controller.discardTemporary(editorId);el('discardTemporaryCatalog').onclick=()=>controller.discardTemporary(state.inspector?.id);el('addAction').onclick=()=>{const creation=model.navigation.creationContext({...displayData,actions:displayData.actions.map(action=>({...action,project_id:state.drafts[action.id]?state.drafts[action.id].project_id:action.project_id}))},state.interaction.view.navigation,creationObject());if(creation.allowed){if(state.interaction.composition)controller.dispatch({type:'composition.defer',intent:{kind:'create',entity:'action',payload:creation.payload}});else controller.createEmpty(creation.payload);}};
 function closeEditor(){if(state.interaction.composition){controller.dispatch({type:'composition.defer',intent:{kind:'select-action',id:null}});return;}if(!state.interaction.composition)controller.flush(editorId);const id=state.selectedId;controller.dispatch({type:'selection.action',id:null});restoreFocus('select:'+(state.interaction.selection.active||id));if(document.activeElement===document.body)el('navigationToggle').focus();}
 el('backToList').onclick=closeEditor;el('closeEditor').onclick=closeEditor;
 el('refresh').onclick=()=>controller.refresh().catch(error=>message(error.code?model.errorMessage(error.code):error.message));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate({view:b.dataset.view}));document.querySelectorAll('[data-display-choice]').forEach(b=>b.onclick=()=>{const next=model.navigation.toggleDisplay(state.interaction.view.navigation,b.dataset.displayChoice);navigate({statuses:next.statuses,includeDeferred:next.includeDeferred},true);});el('undo').onclick=()=>controller.undo();el('check').onclick=()=>controller.check();el('retry').onclick=()=>controller.retry();el('displayToggle').onclick=()=>bridge.request(el('displayToggle').dataset.mode);
 window.addEventListener('beforeunload',event=>{if(model.hasUnsavedChanges(state.unknown,state.drafts,'','')){event.preventDefault();event.returnValue='';}});
 resizeObserver=typeof window.ResizeObserver==='function'?new window.ResizeObserver(invalidateGeometry):null;resizeObserver?.observe(el('actions'));resizeObserver?.observe(el('refresh').closest('header'));window.addEventListener('resize',invalidateGeometry,{passive:true});document.addEventListener('scroll',invalidateGeometry,{capture:true,passive:true});document.fonts?.addEventListener?.('loadingdone',invalidateGeometry);document.fonts?.ready?.then(invalidateGeometry);const dispose=()=>{if(disposed)return;disposed=true;cancelPointer('');resizeObserver?.disconnect();document.fonts?.removeEventListener?.('loadingdone',invalidateGeometry);window.removeEventListener('resize',invalidateGeometry);document.removeEventListener('scroll',invalidateGeometry,true);unsubscribeSnapshot();bridge.dispose();transport.dispose();};window.addEventListener('pagehide',dispose,{once:true});const ready=transport.request('ui/initialize',{appInfo:{name:'action-tools',version:'0.2.0'},appCapabilities:{availableDisplayModes:['inline','fullscreen']},protocolVersion:'2026-01-26'}).then(result=>{bridge.initialize(result||{});transport.notify('ui/notifications/initialized',{});});ready.then(controller.refresh).catch(error=>message(error.message));
 return {controller,bridge,dispose};
}
