from playwright.sync_api import sync_playwright,expect
import json
ids=json.load(open('/tmp/contextual-create-calendar/ids.json'));out=[]
with sync_playwright() as p:
 b=p.chromium.launch()
 def setup(view='inbox',zone='Asia/Tokyo'):
  c=b.new_context(timezone_id=zone,locale='en-US',viewport={'width':1280,'height':1400});page=c.new_page();page.add_init_script('const original=setTimeout;window.setTimeout=(fn,ms,...args)=>original(fn,ms>=10000?1000:ms,...args)');page.goto('http://127.0.0.1:5210/');f=page.frame_locator('iframe');expect(f.locator('#scopeTitle')).to_have_text('Inbox');
  if view!='inbox':f.locator('#navigationToggle').click();f.locator('[data-focus-key="perspective:'+ids['everything']+'"]' if view=='perspective' else '[data-view="'+view+'"]').click()
  return c,page,f
 for view in ['inbox','projects','tags','flagged','history','perspective']:
  c,page,f=setup(view);f.locator('#addAction').click();page.wait_for_function('writes.length===1&&snapshot.actions.some(a=>a.id===writes[0].args.payload.id)||writes.length===1&&snapshot.actions.some(a=>a.title==="")');w=page.evaluate('writes[0]');assert w['args']['kind']=='add';assert w['args']['payload'].get('parent_id') is None;assert w['args']['payload'].get('project_id') is None;assert not w['args']['payload'].get('tag_ids');empty=page.evaluate('snapshot.actions.filter(a=>a.title==="").at(-1)');assert empty['status']=='active';expect(f.locator('#editTitle')).to_have_value('');out.append({'case':'root-add-'+view,'passed':True});c.close()
 for view,kind,selected,expected in [('projects','action','plan','work'),('projects','project','work','work'),('tags','tag','focus','focus'),('tags','action','plan','focus')]:
  c,page,f=setup(view)
  if kind=='action':row=f.locator('.action-row[data-action-id="'+ids[selected]+'"]'+('[data-occurrence-key^="tag:'+ids['focus']+'"]' if view=='tags' else '')).first;row.locator('.action-select').click()
  else:f.locator('.catalog-row[data-catalog-kind="'+kind+'"][data-catalog-id="'+ids[selected]+'"] .catalog-select').click()
  f.locator('#addAction').click();page.wait_for_function('writes.length===1');w=page.evaluate('writes[0].args.payload');assert w.get('parent_id')==(ids[selected] if kind=='action' else None)
  if view=='projects':assert w['project_id']==ids[expected]
  else:assert w['tag_ids']==[ids[expected]];assert f.locator('.action-row[data-action-id="'+ids['plan']+'"]').count()>=2 if kind=='action' else True
  page.wait_for_function('snapshot.actions.some(a=>a.title==="")');new=page.evaluate('snapshot.actions.filter(a=>a.title==="").at(-1)');assert new['status']=='active'
  if view=='tags':assert len(new['tags'])==1
  out.append({'case':'selected-'+view+'-'+kind+'-context','passed':True});c.close()
 for kind,view in [('project','projects'),('tag','tags')]:
  c,page,f=setup(view);f.locator('#addMenuToggle').click();f.locator('#addMenu'+kind.title()).click();page.wait_for_function('writes.length===1&&snapshot.'+view+'.some(a=>a.name==="")');first=page.evaluate('snapshot.'+view+'.find(a=>a.name==="").id');assert page.evaluate('writes[0].args.kind')==kind+'_add';expect(f.locator('#catalogComposer')).to_be_hidden();f.locator('#catalogClose').click();f.locator('#addMenuToggle').click();f.locator('#addMenu'+kind.title()).click();page.wait_for_function('snapshot.'+view+'.filter(a=>a.name==="").length===2');blank=page.evaluate('snapshot.'+view+'.filter(a=>a.name==="").map(a=>a.id)');assert len(set(blank))==2;f.locator('#catalogEditName').fill('Renamed '+kind);f.locator('#catalogEditName').blur();page.wait_for_function('snapshot.'+view+'.some(a=>a.name==="Renamed '+kind+'")');assert len(page.evaluate('writes'))==3;out.append({'case':'header-'+kind+'-repeated-distinct-empty-name-autosave','passed':True});c.close()
 for field,dateid,timeid in [('due_at','editDue','dueTime'),('defer_until','deferDate','deferUntil')]:
  c,page,f=setup('projects');f.locator('.action-row[data-action-id="'+ids['plan']+'"] .action-select').click();date=f.locator('#'+dateid);clock=f.locator('#'+timeid);assert clock.get_attribute('type')=='text';date.fill('2026-10-04');date.blur();page.wait_for_function('args=>snapshot.actions.find(a=>a.id===args.id)[args.field]==="2026-10-04T00:00:00.000Z"',arg={'id':ids['plan'],'field':field});expect(clock).to_have_value('09:00')
  for value,utc in [('1317','2026-10-04T04:17:00.000Z'),('23:59','2026-10-04T14:59:00.000Z'),('13:17:45.123','2026-10-04T04:17:45.123Z')]:
   clock.fill(value);clock.blur();page.wait_for_function('args=>snapshot.actions.find(a=>a.id===args.id)[args.field]===args.utc',arg={'id':ids['plan'],'field':field,'utc':utc})
  before=page.evaluate('writes.length');f.locator('#refresh').click();expect(clock).to_have_value('13:17:45.123');page.wait_for_timeout(300);assert page.evaluate('writes.length')==before;clock.fill('');clock.blur();expect(f.locator('#saveIndicator')).to_have_attribute('data-state','error');page.wait_for_timeout(600);assert page.evaluate('writes.length')==before;date.fill('');date.blur();page.wait_for_function('args=>snapshot.actions.find(a=>a.id===args.id)[args.field]===null',arg={'id':ids['plan'],'field':field});out.append({'case':field+'-enUS-24h-default09-ms-invalidtime-clear','passed':True});c.close()
 c,page,f=setup('history');f.locator('.action-row[data-action-id="'+ids['done']+'"] .action-select').click();f.locator('#addAction').click();page.wait_for_function('writes.length===1&&snapshot.actions.some(a=>a.title==="")');new=page.evaluate('snapshot.actions.find(a=>a.title==="")');assert new['status']=='active' and new['parent_id']==ids['done'];assert page.evaluate('snapshot.actions.find(a=>a.id==="'+ids['done']+'").status')=='completed';out.append({'case':'completed-parent-child-active-parent-unchanged','passed':True});c.close()
 for kind,view,parent in [('project','projects','work'),('tag','tags','focus'),('project','tags',None),('tag','projects',None)]:
  c,page,f=setup(view)
  if parent:f.locator('.catalog-row[data-catalog-kind="'+kind+'"][data-catalog-id="'+ids[parent]+'"] .catalog-select').click()
  else:f.locator('.action-row[data-action-id="'+ids['plan']+'"]').first.locator('.action-select').click()
  f.locator('#addMenuToggle').click();f.locator('#addMenu'+kind.title()).click();page.wait_for_function('writes.length===1');assert page.evaluate('writes[0].args.payload.parent_id')==(ids[parent] if parent else None);out.append({'case':'header-'+kind+'-'+view+'-parentcontext','passed':True});c.close()
 for kind,view in [('project','projects'),('tag','tags')]:
  for recovery in ['check','retry']:
   c,page,f=setup(view);page.evaluate('dropNextResponse=true');f.locator('#addMenuToggle').click();f.locator('#addMenu'+kind.title()).click();expect(f.locator('#unknown')).to_be_visible(timeout=5000);first=page.evaluate('writes[0]');created=page.evaluate('snapshot.'+view+'.find(a=>a.name==="").id');f.locator('#'+recovery).click();expect(f.locator('#unknown')).to_be_hidden();expect(f.locator('#catalogEditName')).to_have_value('');f.locator('#catalogEditName').fill('Recovered '+kind);f.locator('#catalogEditName').blur();page.wait_for_function('args=>snapshot[args.view].find(a=>a.id===args.id).name===args.name',arg={'view':view,'id':created,'name':'Recovered '+kind});copies=[w for w in page.evaluate('writes') if w['args']['operationId']==first['args']['operationId']];assert len(copies)==(1 if recovery=='check' else 2) and all(w==first for w in copies);assert len(page.evaluate('snapshot.'+view+'.filter(a=>a.id==="'+created+'")'))==1;out.append({'case':'header-'+kind+'-unknown-'+recovery+'-sameUUID','passed':True});c.close()
 for field,dateid,timeid in [('due_at','editDue','dueTime'),('defer_until','deferDate','deferUntil')]:
  c,page,f=setup('projects','America/New_York');f.locator('.action-row[data-action-id="'+ids['plan']+'"] .action-select').click();f.locator('#'+timeid).fill('02:30');f.locator('#'+dateid).fill('2026-03-08');f.locator('#'+dateid).blur();expect(f.locator('#saveIndicator')).to_have_attribute('data-state','error');page.wait_for_timeout(600);assert page.evaluate('writes.length')==0;out.append({'case':field+'-DSTgap-blocked','passed':True});c.close()
 for kind,view,expected in [('project','projects','work'),('tag','tags','focus')]:
  c,page,f=setup(view);f.locator('.action-row[data-action-id="'+ids['plan']+'"]'+('[data-occurrence-key^="tag:'+ids['focus']+'"]' if view=='tags' else '')).first.locator('.action-select').click();f.locator('#addMenuToggle').click();f.locator('#addMenu'+kind.title()).click();page.wait_for_function('writes.length===1');assert page.evaluate('writes[0].args.payload.parent_id')==ids[expected];out.append({'case':'header-'+kind+'-selectedAction-occurrence-parent','passed':True});c.close()
 for field,dateid,timeid in [('due_at','editDue','dueTime'),('defer_until','deferDate','deferUntil')]:
  for recovery in ['check','retry']:
   c,page,f=setup('projects');f.locator('.action-row[data-action-id="'+ids['plan']+'"] .action-select').click();page.evaluate('dropNextResponse=true');f.locator('#'+dateid).fill('2026-10-04');f.locator('#'+dateid).blur();expect(f.locator('#unknown')).to_be_visible(timeout=5000);first=page.evaluate('writes[0]');clock=f.locator('#'+timeid);clock.fill('13:');clock.blur();f.locator('#'+recovery).click();expect(f.locator('#unknown')).to_be_hidden();expect(clock).to_have_value('13:');expect(f.locator('#saveIndicator')).to_have_attribute('data-state','error');clock.fill('13:17');clock.blur();page.wait_for_function('args=>snapshot.actions.find(a=>a.id===args.id)[args.field]==="2026-10-04T04:17:00.000Z"',arg={'id':ids['plan'],'field':field});copies=[w for w in page.evaluate('writes') if w['args']['operationId']==first['args']['operationId']];assert len(copies)==(1 if recovery=='check' else 2) and all(w==first for w in copies);out.append({'case':field+'-unknown-'+recovery+'-newerPartialClock','passed':True});c.close()
 c,page,f=setup('projects');f.locator('.action-row[data-action-id="'+ids['plan']+'"] .action-select').click();title=f.locator('#editTitle');title.dispatch_event('compositionstart');title.fill('  Calendar 日本語  ');f.locator('#addMenuToggle').click();f.locator('#addMenuProject').click();assert page.evaluate('writes.length')==0;title.dispatch_event('compositionend');page.wait_for_function('writes.some(w=>w.args.kind==="project_add")&&snapshot.actions.some(a=>a.title==="Calendar 日本語")');assert page.evaluate('writes.map(w=>w.args.kind)')==['edit','project_add'];out.append({'case':'ActionIME-before-header-create-exact-original-save','passed':True});c.close()
 c,page,f=setup('projects');f.locator('.catalog-row[data-catalog-kind="project"][data-catalog-id="'+ids['work']+'"] .catalog-select').click();name=f.locator('#catalogEditName');name.dispatch_event('compositionstart');name.fill('  Context 日本語  ');f.locator('#addMenuToggle').click();f.locator('#addMenuTag').click();assert page.evaluate('writes.length')==0;name.dispatch_event('compositionend');page.wait_for_function('writes.some(w=>w.args.kind==="tag_add")&&snapshot.projects.some(a=>a.name==="Context 日本語")');assert page.evaluate('writes.map(w=>w.args.kind)')==['project_edit','tag_add'];out.append({'case':'catalogIME-before-header-create-preserved','passed':True});c.close()
 for kind in ['action','project','tag']:
  c,page,f=setup('inbox');page.evaluate('delayNextResponse=600')
  if kind=='action':f.locator('#addAction').click()
  else:f.locator('#addMenuToggle').click();f.locator('#addMenu'+kind.title()).click()
  page.wait_for_function('writes.length===1');f.locator('#navigationToggle').click();f.locator('[data-view="history"]').click();expect(f.locator('#scopeTitle')).to_have_text('History');page.wait_for_timeout(1000);expect(f.locator('#scopeTitle')).to_have_text('History');expect(f.locator('#catalogEditor')).to_be_hidden();expect(f.locator('#editor')).to_be_hidden();out.append({'case':'late-'+kind+'-creation-explicit-navigation-wins','passed':True});c.close()
 c,page,f=setup('history');f.locator('.action-row[data-action-id="'+ids['dropped']+'"] .action-select').click();f.locator('#addAction').click();page.wait_for_function('snapshot.actions.some(a=>a.title==="")');new=page.evaluate('snapshot.actions.find(a=>a.title==="")');assert new['status']=='active' and new['parent_id']==ids['dropped'];assert page.evaluate('snapshot.actions.find(a=>a.id==="'+ids['dropped']+'").status')=='dropped';out.append({'case':'dropped-parent-child-active-parent-unchanged','passed':True});c.close()
 c,page,f=setup('projects');f.locator('.action-row[data-action-id="'+ids['plan']+'"] .action-select').click();title=f.locator('#editTitle');title.dispatch_event('compositionstart');title.fill('  Primary 日本語  ');f.locator('#addAction').click();assert page.evaluate('writes.length')==0;expect(title).to_have_value('  Primary 日本語  ');title.dispatch_event('compositionend');page.wait_for_function('writes.some(w=>w.args.kind==="add")&&snapshot.actions.some(a=>a.title==="Primary 日本語")');assert page.evaluate('writes.map(w=>w.args.kind)')==['edit','add'];assert page.evaluate('writes.at(-1).args.payload.parent_id')==ids['plan'];out.append({'case':'primaryAddAction-originalIME-target-retained','passed':True});c.close()
 b.close()
json.dump(out,open('/tmp/contextual-create-calendar/browser-proof.json','w'),indent=2);print(out)
