import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,primaryKey,uniqueIndex,check} from 'drizzle-orm/sqlite-core';
export const actions=sqliteTable('actions',{
 owner:text('owner').notNull(),id:text('id').notNull(),title:text('title').notNull(),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),parentId:text('parent_id'),status:text('status').notNull().default('active'),dueAt:text('due_at'),deferUntil:text('defer_until'),notes:text('notes').notNull().default(''),projectId:text('project_id'),order:integer('order').notNull().default(0),flagged:integer('flagged',{mode:'boolean'}).notNull().default(false)
},t=>[primaryKey({columns:[t.owner,t.id]}),check('actions_order_valid',sql`typeof(${t.order})='integer' AND ${t.order} BETWEEN 0 AND 9007199254740991`),check('actions_flagged_valid',sql`${t.flagged} IN (0,1)`)]);
export const projects=sqliteTable('projects',{order:integer('order').notNull().default(0),owner:text('owner').notNull(),id:text('id').notNull(),name:text('name').notNull(),description:text('description').notNull().default(''),parentId:text('parent_id'),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.owner,t.id]}),check('projects_order_valid',sql`typeof(${t.order})='integer' AND ${t.order} BETWEEN 0 AND 9007199254740991`),uniqueIndex('projects_owner_root_name_uq').on(t.owner,t.name).where(sql`${t.parentId} is null`),uniqueIndex('projects_owner_parent_name_uq').on(t.owner,t.parentId,t.name).where(sql`${t.parentId} is not null`)]);
export const tags=sqliteTable('tags',{order:integer('order').notNull().default(0),owner:text('owner').notNull(),id:text('id').notNull(),name:text('name').notNull(),description:text('description').notNull().default(''),parentId:text('parent_id'),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.owner,t.id]}),check('tags_order_valid',sql`typeof(${t.order})='integer' AND ${t.order} BETWEEN 0 AND 9007199254740991`),uniqueIndex('tags_owner_root_name_uq').on(t.owner,t.name).where(sql`${t.parentId} is null`),uniqueIndex('tags_owner_parent_name_uq').on(t.owner,t.parentId,t.name).where(sql`${t.parentId} is not null`)]);
export const actionTags=sqliteTable('action_tags',{owner:text('owner').notNull(),actionId:text('action_id').notNull(),tagId:text('tag_id').notNull(),revision:integer('revision').notNull()},t=>[primaryKey({columns:[t.owner,t.actionId,t.tagId]})]);
export const catalogIdentityLedger=sqliteTable('catalog_identity_ledger',{owner:text('owner').notNull(),kind:text('kind').notNull(),identity:text('identity').notNull(),revision:integer('revision').notNull()},t=>[primaryKey({columns:[t.owner,t.kind,t.identity]})]);
export const operations=sqliteTable('operations',{owner:text('owner').notNull(),operationId:text('operation_id').notNull(),canonicalPayload:text('canonical_payload').notNull(),result:text('result').notNull(),delta:text('delta').notNull(),revisionBefore:integer('revision_before').notNull(),revisionAfter:integer('revision_after').notNull(),undoOf:text('undo_of'),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.owner,t.operationId]}),uniqueIndex('operations_owner_revision_uq').on(t.owner,t.revisionAfter)]);

export const perspectives=sqliteTable('perspectives',{owner:text('owner').notNull(),id:text('id').notNull(),name:text('name').notNull(),description:text('description').notNull().default(''),filter:text('filter').notNull(),definitionVersion:integer('definition_version').notNull().default(1),revision:integer('revision').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.owner,t.id]}),check('perspectives_definition_version_valid',sql`${t.definitionVersion}=1`),check('perspectives_filter_valid',sql`json_valid(${t.filter}) AND json_type(${t.filter})='object'`)]);
