import {test} from 'node:test';import assert from 'node:assert/strict';
import {createD1ActionStore} from '../../lib/adapters/d1-action-store.ts';import {actionCall} from '../../lib/application/action-service.ts';import {memoryActionStore} from '../helpers/memory-action-store.mjs';import {sqliteFixture} from '../helpers/sqlite-d1.mjs';
const now='2026-10-03T00:00:00.000Z';
for(const kind of ['memory','SQLite D1'])test(kind+' action_move preserves atomic CAS/replay/Undo/owner contracts',async t=>{
 const fixture=kind==='memory'?null:sqliteFixture();if(fixture)t.after(()=>fixture.sql.close());const store=fixture?createD1ActionStore(fixture.db):memoryActionStore();let allocated=0;
 const call=(owner,name,args={})=>actionCall({store,clock:()=>now,newId:()=>{allocated++;return crypto.randomUUID();}},owner,name,args);
 const write=async(owner,kind,payload)=>call(owner,'apply_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:(await store.readSnapshot(owner)).revision,kind,payload});
 const project=(await write('A','project_get_or_create',{name:'P'})).result.resolved.project.id,tag=(await write('A','tag_get_or_create',{name:'T'})).result.resolved.tag.id;
 const create=async(title,p={})=>(await write('A','add',{title,notes:' exact\n日本語 ',project_id:project,tag_ids:[tag],flagged:true,...p})).result.resolved.actions[0].id;
 const a=await create('A',{order:20}),hidden=await create('Hidden',{order:40}),b=await create('B',{order:80}),child=await create('Child',{parent_id:a,order:99});
 await write('A','edit',{id:child,status:'on-hold',due_at:'2026-10-05T09:00:00Z',defer_until:'2026-10-04T09:00:00Z'});
 const foreign=(await write('B','add',{title:'Owner B'})).result.resolved.actions[0].id;
 const before=await store.readSnapshot('A'),idsUsed=allocated,invalid={schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:before.revision,kind:'action_move',payload:{ids:[a,foreign],placement:'inside',anchor_id:b}};
 await assert.rejects(call('A','apply_change',invalid),e=>e.code==='not_found');assert.deepEqual(await store.readSnapshot('A'),before);assert.equal(await store.readReceipt('A',invalid.operationId),null);assert.equal(allocated,idsUsed);
 const request={...invalid,operationId:crypto.randomUUID(),payload:{ids:[b,a,child],placement:'after',anchor_id:hidden}};
 const preview=await call('A','preview_change',{expectedRevision:before.revision,kind:request.kind,payload:request.payload});assert.ok(preview.affected.length);assert.deepEqual(await store.readSnapshot('A'),before);
 if(fixture)fixture.lose();else store.lose();await assert.rejects(call('A','apply_change',request),/lost response/);const after=await store.readSnapshot('A'),proof=await call('A','operation_status',{operationId:request.operationId});assert.equal(proof.status,'applied');assert.equal(after.revision,before.revision+1);assert.equal(allocated,idsUsed);
 const replay=await call('A','apply_change',request);assert.equal(replay.result.operationId,request.operationId);assert.equal(replay.revision,after.revision);assert.deepEqual(replay.actions.filter(x=>x.parent_id===null).map(x=>x.id),[hidden,b,a]);assert.equal(replay.actions.find(x=>x.id===child).parent_id,a);assert.equal(replay.actions.find(x=>x.id===child).order,99);
 for(const action of after.actions){const old=before.actions.find(x=>x.id===action.id);for(const key of ['title','notes','project_id','status','flagged','due_at','defer_until'])assert.equal(action[key],old[key]);}assert.deepEqual(after.action_tags,before.action_tags);
 await call('A','undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:after.revision,undoOf:request.operationId});const restored=await store.readSnapshot('A');for(const action of restored.actions){const old=before.actions.find(x=>x.id===action.id);assert.equal(action.parent_id,old.parent_id);assert.equal(action.order,old.order);}
 const race=await Promise.allSettled([a,b].map(id=>call('A','apply_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:restored.revision,kind:'action_move',payload:{ids:[id],placement:'inside',anchor_id:hidden}})));assert.equal(race.filter(x=>x.status==='fulfilled').length,1);assert.equal(race.filter(x=>x.status==='rejected'&&x.reason.code==='conflict').length,1);
 const current=await store.readSnapshot('A'),changed=(await write('A','action_move',{ids:[a,b],placement:'root'})).result.operationId;const saved=await store.readSnapshot('A');await write('A','edit',{id:a,notes:'later correction'});const late=await store.readSnapshot('A');await assert.rejects(call('A','undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:late.revision,undoOf:changed}),e=>e.code==='undo_conflict');assert.deepEqual(await store.readSnapshot('A'),late);
 const exact={schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:late.revision,kind:'action_move',payload:{ids:[b,a],placement:'inside',anchor_id:hidden}};await call('A','apply_change',exact);await write('A','edit',{id:a,title:'newer title'});const repeated=await call('A','apply_change',exact);assert.equal(repeated.actions.find(x=>x.id===a).title,'newer title');assert.equal(repeated.result.revision,late.revision+1);assert.equal((await store.readSnapshot('B')).actions[0].id,foreign);assert.equal(await store.readReceipt('B',exact.operationId),null);assert.ok(current.revision<saved.revision);
});
test('SQLite row failure rolls back every moved sibling, parent, revision and receipt',async t=>{
 const fixture=sqliteFixture();t.after(()=>fixture.sql.close());const store=createD1ActionStore(fixture.db),call=args=>actionCall({store,clock:()=>now,newId:()=>crypto.randomUUID()},'A','apply_change',args);let revision=0;
 const create=async title=>{const r=await call({schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:revision++,kind:'add',payload:{title}});return r.result.resolved.actions[0].id;};const a=await create('A'),b=await create('B'),target=await create('Target');
 fixture.sql.exec(`CREATE TRIGGER reject_move BEFORE UPDATE ON actions WHEN NEW.id='${b}' BEGIN SELECT RAISE(ABORT, 'injected move failure'); END`);
 const before=await store.readSnapshot('A'),operationId=crypto.randomUUID();await assert.rejects(call({schemaVersion:2,operationId,expectedRevision:revision,kind:'action_move',payload:{ids:[a,b],placement:'inside',anchor_id:target}}));assert.deepEqual(await store.readSnapshot('A'),before);assert.equal(await store.readReceipt('A',operationId),null);
});
