import {test} from 'node:test';import assert from 'node:assert/strict';import {createD1ActionStore} from '../helpers/owner-composition.mjs';import {actionCallForOwner as actionCall} from '../helpers/owner-composition.mjs';import {memoryActionStore} from '../helpers/memory-action-store.mjs';import {sqliteFixture} from '../helpers/sqlite-d1.mjs';
const now='2026-10-03T00:00:00.000Z';
for(const adapter of ['memory','SQLite D1'])for(const kind of ['action_project','action_tag'])test(adapter+' '+kind+' batch CAS, owner isolation, lost response replay and conflict-safe Undo',async t=>{
 const f=adapter==='memory'?null:sqliteFixture();if(f)t.after(()=>f.sql.close());const store=f?createD1ActionStore(f.db):memoryActionStore();const call=(owner,name,args={})=>actionCall({store,clock:()=>now,newId:()=>crypto.randomUUID()},owner,name,args),write=async(owner,kind,payload)=>call(owner,'apply_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:(await store.readSnapshot(owner)).revision,kind,payload});
 const p=(await write('A','project_get_or_create',{name:'P'})).result.resolved.project.id,g=(await write('A','tag_get_or_create',{name:'T'})).result.resolved.tag.id;const a=(await write('A','add',{title:'A',flagged:true})).result.resolved.actions[0].id,b=(await write('A','add',{title:'B',parent_id:a,notes:' exact '})).result.resolved.actions[0].id,foreign=(await write('B','add',{title:'Foreign'})).result.resolved.actions[0].id;
 const payload=ids=>kind==='action_project'?{ids,project_id:p}:{ids,tag_id:g,enabled:true};const before=await store.readSnapshot('A'),bad={schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:before.revision,kind,payload:payload([a,foreign])};await assert.rejects(call('A','apply_change',bad),e=>e.code==='not_found');assert.deepEqual(await store.readSnapshot('A'),before);assert.equal(await store.readReceipt('A',bad.operationId),null);
 const req={...bad,operationId:crypto.randomUUID(),payload:payload([b,a])};if(f)f.lose();else store.lose();await assert.rejects(call('A','apply_change',req),/lost response/);const after=await store.readSnapshot('A');assert.equal(after.revision,before.revision+1);assert.equal((await call('A','operation_status',{operationId:req.operationId})).status,'applied');await call('A','apply_change',req);assert.deepEqual(await store.readSnapshot('A'),after);await assert.rejects(call('A','apply_change',{...req,payload:payload([a,b])}),e=>e.code==='idempotency_conflict');
 if(kind==='action_project')assert.ok(after.actions.every(x=>x.project_id===p));else assert.equal(after.action_tags.length,2);assert.equal(after.actions.find(x=>x.id===b).parent_id,a);
 await call('A','undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:after.revision,undoOf:req.operationId});const restored=await store.readSnapshot('A');assert.ok(restored.actions.every(x=>x.project_id===null));assert.equal(restored.action_tags.length,0);
 const race=await Promise.allSettled([a,b].map(id=>call('A','apply_change',{...req,operationId:crypto.randomUUID(),expectedRevision:restored.revision,payload:payload([id])})));assert.equal(race.filter(x=>x.status==='fulfilled').length,1);assert.equal(race.filter(x=>x.status==='rejected'&&x.reason.code==='conflict').length,1);
 const lateReq={...req,operationId:crypto.randomUUID(),expectedRevision:(await store.readSnapshot('A')).revision};await call('A','apply_change',lateReq);await write('A','edit',{id:b,notes:'Later correction'});const late=await store.readSnapshot('A');await assert.rejects(call('A','undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:late.revision,undoOf:lateReq.operationId}),e=>e.code==='undo_conflict');const replay=await call('A','apply_change',lateReq);assert.equal(replay.actions.find(x=>x.id===b).notes,'Later correction');assert.deepEqual(await store.readSnapshot('A'),late);assert.equal(await store.readReceipt('B',req.operationId),null);assert.equal((await store.readSnapshot('B')).actions[0].id,foreign);
});
for(const kind of ['action_project','action_tag'])test('SQLite '+kind+' injected middle row failure rolls back all rows and receipt',async t=>{
 const f=sqliteFixture();t.after(()=>f.sql.close());let lastOperation;const store=createD1ActionStore(f.db),call=async(kind,payload)=>actionCall({store,clock:()=>now,newId:()=>crypto.randomUUID()},'A','apply_change',{schemaVersion:2,operationId:(lastOperation=crypto.randomUUID()),expectedRevision:(await store.readSnapshot('A')).revision,kind,payload});const p=(await call('project_get_or_create',{name:'P'})).result.resolved.project.id,g=(await call('tag_get_or_create',{name:'T'})).result.resolved.tag.id,a=(await call('add',{title:'A'})).result.resolved.actions[0].id,b=(await call('add',{title:'B'})).result.resolved.actions[0].id;
 if(kind==='action_project')f.sql.exec(`CREATE TRIGGER reject_batch BEFORE UPDATE ON actions WHEN NEW.id='${b}' BEGIN SELECT RAISE(ABORT, 'injected classification failure'); END`);else f.sql.exec(`CREATE TRIGGER reject_batch BEFORE INSERT ON action_tags WHEN NEW.action_id='${b}' BEGIN SELECT RAISE(ABORT, 'injected classification failure'); END`);
 const before=await store.readSnapshot('A');await assert.rejects(call(kind,kind==='action_project'?{ids:[a,b],project_id:p}:{ids:[a,b],tag_id:g,enabled:true}));assert.deepEqual(await store.readSnapshot('A'),before);assert.equal(await store.readReceipt('A',lastOperation),null);
});
