import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createD1ActionStore} from '../../lib/adapters/d1-action-store.ts';import {actionCall} from '../../lib/application/action-service.ts';import {memoryActionStore} from '../helpers/memory-action-store.mjs';import {sqliteFixture} from '../helpers/sqlite-d1.mjs';
const now='2026-10-03T00:00:00.000Z';
for(const adapter of ['memory','SQLite'])for(const type of ['project','tag'])test(adapter+' named '+type+' distinct IDs, validation, CAS, lost response/replay and safe Undo',async t=>{
 const f=adapter==='SQLite'?sqliteFixture():null;if(f)t.after(()=>f.sql.close());const store=f?createD1ActionStore(f.db):memoryActionStore();let allocations=0;const call=(owner,name,args={})=>actionCall({store,clock:()=>now,newId:()=>{allocations++;return crypto.randomUUID();}},owner,name,args),req=async(kind,payload,owner='A')=>({schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:(await store.readSnapshot(owner)).revision,kind,payload}),write=async(kind,payload,owner='A')=>call(owner,'apply_change',await req(kind,payload,owner));
 const foreign=(await write(type+'_add',{name:'Foreign'},'B')).result.resolved[type].id;let before=await store.readSnapshot('A'),count=allocations;
 for(const payload of [{name:'Valid',id:crypto.randomUUID()},{name:'Valid',parent_id:foreign},{name:''},{name:'  '},{name:'x'.repeat(201)}])await assert.rejects(call('A','apply_change',await req(type+'_add',payload)));assert.equal(allocations,count);assert.deepEqual(await store.readSnapshot('A'),before);
 await assert.rejects(write(type+'_get_or_create',{name:''}));const first=(await write(type+'_add',{name:' First ',description:' exact '})).result.resolved[type].id,second=(await write(type+'_add',{name:'Second'})).result.resolved[type].id;assert.notEqual(first,second);const rows=(await store.readSnapshot('A'))[type==='project'?'projects':'tags'];assert.deepEqual(new Set(rows.map(x=>x.name)),new Set(['First','Second']));assert.equal(rows.find(x=>x.id===first).description,' exact ');if(type==='project')assert.deepEqual([first,second].map(id=>rows.find(x=>x.id===id).order),[0,1]);
 await write(type+'_edit',{id:first,name:'Named'});const named=(await write(type+'_get_or_create',{name:'Named',description:'overwrite'})).result.resolved[type];assert.equal(named.id,first);assert.equal(named.created,false);assert.equal((await store.readSnapshot('A'))[type==='project'?'projects':'tags'].find(x=>x.id===first).description,' exact ');count=allocations;await assert.rejects(write(type+'_add',{name:'Named'}));assert.equal(allocations,count);before=await store.readSnapshot('A');await assert.rejects(write(type+'_edit',{id:first,name:''}),e=>e.code==='invalid_input');assert.deepEqual(await store.readSnapshot('A'),before);
 const unknown=await req(type+'_add',{name:'Third'});if(f)f.lose();else store.lose();await assert.rejects(call('A','apply_change',unknown),/lost response/);const after=await store.readSnapshot('A'),status=await call('A','operation_status',{operationId:unknown.operationId}),created=status.result.resolved[type].id;count=allocations;const replay=await call('A','apply_change',unknown);assert.equal(replay.result.resolved[type].id,created);assert.equal(allocations,count);assert.deepEqual(await store.readSnapshot('A'),after);await assert.rejects(call('A','apply_change',{...unknown,payload:{name:'Other'}}),e=>e.code==='idempotency_conflict');assert.equal(await store.readReceipt('B',unknown.operationId),null);
 await call('A','undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:(await store.readSnapshot('A')).revision,undoOf:unknown.operationId});assert.ok(!(await store.readSnapshot('A'))[type==='project'?'projects':'tags'].some(x=>x.id===created));
 before=await store.readSnapshot('A');const races=await Promise.allSettled([1,2].map(()=>call('A','apply_change',{...unknown,operationId:crypto.randomUUID(),expectedRevision:before.revision})));assert.equal(races.filter(x=>x.status==='fulfilled').length,1);assert.equal(races.filter(x=>x.status==='rejected'&&x.reason.code==='conflict').length,1);
 const late=await req(type+'_add',{name:'Initial'});const lateId=(await call('A','apply_change',late)).result.resolved[type].id;await write(type+'_edit',{id:lateId,name:'Later'});await assert.rejects(call('A','undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:(await store.readSnapshot('A')).revision,undoOf:late.operationId}),e=>e.code==='undo_conflict');assert.equal((await call('A','apply_change',late))[type==='project'?'projects':'tags'].find(x=>x.id===lateId).name,'Later');
});
for(const type of ['project','tag'])test('SQLite '+type+' injected identity-row failure rolls back create and receipt',async t=>{
 const f=sqliteFixture();t.after(()=>f.sql.close());const store=createD1ActionStore(f.db);f.sql.exec("CREATE TRIGGER reject_identity BEFORE INSERT ON catalog_identity_ledger BEGIN SELECT RAISE(ABORT, 'injected identity failure'); END");const before=await store.readSnapshot('A'),operationId=crypto.randomUUID();await assert.rejects(actionCall({store,clock:()=>now,newId:()=>crypto.randomUUID()},'A','apply_change',{schemaVersion:2,operationId,expectedRevision:before.revision,kind:type+'_add',payload:{name:'Valid'}}));assert.deepEqual(await store.readSnapshot('A'),before);assert.equal(await store.readReceipt('A',operationId),null);
});
test('forward catalog index migration preserves populated rows/history and full uniqueness',async t=>{
 const f=sqliteFixture({beforeRequiredNamesMigration:true});t.after(()=>f.sql.close());
 // Isolate index migration 0015 after installing the columns required by the current adapter.
 f.sql.exec(readFileSync('drizzle/0016_tag_order.sql','utf8'));const store=createD1ActionStore(f.db);let revision=0;for(const type of ['project','tag'])await actionCall({store,clock:()=>now,newId:()=>crypto.randomUUID()},'A','apply_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:revision++,kind:type+'_get_or_create',payload:{name:'Named'}});const tables=['projects','tags','operations','catalog_identity_ledger'],before=Object.fromEntries(tables.map(table=>[table,f.sql.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()]));f.sql.exec(readFileSync('drizzle/0015_required_catalog_names.sql','utf8'));for(const table of tables)assert.deepEqual(f.sql.prepare('SELECT * FROM '+table+' ORDER BY rowid').all(),before[table]);for(const table of ['projects','tags']){const original=before[table][0],columns=Object.keys(original),insert=f.sql.prepare('INSERT INTO '+table+' ('+columns.map(k=>'"'+k+'"').join(',')+') VALUES ('+columns.map(()=>'?').join(',')+')');insert.run(...columns.map(k=>k==='id'?crypto.randomUUID():k==='name'?'':original[k]));assert.throws(()=>insert.run(...columns.map(k=>k==='id'?crypto.randomUUID():k==='name'?'':original[k])),/UNIQUE/);assert.throws(()=>insert.run(...columns.map(k=>k==='id'?crypto.randomUUID():original[k])),/UNIQUE/);}
});
test('forward index migration rejects duplicate data atomically instead of repairing it',t=>{
 const f=sqliteFixture({beforeRequiredNamesMigration:true});t.after(()=>f.sql.close());for(let i=0;i<2;i++)f.sql.prepare('INSERT INTO projects(owner,id,name,description,parent_id,"order",revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run('A',crypto.randomUUID(),'','',null,i,1,now,now);const before=f.sql.prepare('SELECT * FROM projects ORDER BY id').all(),indexes=f.sql.prepare("SELECT name,sql FROM sqlite_master WHERE type='index' AND name LIKE '%_name_uq' ORDER BY name").all();f.sql.exec('BEGIN');assert.throws(()=>f.sql.exec(readFileSync('drizzle/0015_required_catalog_names.sql','utf8')),/UNIQUE/);f.sql.exec('ROLLBACK');assert.deepEqual(f.sql.prepare('SELECT * FROM projects ORDER BY id').all(),before);assert.deepEqual(f.sql.prepare("SELECT name,sql FROM sqlite_master WHERE type='index' AND name LIKE '%_name_uq' ORDER BY name").all(),indexes);
});
