import {test} from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {actionCall} from '../helpers/d1-actions.mjs';
import {dateDefer} from '../../lib/domain/core.ts';
import {sqliteFixture} from '../helpers/sqlite-d1.mjs';
function scenario(t){
 const f=sqliteFixture(),owner='fictional-A';t.after(()=>f.sql.close());let now='2026-10-01T00:00:00.000Z';
 const aliases=new Map(),reverseAliases=new Map();
 const actual=value=>aliases.get(value)??value;
 const logical=value=>reverseAliases.get(value)??value;
 function publicChange(kind,payload){
  const p={...payload};let alias;
  if(kind==='defer'&&p.date&&!p.timezone)p.timezone='Asia/Tokyo';
  if(kind==='add'){alias=p.id;delete p.id;for(const key of ['parent_id','source_inbox_action_id'])if(p[key])p[key]=actual(p[key]);}
  else if(kind==='project_add'||kind==='tag_add'){alias=p.id;kind=kind==='project_add'?'project_get_or_create':'tag_get_or_create';delete p.id;if(p.parent_id)p.parent_id=actual(p.parent_id);}
  else if(kind==='structure'){
   const refs=new Map(p.actions.map((action,index)=>[action.id,`local-${index}`]));
   const actions=p.actions.map(action=>({ref:refs.get(action.id),title:action.title,...(action.parent_id?refs.has(action.parent_id)?{parent_ref:refs.get(action.parent_id)}:{parent_id:actual(action.parent_id)}:{}),...(action.notes!==undefined?{notes:action.notes}:{})}));
   const refsToAliases=new Map([...refs].map(([id,ref])=>[ref,id]));
   return {kind:'structure_create',payload:{inbox_action_id:actual(p.inbox_action_id),actions},aliasActions:refsToAliases};
  } else if(kind==='structure_create'){
   p.inbox_action_id=actual(p.inbox_action_id);
   p.actions=p.actions.map(action=>({...action,...(action.parent_id?{parent_id:actual(action.parent_id)}:{})}));
  } else {
   for(const key of ['id','parent_id','project_id','tag_id','source_inbox_action_id'])if(p[key])p[key]=actual(p[key]);
   if(Array.isArray(p.reopen_ancestors))p.reopen_ancestors=p.reopen_ancestors.map(actual);
   for(const key of ['dependent','prerequisite'])if(p[key])p[key]=actual(p[key]);
  }
  return {kind,payload:p,...(alias?{alias}:{})};
 }
 function mapResponse(value){
  if(Array.isArray(value))return value.map(mapResponse);
  if(!value||typeof value!=='object')return value;
  const result={};for(const [key,item] of Object.entries(value)){
   if(key==='list_scopes'&&item&&typeof item==='object')result[key]=Object.fromEntries(Object.entries(item).map(([scope,ids])=>[scope,Array.isArray(ids)?ids.map(logical):ids]));
   else if(['id','parent_id','project_id','tag_id','source_inbox_action_id','inbox_action_id','dependent','prerequisite','changedIds','reopen_ancestors'].includes(key))result[key]=Array.isArray(item)?item.map(logical):logical(item);
   else result[key]=mapResponse(item);
  }return result;
 }
 const call=async(name,args={})=>{
  if(name==='capture_intent'){
   const result=await actionCall(f.db,owner,name,args,()=>now),captureId=result.result.resolved.actions[0].id;
   aliases.set(args.operationId,captureId);reverseAliases.set(captureId,args.operationId);return mapResponse(result);
  }
  if(name==='apply_change'){
   const translated=publicChange(args.kind,args.payload),request={...args,kind:translated.kind,payload:translated.payload};
   const result=await actionCall(f.db,owner,name,request,()=>now);
   if(translated.alias){const entityId=result.result.resolved[translated.kind==='project_get_or_create'?'project':translated.kind==='tag_get_or_create'?'tag':'actions']?.id??result.result.resolved.actions?.[0]?.id;aliases.set(translated.alias,entityId);reverseAliases.set(entityId,translated.alias);}
   if(translated.aliasActions)for(const [ref,alias] of translated.aliasActions){const entityId=result.result.resolved.actions.find(action=>action.ref===ref).id;aliases.set(alias,entityId);reverseAliases.set(entityId,alias);}
   return mapResponse(result);
  }
  if(name==='preview_change'){
   const translated=publicChange(args.kind,args.payload),result=await actionCall(f.db,owner,name,{...args,kind:translated.kind,payload:translated.payload},()=>now);
   if(translated.aliasActions&&result.resolved?.actions)for(const item of result.resolved.actions){const alias=translated.aliasActions.get(item.ref);if(alias){aliases.set(alias,item.id);reverseAliases.set(item.id,alias);}}
   return mapResponse(result);
  }
  if(name==='query_actions'){
   const mapped={...args,...(args.project_id?{project_id:actual(args.project_id)}:{}),...(args.tag_id?{tag_id:actual(args.tag_id)}:{})};
   return mapResponse(await actionCall(f.db,owner,name,mapped,()=>now));
  }
  return mapResponse(await actionCall(f.db,owner,name,args,()=>now));
 },list=()=>call('list_actions');
 const apply=async(kind,payload,operationId=crypto.randomUUID())=>call('apply_change',{schemaVersion:2,operationId,expectedRevision:(await list()).revision,kind,payload});
 const p=crypto.randomUUID(),a=crypto.randomUUID(),b=crypto.randomUUID(),d=crypto.randomUUID();
 async function seedGraph(){await apply('add',{id:p,title:'資料を作る'});await apply('add',{id:a,title:'数字確認',parent_id:p});await apply('add',{id:b,title:'図作成',parent_id:p});}
 return {f,call,list,apply,p,a,b,d,seedGraph,setNow:value=>{now=value;}};
}
test('date-only Defer requires a timezone in that request, without storing a setting',async context=>{const {call,list,apply}=scenario(context);assert.equal(dateDefer('2026-10-02','Asia/Tokyo'),'2026-10-02T00:00:00.000Z');assert.throws(()=>dateDefer('2026-02-30','Asia/Tokyo'));const r=await apply('add',{title:'local date'}),id=r.result.resolved.actions[0].id;const preview=await call('preview_change',{expectedRevision:r.revision,kind:'defer',payload:{id,date:'2026-10-02',timezone:'Asia/Tokyo'}});assert.deepEqual(preview.payload,{id,until:'2026-10-02T00:00:00.000Z'});await apply(preview.kind,preview.payload);assert.equal('timezone' in await list(),false);});
test('legacy rows migrate without loss',async context=>{scenario(context);const x=new DatabaseSync(':memory:');x.exec(readFileSync('drizzle/0000_worthless_pyro.sql','utf8'));x.prepare('INSERT INTO tasks VALUES(?,?,?,?,?,?,?,?)').run('A',crypto.randomUUID(),'既存','初期',5,'old','2026-01-01','2026-01-01');x.exec(readFileSync('drizzle/0001_structured_todo.sql','utf8'));assert.equal(x.prepare('SELECT status,revision FROM tasks').get().status,'open');assert.equal(x.prepare('SELECT revision FROM tasks').get().revision,5);assert.equal(x.prepare('SELECT revision FROM owner_state').get().revision,0);x.close();});
test('Inbox input is structured in place',async context=>{const {call,list,apply,p,a,b}=scenario(context);const s=await list(),cap=crypto.randomUUID();await call('capture_intent',{schemaVersion:2,operationId:cap,expectedRevision:s.revision,title:'原文の内容',text:'資料を作る。数字確認と図作成。参考URLも残す。'});await apply('structure',{inbox_action_id:cap,actions:[{id:p,title:'資料を作る',notes:'参考URLは行動ではない'},{id:a,title:'数字確認',parent_id:p},{id:b,title:'図作成',parent_id:p}],dependencies:[{dependent:b,prerequisite:a}]});const r=await list();assert.equal(r.actions.find(t=>t.id===p).notes,'参考URLは行動ではない');assert.equal('captures' in r,false);assert.equal(r.actions.length,3);await assert.rejects(apply('structure',{inbox_action_id:cap,actions:[],dependencies:[]}),e=>e.code==='invalid_input');});
test('later siblings are available without prerequisite state',async context=>{const {list,b,seedGraph}=scenario(context);await seedGraph();const action=(await list()).actions.find(x=>x.id===b);assert.equal(action.view,'normal');assert.equal('waiting' in action,false);assert.equal('prerequisites' in action,false);});
test('fresh reads deliver interaction policy and exact list scopes',async context=>{const {call,b,seedGraph}=scenario(context);await seedGraph();const r=await call('get_relevant_context');assert.equal(typeof r.assistance_policy,'string');assert(r.assistance_policy.includes('status'));assert.deepEqual(r.list_scopes.normal,r.actions.filter(t=>t.view==='normal').map(t=>t.id));assert(r.list_scopes.normal.includes(b));assert.equal(r.list_scopes.cancelled.length,0);});
test('cycle rejected atomically',async context=>{const {list,apply,p,a,b,seedGraph}=scenario(context);await seedGraph();const before=await list();await assert.rejects(apply('edit',{id:p,parent_id:a}));await assert.rejects(apply('dependency',{dependent:a,prerequisite:b,enabled:true}),e=>e.code==='unknown_kind');assert.equal((await list()).revision,before.revision);});
test('C1 parent Defer preserves later child instant and deadline',async context=>{const {call,list,apply,p,a,b,seedGraph,setNow}=scenario(context);await seedGraph();await apply('edit',{id:b,due_at:'2026-10-03T09:00:00+09:00'});await apply('defer',{id:b,date:'2026-10-04'});const pv=await call('preview_change',{expectedRevision:(await list()).revision,kind:'defer',payload:{id:p,date:'2026-10-02'}});await apply(pv.kind,pv.payload);assert((await list()).actions.every(x=>x.view==='deferred'));await apply('release',{id:a});assert.equal((await list()).actions.find(x=>x.id===a).is_deferred,true);setNow('2026-10-02T00:00:00.000Z');const r=await list();assert.equal(r.actions.find(x=>x.id===p).view,'normal');assert.equal(r.actions.find(x=>x.id===b).view,'deferred');assert.equal(r.actions.find(x=>x.id===b).due_at,'2026-10-03T00:00:00.000Z');});
test('parent completion atomically completes descendants and preserves their fields',async context=>{const {call,list,apply,p,a,b,seedGraph}=scenario(context);await seedGraph();await apply('edit',{id:b,status:'on-hold',defer_until:'2026-10-05T00:00:00.000Z'});const before=await list();const preview=await call('preview_change',{expectedRevision:before.revision,kind:'edit',payload:{id:p,status:'completed'}});assert.deepEqual(new Set(preview.affected.map(x=>x.id)),new Set([p,a,b]));const completed=await apply('edit',{id:p,status:'completed'});assert(completed.actions.every(x=>x.status==='completed'));assert.equal(completed.actions.find(x=>x.id===b).defer_until,'2026-10-05T00:00:00.000Z');await call('undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:completed.revision,undoOf:completed.result.operationId});const restored=await list();assert.equal(restored.actions.find(x=>x.id===p).status,'active');assert.equal(restored.actions.find(x=>x.id===b).status,'on-hold');await apply('complete',{id:p});await apply('status',{id:b,status:'active'});assert.equal((await list()).actions.find(x=>x.id===p).status,'completed');});
test('completion and reopen preserve Defer with no execution restriction',async context=>{const {call,list,apply,p,a,b,seedGraph}=scenario(context);await seedGraph();await apply('defer',{id:b,date:'2026-10-04'});await apply('complete',{id:a});await apply('complete',{id:b});await apply('complete',{id:p});const s=await list(),preview=await call('preview_change',{expectedRevision:s.revision,kind:'reopen',payload:{id:b}});assert.equal(preview.payload.reopen_ancestors,undefined);await apply(preview.kind,preview.payload);assert.equal((await list()).actions.find(x=>x.id===b).view,'deferred');await apply('reopen',{id:a,reopen_ancestors:[]});assert.equal((await list()).actions.find(x=>x.id===b).status,'active');});
test('C3 another request timezone never changes an already saved instant',async context=>{const {list,apply,b,d,seedGraph}=scenario(context);await seedGraph();await apply('defer',{id:b,date:'2026-10-04',timezone:'Asia/Tokyo'});const instant=(await list()).actions.find(x=>x.id===b).defer_until;await apply('add',{id:d,title:'different locale'});await apply('defer',{id:d,date:'2026-10-04',timezone:'UTC'});assert.equal((await list()).actions.find(x=>x.id===b).defer_until,instant);assert.equal((await list()).actions.find(x=>x.id===d).defer_until,'2026-10-04T09:00:00.000Z');});
test('BUG-01 receipt binds original full payload even after later edits',async context=>{const {call,list,apply,d,seedGraph}=scenario(context);await seedGraph();await apply('add',{id:d,title:'初期'});const s=await list(),op=crypto.randomUUID(),args={schemaVersion:2,operationId:op,expectedRevision:s.revision,kind:'edit',payload:{id:d,title:'編集'}};const first=await call('apply_change',args);assert.equal((await call('apply_change',args)).revision,first.revision);await apply('edit',{id:d,title:'最新'});const replay=await call('apply_change',args);assert.equal(replay.actions.find(x=>x.id===d).title,'最新');await assert.rejects(call('apply_change',{...args,expectedRevision:replay.revision,payload:{id:d,title:'別入力'}}),e=>e.code==='idempotency_conflict');});
test('stale revision rejects without partial writes',async context=>{const {call,list,apply,d,seedGraph}=scenario(context);await seedGraph();await apply('add',{id:d,title:'最新'});const s=await list();await apply('edit',{id:d,notes:'本人が入力した待機'});await assert.rejects(call('apply_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:s.revision,kind:'edit',payload:{id:d,title:'古い案'}}),e=>e.code==='conflict');assert.equal((await list()).actions.find(x=>x.id===d).title,'最新');});
test('lost response retry replays one committed operation',async context=>{const {f,call,list,apply,d,seedGraph}=scenario(context);await seedGraph();await apply('add',{id:d,title:'最新'});const s=await list(),op=crypto.randomUUID(),args={schemaVersion:2,operationId:op,expectedRevision:s.revision,kind:'edit',payload:{id:d,title:'不明後'}};f.lose();await assert.rejects(call('apply_change',args),/lost response/);assert.equal((await call('apply_change',args)).revision,s.revision+1);});
test('Undo unrelated changes allowed, changed target rejected',async context=>{const {call,list,apply,a,d,seedGraph}=scenario(context);await seedGraph();await apply('add',{id:d,title:'不明後'});const r=await apply('edit',{id:d,title:'Undo前'}),op=r.result.operationId;await apply('edit',{id:a,notes:'待ち'});let s=await list();await call('undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:s.revision,undoOf:op});assert.equal((await list()).actions.find(x=>x.id===d).title,'不明後');const r2=await apply('edit',{id:d,title:'旧訂正'});await apply('edit',{id:d,title:'新訂正'});s=await list();await assert.rejects(call('undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:s.revision,undoOf:r2.result.operationId}),e=>e.code==='undo_conflict');});
test('future completed action never reopens on time passage',async context=>{const {list,apply,b,seedGraph,setNow}=scenario(context);await seedGraph();await apply('defer',{id:b,date:'2026-10-04'});await apply('complete',{id:b});setNow('2026-10-06T00:00:00.000Z');assert.equal((await list()).actions.find(x=>x.id===b).view,'completed');});
test('SQL failure rolls CAS, catalog row and identity ledger back together',async context=>{const {f,list,apply}=scenario(context);const created=await apply('project_get_or_create',{name:'rollback'}),id=created.result.resolved.project.id,before=await list(),ledger=f.sql.prepare("SELECT kind,identity,revision FROM catalog_identity_ledger WHERE owner='fictional-A' ORDER BY kind,identity").all();f.sql.exec("CREATE TRIGGER reject_receipt BEFORE INSERT ON operations BEGIN SELECT RAISE(ABORT,'injected'); END;");await assert.rejects(apply('project_edit',{id,name:'failed edit'}));f.sql.exec('DROP TRIGGER reject_receipt');const after=await list();assert.equal(after.revision,before.revision);assert.equal(after.projects[0].name,'rollback');assert.deepEqual(f.sql.prepare("SELECT kind,identity,revision FROM catalog_identity_ledger WHERE owner='fictional-A' ORDER BY kind,identity").all(),ledger);});
test('unknown operation status and old UI schema explicit',async context=>{const {call}=scenario(context);assert.equal((await call('operation_status',{operationId:crypto.randomUUID()})).status,'not_observed');await assert.rejects(call('add_action',{title:'旧',request_id:crypto.randomUUID()}),e=>e.code==='schema_mismatch');});
test('simultaneous writes only one winner and no receipt for loser',async context=>{const {f,call,list,apply,d,seedGraph}=scenario(context);await seedGraph();await apply('add',{id:d,title:'最新'});const s=await list(),ops=[crypto.randomUUID(),crypto.randomUUID()];const r=await Promise.allSettled(ops.map((operationId,i)=>call('apply_change',{schemaVersion:2,operationId,expectedRevision:s.revision,kind:'edit',payload:{id:d,title:'並行'+i}})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(r.filter(x=>x.status==='rejected'&&x.reason.code==='conflict').length,1);assert.equal((await list()).revision,s.revision+1);assert.equal(f.sql.prepare('SELECT count(*) n FROM operations WHERE operation_id IN (?,?)').get(...ops).n,1);});
test('removed timezone-setting operation is rejected without writes',async context=>{const {list,apply,seedGraph}=scenario(context);await seedGraph();const before=await list();await assert.rejects(apply('timezone',{timezone:'UTC'}),e=>e.code==='unknown_kind');assert.deepEqual(await list(),before);});
test('unresolved input survives as an ordinary Inbox action',async context=>{const {call,list,apply,d,seedGraph}=scenario(context);await seedGraph();await apply('add',{id:d,title:'最新'});const before=await list(),op=crypto.randomUUID();await call('capture_intent',{schemaVersion:2,operationId:op,expectedRevision:before.revision,title:'片付けを検討',text:'実家の片付けが気になるが、どこまでやるか未定'});const r=await call('get_relevant_context');assert.equal(r.actions.length,before.actions.length+1);assert.equal(r.actions.find(t=>t.id===op).title,'片付けを検討');assert.equal(r.actions.find(t=>t.id===op).notes,'実家の片付けが気になるが、どこまでやるか未定');assert(r.list_scopes.inbox.includes(op));});
test('withdrawal retains record and receipt, replays and supports Undo',async context=>{const {call,list,apply,seedGraph}=scenario(context);await seedGraph();const tid=crypto.randomUUID();await apply('add',{id:tid,title:'取り下げ候補',notes:'来週やりたい。締切ではない。'});const s=await list(),args={schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:s.revision,kind:'cancel',payload:{id:tid}};const preview=await call('preview_change',{expectedRevision:s.revision,kind:'cancel',payload:{id:tid}});assert.equal(preview.affected[0].view,'cancelled');await call('apply_change',args);const r=await call('apply_change',args),t=r.actions.find(t=>t.id===tid);assert.equal(t.status,'dropped');assert.equal(t.view,'cancelled');assert.equal(t.due_at,null);assert(t.notes.includes('締切ではない'));await call('undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:r.revision,undoOf:args.operationId});assert.equal((await list()).actions.find(t=>t.id===tid).status,'active');});
test('withdrawal retains graph relations without forcing pre-cleanup',async context=>{const {list,apply,p,a,b,seedGraph}=scenario(context);await seedGraph();await apply('cancel',{id:p});await apply('cancel',{id:a});const r=await list();assert.equal(r.actions.find(x=>x.id===b).parent_id,p);assert.equal('prerequisites' in r.actions.find(x=>x.id===b),false);await apply('edit',{id:a,notes:'記録訂正',status:'active'});assert.equal((await list()).actions.find(x=>x.id===b).view,'normal');});
test('project/tag catalog migration is additive over legacy rows',async context=>{scenario(context);const x=new DatabaseSync(':memory:');x.exec(readFileSync('drizzle/0000_worthless_pyro.sql','utf8'));x.prepare('INSERT INTO tasks VALUES(?,?,?,?,?,?,?,?)').run('A',crypto.randomUUID(),'既存','初期',3,'old','2026-01-01','2026-01-01');x.exec(readFileSync('drizzle/0001_structured_todo.sql','utf8'));x.exec(readFileSync('drizzle/0002_worthless_lorna_dane.sql','utf8'));x.exec(readFileSync('drizzle/0003_absent_landau.sql','utf8'));assert.equal(x.prepare('SELECT count(*) n FROM tasks').get().n,1);assert.equal(x.prepare('SELECT project_id FROM tasks').get().project_id,null);assert.equal(x.prepare('SELECT catalog_revision FROM owner_state').get().catalog_revision,0);for(const name of ['projects','tags','task_tags'])assert.equal(x.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(name).name,name);x.close();});
test('0004 backfills latest catalog identity revisions and tolerates old receipts without catalog arrays',async context=>{
 scenario(context);const x=new DatabaseSync(':memory:');for(const file of ['0000_worthless_pyro','0001_structured_todo','0002_worthless_lorna_dane','0003_absent_landau'])x.exec(readFileSync(`drizzle/${file}.sql`,'utf8'));
 const owner='legacy',project=crypto.randomUUID(),deleted=crypto.randomUUID(),tag=crypto.randomUUID(),action=crypto.randomUUID(),fallback=crypto.randomUUID();
 x.prepare('INSERT INTO owner_state(owner,revision) VALUES(?,9)').run(owner);
 x.prepare('INSERT INTO projects(owner,id,name,parent_id,revision,created_at,updated_at) VALUES(?,?,?,NULL,1,?,?)').run(owner,project,'Project','old','old');
 x.prepare('INSERT INTO projects(owner,id,name,parent_id,revision,created_at,updated_at) VALUES(?,?,?,NULL,1,?,?)').run(owner,fallback,'Legacy without history','old','old');
 x.prepare('INSERT INTO tags(owner,id,name,parent_id,revision,created_at,updated_at) VALUES(?,?,?,NULL,1,?,?)').run(owner,tag,'Tag','old','old');
 x.prepare('INSERT INTO task_tags(owner,task_id,tag_id,revision) VALUES(?,?,?,1)').run(owner,action,tag);
 const insert=x.prepare('INSERT INTO operations(owner,operation_id,canonical_payload,result,delta,revision_before,revision_after,undo_of,created_at) VALUES(?,?,?,?,?,?,?,?,?)');
 const record=(op,revision,delta)=>insert.run(owner,op,'{}','{}',JSON.stringify(delta),revision-1,revision,null,'old');
 record(crypto.randomUUID(),2,{projects:[{before:null,after:{id:project}}],tags:[],task_tags:[]});
 record(crypto.randomUUID(),4,{projects:[{before:{id:project},after:{id:project}}],tags:[{before:null,after:{id:tag}}],task_tags:[{before:null,after:{task_id:action,tag_id:tag}}]});
 record(crypto.randomUUID(),6,{projects:[{before:{id:deleted},after:null}],tags:[],task_tags:[{before:{task_id:action,tag_id:tag},after:null}]});
 record(crypto.randomUUID(),9,{tasks:[]});
 x.exec(readFileSync('drizzle/0004_material_silhouette.sql','utf8'));
 const revision=(kind,identity)=>x.prepare('SELECT revision FROM catalog_identity_ledger WHERE owner=? AND kind=? AND identity=?').get(owner,kind,identity)?.revision;
 assert.equal(revision('project',project),4);assert.equal(revision('project',deleted),6);assert.equal(revision('project',fallback),9);assert.equal(revision('tag',tag),4);assert.equal(revision('task_tag',`${action}:${tag}`),6);
 x.close();
});
test('0004 refuses duplicate natural keys without merging existing catalog rows',async context=>{
 scenario(context);const x=new DatabaseSync(':memory:');for(const file of ['0000_worthless_pyro','0001_structured_todo','0002_worthless_lorna_dane','0003_absent_landau'])x.exec(readFileSync(`drizzle/${file}.sql`,'utf8'));
 const owner='duplicate',insert=x.prepare('INSERT INTO projects(owner,id,name,parent_id,revision,created_at,updated_at) VALUES(?,?,?,NULL,1,?,?)');
 insert.run(owner,crypto.randomUUID(),'same','old','old');insert.run(owner,crypto.randomUUID(),'same','old','old');
 assert.throws(()=>x.exec(readFileSync('drizzle/0004_material_silhouette.sql','utf8')),/UNIQUE constraint failed/);assert.equal(x.prepare('SELECT count(*) n FROM projects WHERE owner=? AND name=?').get(owner,'same').n,2);x.close();
});
test('project/tag catalog persists, derives paths and queries descendants',async context=>{const {call,list,apply}=scenario(context);const p=crypto.randomUUID(),c=crypto.randomUUID(),t1=crypto.randomUUID(),t2=crypto.randomUUID(),action=crypto.randomUUID();await apply('project_add',{id:p,name:'仕事'});await apply('project_add',{id:c,name:'資料',parent_id:p});await apply('tag_add',{id:t1,name:'重要'});await apply('tag_add',{id:t2,name:'今週',parent_id:t1});await apply('add',{id:action,title:'作業'});await apply('action_project',{id:action,project_id:c});await apply('action_tag',{id:action,tag_id:t2,enabled:true});const r=await list();assert.equal(r.projects.find(x=>x.id===c).path,'仕事/資料');assert.equal(r.tags.find(x=>x.id===t2).path,'重要/今週');const q=await call('query_actions',{project_id:p,include_descendants:true});assert.equal(q.actions.length,1);assert.equal(q.actions[0].id,action);assert.equal(q.actions[0].project_path,'仕事/資料');assert.deepEqual(q.actions[0].tags.map(x=>x.id),[t2]);assert.equal((await call('query_actions',{tag_id:t1,include_descendants:true})).actions[0].id,action);assert.equal((await call('query_actions',{project_id:p})).actions.length,0);});
test('project cycle and dangling reference rejected atomically',async context=>{const {list,apply}=scenario(context);const a=crypto.randomUUID(),b=crypto.randomUUID();await apply('project_add',{id:a,name:'A'});await apply('project_add',{id:b,name:'B',parent_id:a});const before=await list();await assert.rejects(apply('project_move',{id:a,parent_id:b}),e=>e.code==='cycle');await assert.rejects(apply('action_project',{id:crypto.randomUUID(),project_id:a}),e=>e.code==='not_found');await assert.rejects(apply('tag_add',{id:crypto.randomUUID(),name:'x',parent_id:crypto.randomUUID()}),e=>e.code==='not_found');assert.equal((await list()).revision,before.revision);});
test('project/tag deletion refuses references and Undo restores the node',async context=>{const {call,list,apply}=scenario(context);const p=crypto.randomUUID(),action=crypto.randomUUID();await apply('project_add',{id:p,name:'P'});await apply('add',{id:action,title:'t'});await apply('action_project',{id:action,project_id:p});await assert.rejects(apply('project_remove',{id:p}),e=>e.code==='related_actions');await apply('action_project',{id:action,project_id:null});const del=await apply('project_remove',{id:p});assert.equal((await list()).projects.length,0);const s=await list();await call('undo_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:s.revision,undoOf:del.result.operationId});assert.equal((await list()).projects.length,1);assert.equal((await list()).projects[0].name,'P');});
test('catalog changes stay owner isolated in one database and support identical resend',async context=>{const {f,call,list,apply}=scenario(context);const p=crypto.randomUUID(),op=crypto.randomUUID();await apply('project_add',{id:p,name:'P'});const s=await list(),args={schemaVersion:2,operationId:op,expectedRevision:s.revision,kind:'tag_add',payload:{id:crypto.randomUUID(),name:'T'}};await call('apply_change',args);assert.equal((await call('apply_change',args)).tags.length,1);const bClock=()=> '2026-10-01T00:00:00.000Z';const foreign=await actionCall(f.db,'fictional-B','list_actions',{},bClock);assert.equal(foreign.projects.length,0);assert.equal(foreign.tags.length,0);assert.equal(foreign.actions.length,0);await assert.rejects(actionCall(f.db,'fictional-B','apply_change',{schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:0,kind:'action_project',payload:{id:crypto.randomUUID(),project_id:p}},bClock),e=>e.code==='not_found');});

test('Undo persists successfully after the detached tag was deleted and replays',async context=>{
 const {call,list,apply}=scenario(context),action=crypto.randomUUID(),tag=crypto.randomUUID();
 await apply('add',{id:action,title:'action'});
 await apply('tag_add',{id:tag,name:'deleted'});
 await apply('action_tag',{id:action,tag_id:tag,enabled:true});
 const detached=await apply('action_tag',{id:action,tag_id:tag,enabled:false});
 await apply('tag_remove',{id:tag});
 const before=await list(),args={schemaVersion:2,operationId:crypto.randomUUID(),expectedRevision:before.revision,undoOf:detached.result.operationId};
 const restored=await call('undo_change',args);
 assert.equal(restored.revision,before.revision+1);
 assert.equal(restored.tags.length,0);
 assert.deepEqual(restored.actions.find(row=>row.id===action).tags,[]);
 const replay=await call('undo_change',args);
 assert.equal(replay.revision,restored.revision);
});
